### ISSUE TITLE
android.database.sqlite.SQLiteException: not an error (code 0)

### ISSUE THREAD

**Issue by huzaifaiftikhar** [openfoodfacts/openfoodfacts-androidapp#1072]
FATAL EXCEPTION: main
                                                                                       Process: openfoodfacts.github.scrachx.openfood, PID: 15603
                                                                                       android.database.sqlite.SQLiteException: not an error (code 0)
                                                                                           at android.database.sqlite.SQLiteConnection.nativeRegisterLocalizedCollators(Native Method)
                                                                                           at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:361)
                                                                                           at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:218)
                                                                                           at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
                                                                                           at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                                           at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                                           at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                                           at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
                                                                                           at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
                                                                                           at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
                                                                                           at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:652)
                                                                                           at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:289)
                                                                                           at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
                                                                                           at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                                           at org.greenrobot.greendao.database.DatabaseOpenHelper.getWritableDb(DatabaseOpenHelper.java:59)
                                                                                           at openfoodfacts.github.scrachx.openfood.utils.Utils.getDaoSession(Utils.java:329)
                                                                                           at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient.<init>(OpenFoodAPIClient.java:102)
                                                                                           at openfoodfacts.github.scrachx.openfood.jobs.SavedProductUploadJob.onStartJob(SavedProductUploadJob.java:21)
                                                                                           at com.firebase.jobdispatcher.JobService$2.run(JobService.java:164)
                                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6165)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

This might be related to the merge #887

**Comment by jaztriumph** [comment]
@huzaifaiftikhar I have made the issue #1068 on this. I am about to make a pull request resolving this soon.

**Comment by huzaifaiftikhar** [comment]
Closing this via #1079
