### ISSUE TITLE
App crashes on launching offlineEditFragment when it contains a single item.

### ISSUE THREAD

**Issue by Shubham2320** [openfoodfacts/openfoodfacts-androidapp#1129]
**Summary:** 

App crashes on launching offlineEditFragment when it contains a single item.

**Steps to reproduce:** 

How can we reproduce the issue?

**Add system logs:**

E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: openfoodfacts.github.scrachx.openfood, PID: 10307
                                                   java.lang.IllegalStateException: Circular dependencies cannot exist in RelativeLayout
                                                       at android.widget.RelativeLayout$DependencyGraph.getSortedViews(RelativeLayout.java:1727)
                                                       at android.widget.RelativeLayout.sortChildren(RelativeLayout.java:383)
                                                       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:390)
                                                       at android.view.View.measure(View.java:18827)
                                                       at android.widget.ListView.setupChild(ListView.java:1958)
                                                       at android.widget.ListView.makeAndAddView(ListView.java:1879)
                                                       at android.widget.ListView.fillDown(ListView.java:702)
                                                       at android.widget.ListView.fillFromTop(ListView.java:763)
                                                       at android.widget.ListView.layoutChildren(ListView.java:1685)
                                                       at android.widget.AbsListView.onLayout(AbsListView.java:2148)
                                                       at android.view.View.layout(View.java:16669)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                       at android.view.View.layout(View.java:16669)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                       at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1197)
                                                       at android.view.View.layout(View.java:16669)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                       at android.view.View.layout(View.java:16669)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                       at android.view.View.layout(View.java:16669)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                       at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1172)
                                                       at android.view.View.layout(View.java:16669)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                       at android.view.View.layout(View.java:16669)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                       at android.view.View.layout(View.java:16669)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                       at android.view.View.layout(View.java:16669)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                       at android.view.View.layout(View.java:16669)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                       at android.view.View.layout(View.java:16669)
                                                       at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2207)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1963)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6064)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:672)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:608)
                                                   	at android.view.Choreographer$FrameDisplayEventReceiver.run(C

**Expected behaviour:** 

There should be the list of items waiting to be sent online.

**Observed behaviour:** 

App crashes.

**Device and Android version:** 
Android 6.0

**Comment by Shubham2320** [comment]
I would work on this.

**Comment by Shubham2320** [comment]
I've figured it out, it is happening because of circular chaining of views inside relativeLayout of save_list_item.xml and going to a send PR asap :).
