### ISSUE TITLE
 android.content.ActivityNotFoundException: No Activity found to handle Intent

### ISSUE THREAD

**Issue by iml-v** [openfoodfacts/openfoodfacts-androidapp#1210]
this  found in off SummaryProductFragment on clicking on "Link to product page "
**Add system logs:**
```03-12 05:11:10.694 20903-20903/openfoodfacts.github.scrachx.openfood E/InputEventReceiver: Exception dispatching input event.
03-12 05:11:10.694 20903-20903/openfoodfacts.github.scrachx.openfood E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
03-12 05:11:10.699 20903-20903/openfoodfacts.github.scrachx.openfood E/MessageQueue-JNI: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=bombusenergy.com pkg=com.sec.android.app.sbrowser launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } (has extras) }
                                                                                             at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1844)
                                                                                             at android.app.Instrumentation.execStartActivity(Instrumentation.java:1531)
                                                                                             at android.app.Activity.startActivityForResult(Activity.java:4404)
                                                                                             at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                                                                                             at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
                                                                                             at android.app.Activity.startActivityForResult(Activity.java:4363)
                                                                                             at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:732)
                                                                                             at android.app.Activity.startActivity(Activity.java:4687)
                                                                                             at android.support.v4.content.ContextCompat.startActivity(ContextCompat.java:143)
                                                                                             at android.support.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:262)
                                                                                             at openfoodfacts.github.scrachx.openfood.views.customtabs.CustomTabActivityHelper.openCustomTab(CustomTabActivityHelper.java:57)
                                                                                             at openfoodfacts.github.scrachx.openfood.fragments.SummaryProductFragment$1.onClick(SummaryProductFragment.java:368)
                                                                                             at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:217)
                                                                                             at android.widget.TextView.onTouchEvent(TextView.java:10123)
                                                                                             at android.view.View.dispatchTouchEvent(View.java:10779)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                             at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:605)
                                                                                             at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1895)
                                                                                             at android.app.Activity.dispatchTouchEvent(Activity.java:3241)
                                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                                             at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:567)
                                                                                             at android.view.View.dispatchPointerEvent(View.java:11008)
                                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5155)
                                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5007)
                                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
                                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4585)
                                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4551)
                                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4684)
                                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4559)
                                                                                         	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:
03-12 05:11:10.699 20903-20903/openfoodfacts.github.scrachx.openfood D/AndroidRuntime: Shutting down VM
03-12 05:11:10.700 20903-20903/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: openfoodfacts.github.scrachx.openfood, PID: 20903
                                                                                       android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=bombusenergy.com pkg=com.sec.android.app.sbrowser launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } (has extras) }
                                                                                           at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1844)
                                                                                           at android.app.Instrumentation.execStartActivity(Instrumentation.java:1531)
                                                                                           at android.app.Activity.startActivityForResult(Activity.java:4404)
                                                                                           at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                                                                                           at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
                                                                                           at android.app.Activity.startActivityForResult(Activity.java:4363)
                                                                                           at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:732)
                                                                                           at android.app.Activity.startActivity(Activity.java:4687)
                                                                                           at android.support.v4.content.ContextCompat.startActivity(ContextCompat.java:143)
                                                                                           at android.support.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:262)
                                                                                           at openfoodfacts.github.scrachx.openfood.views.customtabs.CustomTabActivityHelper.openCustomTab(CustomTabActivityHelper.java:57)
                                                                                           at openfoodfacts.github.scrachx.openfood.fragments.SummaryProductFragment$1.onClick(SummaryProductFragment.java:368)
                                                                                           at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:217)
                                                                                           at android.widget.TextView.onTouchEvent(TextView.java:10123)
                                                                                           at android.view.View.dispatchTouchEvent(View.java:10779)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
                                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
                                                                                           at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:605)
                                                                                           at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1895)
                                                                                           at android.app.Activity.dispatchTouchEvent(Activity.java:3241)
                                                                                           at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                                           at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                                                                                           at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:567)
                                                                                           at android.view.View.dispatchPointerEvent(View.java:11008)
                                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5155)
                                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5007)
                                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
                                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4585)
                                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4551)
                                                                                           at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4684)
03-12 05:11:10.701 20903-20903/openfoodfacts.github.scrachx.openfood E/AndroidRuntime:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4559)
                                                                                           at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4741)
                                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
                                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4585)
                                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4551)
                                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4559)
                                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
                                                                                           at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
                                                                                           at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7024)
                                                                                           at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6985)
                                                                                           at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7202)
                                                                                           at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                                           at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                           at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                                           at android.os.Looper.loop(Looper.java:136)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)```

**Device and Android version:** 
Android 7.0 API 24
i am working on this

**Comment by jaztriumph** [comment]
@iml-v  this is same as #1201.

**Comment by iml-v** [comment]
Thanks @jaztriumph  ok I am closing this .
