### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 6(offset:6).state:8 android.support.v7.widget.RecyclerView

### ISSUE THREAD

**Issue by huzaifaiftikhar** [openfoodfacts/openfoodfacts-androidapp#1268]
FATAL EXCEPTION: main
                                                                                     Process: openfoodfacts.github.scrachx.openfood, PID: 3820
                                                                                     java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 6(offset:6).state:8 android.support.v7.widget.RecyclerView{32a83f5 VFED..... .F...... 0,0-1080,1540 #7f090139 app:id/products_recycler_view}, adapter:openfoodfacts.github.scrachx.openfood.views.adapters.ProductsRecyclerViewAdapter@1cd058a, layout:android.support.v7.widget.LinearLayoutManager@eb797fb, context:openfoodfacts.github.scrachx.openfood.views.ProductBrowsingListActivity@4610689
                                                                                         at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5654)
                                                                                         at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
                                                                                         at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
                                                                                         at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
                                                                                         at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
                                                                                         at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
                                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6165)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)

**Steps to reproduce:** 
Open "your contributions", when it is loaded try to refresh it by swiping down, while it is refreshing quickly scroll up.

**Screenshots:** 
![videotogif_2018 03 18_01 04 11](https://user-images.githubusercontent.com/10832531/37559250-aa216950-2a48-11e8-933e-fbf663cf7eb9.gif)

**Comment by jaztriumph** [comment]
Not only for "your contributions" same thing is happening  for very view that's using 'productBrowsingListActivity", even the search results.
I will work on this.
