### ISSUE TITLE
Contribution - Launching app on Android Studio

### ISSUE THREAD

**Issue by herau** [openfoodfacts/OpenFoodFacts-androidApp#134]
Hello,
i want to contribute for this project but i have an issue during the launching of the App.
When i'm trying to launch the application thought Android studio with a device (Android 6.0.1 App 23), i have this kind of message: 

```
09/27 18:12:14: Launching app
$ adb push /Volumes/diskE/Users/n27/IdeaProjects/OpenFoodFacts-androidApp-test/app/build/outputs/apk/app-debug.apk /data/local/tmp/openfoodfacts.github.scrachx.openfood
$ adb shell pm install -r "/data/local/tmp/openfoodfacts.github.scrachx.openfood"
	pkg: /data/local/tmp/openfoodfacts.github.scrachx.openfood
Success
$ adb shell am start -n "openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.SplashActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 788 on device oneplus-one_e1003-964c33d6
I/asset: Successfully loaded resource /system/framework/oxygen-framework-res.apk
W/System: ClassLoader referenced unknown path: /data/app/openfoodfacts.github.scrachx.openfood-1/lib/arm
I/InstantRun: Instant Run Runtime started. Android package is openfoodfacts.github.scrachx.openfood, real application class is com.orm.SugarApp.
W/System: ClassLoader referenced unknown path: /data/app/openfoodfacts.github.scrachx.openfood-1/lib/arm
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
D/AppTracker: App Event: start
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I741a3d36ca)
              OpenGL ES Shader Compiler Version: E031.29.00.00
              Build Date: 04/04/16 Mon
              Local Branch: mybranch19053788
              Remote Branch: quic/LA.BF.1.1.3_rb1.12
              Local Patches: NONE
              Reconstruct Branch: NOTHING
I/OpenGLRenderer: Initialized EGL, version 1.4
D/AbstractTracker: Event success
W/nAnnotationIntrospector: Unable to load JDK7 annotation types; will have to skip
W/System.err: WARNING: could not load Java7 Path class
D/Sugar: Fetching properties
E/SQLiteLog: (1) no such table: ADDITIVE
E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                  Process: openfoodfacts.github.scrachx.openfood, PID: 788
                  java.lang.RuntimeException: An error occurred while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:309)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: android.database.sqlite.SQLiteException: no such table: ADDITIVE (code 1): , while compiling: INSERT OR REPLACE  INTO ADDITIVE(RISK,ID,NAME,CODE) VALUES (?,?,?,?)
                      at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                      at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                      at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                      at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                      at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                      at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                      at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1481)
                      at com.orm.SugarRecord.save(SugarRecord.java:280)
                      at com.orm.SugarRecord.save(SugarRecord.java:416)
                      at openfoodfacts.github.scrachx.openfood.views.SplashActivity$GetJson.doInBackground(SplashActivity.java:87)
                      at openfoodfacts.github.scrachx.openfood.views.SplashActivity$GetJson.doInBackground(SplashActivity.java:49)
                      at android.os.AsyncTask$2.call(AsyncTask.java:295)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                      at java.lang.Thread.run(Thread.java:818) 
E/AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()
D/AppTracker: App Event: crash
E/AbstractTracker: mTrackerAsyncQueryHandler is null
D/AppTracker: App Event: stop
E/DeviceManagerUtil: RunningAppProcessInfo is null
E/DeviceManagerUtil: RunningAppProcessInfo is null
D/AbstractTracker: Event success

```

I also have the same issue with the emulator.
Does i miss something ? 

```
$ echo $ANDROID_HOME
/usr/local/Cellar/android-sdk/24.4.1_1
```

**Comment by itchix** [comment]
Try to disable Instant Run for the first time, Sugar ORM (sqlite) have an issue with that...

**Comment by herau** [comment]
None changes after disabling instant run...
Can i disable locally this feature ? With configuration for exemple.

**Comment by itchix** [comment]
See http://stackoverflow.com/questions/35765760/sugar-orm-just-wont-create-tables

**Comment by herau** [comment]
i tried with the last version of sugar `compile 'com.github.satyan:sugar:b16e65326a'` but without any changes...

**Comment by itchix** [comment]
Really weird.. :/ But I'm glad you could fix it!
