### ISSUE TITLE
android.database.sqlite.SQLiteException: duplicate column name: wiki_data_id (code 1): , while compiling: ALTER TABLE additive_name ADD COLUMN 'wiki_data_id' TEXT NOT NULL DEFAULT '';

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1433]
04-09 22:19:57.542 1551-1551/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.openpetfoodfacts.scanner, PID: 1551
    java.lang.RuntimeException: Unable to create application openfoodfacts.github.scrachx.openfood.views.OFFApplication: android.database.sqlite.SQLiteException: duplicate column name: wiki_data_id (code 1): , while compiling: ALTER TABLE additive_name ADD COLUMN 'wiki_data_id' TEXT NOT NULL DEFAULT '';
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5825)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:251)
        at android.app.ActivityThread.main(ActivityThread.java:6572)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.database.sqlite.SQLiteException: duplicate column name: wiki_data_id (code 1): , while compiling: ALTER TABLE additive_name ADD COLUMN 'wiki_data_id' TEXT NOT NULL DEFAULT '';
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:895)
        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:506)
        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
        at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
        at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1677)
        at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1608)
        at org.b.a.b.f.a(Unknown Source:2)
        at openfoodfacts.github.scrachx.openfood.models.DatabaseHelper.upgrade(Unknown Source:29)
        at openfoodfacts.github.scrachx.openfood.models.DatabaseHelper.onUpgrade(Unknown Source:34)
        at org.b.a.b.b.onUpgrade(Unknown Source:4)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:299)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
        at org.b.a.b.b.getWritableDb(Unknown Source:0)
        at openfoodfacts.github.scrachx.openfood.views.OFFApplication.onCreate(Unknown Source:55)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5822)
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:251) 
        at android.app.ActivityThread.main(ActivityThread.java:6572) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by ross-holloway94** [comment]
I'm now having this with OFF too.

**Comment by ross-holloway94** [comment]
We need a way of checking if the column exists before trying to add it in each table.
Method is DatabaseHelper.upgrade() - case 7.

**Comment by Hangman228** [comment]
Not very usefull but I have same error on Android 7.1.2 and crash on start, if you need any logs let me know

**Comment by Hangman228** [comment]
Now fixed (0.8.10) ! I think you can close this one

**Comment by ross-holloway94** [comment]
Thanks @Hangman228 , I forgot to close this.
