### ISSUE TITLE
App crashes on clicking language options on Android 4.4

### ISSUE THREAD

**Issue by jaztriumph** [openfoodfacts/openfoodfacts-androidapp#1451]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 
App crashes on clicking language options inside preference tab on android 4.4.

**Add system logs:**

```openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
Process: openfoodfacts.github.scrachx.openfood, PID: 23681
java.lang.NullPointerException
   at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:394)
   at android.widget.ArrayAdapter.getView(ArrayAdapter.java:362)
   at android.widget.AbsListView.obtainView(AbsListView.java:2300)
   at android.widget.ListView.measureHeightOfChildren(ListView.java:1273)
   at android.widget.ListView.onMeasure(ListView.java:1182)
   at android.view.View.measure(View.java:16834)
   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5379)
   at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
   at android.view.View.measure(View.java:16834)
   at android.support.v7.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:133)
   at android.support.v7.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:63)
   at android.view.View.measure(View.java:16834)
   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5379)
   at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
   at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
   at android.view.View.measure(View.java:16834)
   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5379)
   at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
   at android.view.View.measure(View.java:16834)
   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5379)
   at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
   at android.view.View.measure(View.java:16834)
   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5379)
   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1621)
   at android.widget.LinearLayout.measureVertical(LinearLayout.java:742)
   at android.widget.LinearLayout.onMeasure(LinearLayout.java:607)
   at android.view.View.measure(View.java:16834)
   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5379)
   at android.widget.FrameLayout.onMeasure(FrameLayout.java:340)
   at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2368)
   at android.view.View.measure(View.java:16834)
   at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2246)
   at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1280)
   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1509)
   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1189)
   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6223)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
   at android.view.Choreographer.doCallbacks(Choreographer.java:591)
   at android.view.Choreographer.doFrame(Choreographer.java:560)
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
   at android.os.Handler.handleCallback(Handler.java:808)
   at android.os.Handler.dispatchMessage(Handler.java:103)
   at android.os.Looper.loop(Looper.java:193)
   at android.app.ActivityThread.main(ActivityThread.java:5333)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
   at dalvik.system.NativeStart.main(Native Method)
```

**Expected behavior:** 

On clicking language option, language list preference should appear to select language.

**Device and Android version:** 

HTC 820g+, Android 4.4 KITKAT

**Screenshots:** 
![preference-crash](https://user-images.githubusercontent.com/22943390/38796051-dbe162e2-4177-11e8-9b3b-3ba1096103f6.gif)

**Comment by jaztriumph** [comment]
i am working on this
