### ISSUE TITLE
openfoodfacts.github.scrachx.openfood requested task be persisted for tag: 'upload_saved_product_job' but does not hold the permission android.permission.RECEIVE_BOOT_COMPLETED. This task won't be persisted.

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1716]
```
6-16 18:50:59.027 2443-22552/? E/NetworkScheduler: openfoodfacts.github.scrachx.openfood requested task be persisted for tag: 'upload_saved_product_job' but does not hold the permission android.permission.RECEIVE_BOOT_COMPLETED. This task won't be persisted.
06-16 18:50:59.083 23094-23094/openfoodfacts.github.scrachx.openfood D/AndroidRuntime: Shutting down VM
   
    --------- beginning of crash
06-16 18:50:59.090 23094-23094/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 23094
    android.view.InflateException: Binary XML file line #28: Binary XML file line #28: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #28: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at openfoodfacts.github.scrachx.openfood.fragments.BaseFragment.createView(BaseFragment.java:37)
        at openfoodfacts.github.scrachx.openfood.fragments.HomeFragment.onCreateView(HomeFragment.java:48)
        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2346)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1428)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3248)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3200)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:195)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
        at openfoodfacts.github.scrachx.openfood.views.MainActivity.onStart(MainActivity.java:741)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7152)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2926)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6642)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalArgumentException: The auto-size step granularity (0.0px) is less or equal to (0px)
        at android.widget.TextView.validateAndSetAutoSizeTextTypeUniformConfiguration(TextView.java:1887)
        at android.widget.TextView.setAutoSizeTextTypeUniformWithConfiguration(TextView.java:1713)
06-16 18:50:59.091 23094-23094/openfoodfacts.github.scrachx.openfood E/AndroidRuntime:     at android.support.v7.widget.AppCompatTextView.setAutoSizeTextTypeUniformWithConfiguration(AppCompatTextView.java:239)
        at android.support.v7.widget.AppCompatTextHelper.loadFromAttributes(AppCompatTextHelper.java:196)
        at android.support.v7.widget.AppCompatTextHelperV17.loadFromAttributes(AppCompatTextHelperV17.java:38)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:82)
        at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:72)
        	... 42 more

```

**Comment by teolemon** [comment]
@VaiTon I believe this is fixed by the WorkManager transition
