### ISSUE TITLE
 java.lang.NullPointerException at openfoodfacts.github.scrachx.openfood.views.MainActivity$7.onClick(MainActivity.java:998)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#1917]
``` 
09-23 10:47:57.369 5010-5010/org.openfoodfacts.scanner E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.openfoodfacts.scanner, PID: 5010
    java.lang.NullPointerException
        at java.io.File.<init>(File.java:283)
        at openfoodfacts.github.scrachx.openfood.views.MainActivity$7.onClick(MainActivity.java:998)
        at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by teolemon** [comment]
So this happens when sharing from Google Photos, but when sharing from the files app, it works ok.

**Comment by jaindiv26** [comment]
@teolemon I've tried to reproduce this issue in various devices but every time I share photos from Google Photos it works perfectly fine. Is this issue still happening?
