### ISSUE TITLE
App crashes on pressing back button from search by barcode

### ISSUE THREAD

**Issue by huzaifaiftikhar** [openfoodfacts/openfoodfacts-androidapp#1954]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.

**Summary:** 
App crashes on pressing back button from search by barcode screen.

**Steps to reproduce:** 
- Open the app.
- Navigate to "Search by barcode" menu from the navigation pane.
- Press back button.

**Add system logs:**
```
openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 4117
    java.lang.IllegalStateException: Fragment HomeFragment{2eb61ce} not attached to a context.
        at android.support.v4.app.Fragment.requireContext(Fragment.java:614)
        at android.support.v4.app.Fragment.getResources(Fragment.java:678)
        at openfoodfacts.github.scrachx.openfood.fragments.HomeFragment$1.onResponse(HomeFragment.java:73)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

**Expected behavior:** 
The app shouldn't crash.

**Observed behavior:** 
The app crashes.

**Device and Android version:** 
Motorola Moto G5s
Android 8.1

**Screenshots:** 
<kbd>![videotogif_2018 10 04_01 43 00](https://user-images.githubusercontent.com/10832531/46436707-2fb18980-c777-11e8-862b-069a3378e02c.gif)</kbd>

**Comment by huzaifaiftikhar** [comment]
@teolemon The issue you reported on Slack
