### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setNextFocusDownId(int)' on a null object reference         at openfoodfacts.github.scrachx.openfood.fragments.AddProductNutritionFactsFragment.addNutrientRow(AddProductNutritionFactsFragment.java:1321) 

### ISSUE THREAD

**Issue by KarthikRIyer** [openfoodfacts/openfoodfacts-androidapp#2145]
**Steps to reproduce:** 

How can we reproduce the issue?
The exception occurs on clicking on the edit product icon.

**Add system logs:**
```

19-01-24 20:39:18.334 9204-9204/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 9204
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.EditText.setNextFocusDownId(int)' on a null object reference
        at openfoodfacts.github.scrachx.openfood.fragments.AddProductNutritionFactsFragment.addNutrientRow(AddProductNutritionFactsFragment.java:1321)
        at openfoodfacts.github.scrachx.openfood.fragments.AddProductNutritionFactsFragment.preFillProductValues(AddProductNutritionFactsFragment.java:468)
        at openfoodfacts.github.scrachx.openfood.fragments.AddProductNutritionFactsFragment.onViewCreated(AddProductNutritionFactsFragment.java:310)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1439)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.measure(View.java:22190)
        at android.support.constraint.ConstraintLayout.internalMeasureChildren(ConstraintLayout.java:1227)
        at android.support.constraint.ConstraintLayout.onMeasure(ConstraintLayout.java:1572)
        at android.view.View.measure(View.java:22190)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6676)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
        at android.view.View.measure(View.java:22190)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6676)
        at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:400)
        at android.view.View.measure(View.java:22190)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6676)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:22190)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6676)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
        at android.view.View.measure(View.java:22190)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6676)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:751)
        at android.view.View.measure(View.java:22190)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2540)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1600)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1868)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1475)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7298)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:726)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
2019-01-24 20:39:18.335 9204-9204/openfoodfacts.github.scrachx.openfood E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
```

**Expected behavior:** 

The edition activity should open.

**Observed behavior:** 

The app crashes.

**Device and Android version:** 

LG K10 2017 edition.  Android Version 8.1.0

**Comment by teolemon** [comment]
Can you give the specific barcode, and the language/version you are using ?

**Comment by KarthikRIyer** [comment]
Language: English
## Product 1
Barcode: 9556995120946
## Product 2
Barcode: 0011433117272

**Comment by teolemon** [comment]
Indeed 👍  💥

**Comment by Shritesh99** [comment]
Will work in this.
