### ISSUE TITLE
Crash on clicking scan in the additives explorer

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2176]
```
2019-01-30 10:40:15.778 6108-6108/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 6108
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at openfoodfacts.github.scrachx.openfood.views.AdditivesExplorer$1.onQueryTextChange(AdditivesExplorer.java:119)
        at android.support.v7.widget.SearchView.onTextChanged(SearchView.java:1180)
        at android.support.v7.widget.SearchView$10.onTextChanged(SearchView.java:1714)
        at android.widget.TextView.sendOnTextChanged(TextView.java:9754)
        at android.widget.TextView.setText(TextView.java:5733)
        at android.widget.TextView.setText(TextView.java:5571)
        at android.widget.EditText.setText(EditText.java:122)
        at android.widget.TextView.setText(TextView.java:5528)
        at android.support.v7.widget.SearchView.onActionViewExpanded(SearchView.java:1294)
        at android.support.v7.widget.Toolbar$ExpandedActionViewMenuPresenter.expandItemActionView(Toolbar.java:2396)
        at android.support.v7.view.menu.MenuBuilder.expandItemActionView(MenuBuilder.java:1348)
        at android.support.v7.view.menu.MenuItemImpl.expandActionView(MenuItemImpl.java:810)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:978)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by PrajwalM2212** [comment]
Will look into it soon

**Comment by PrajwalM2212** [comment]
@teolemon Is this issue about the search field or scanning ?
Currently, 
![screenshot_1548939376](https://user-images.githubusercontent.com/30733262/52055550-b9d2f880-2585-11e9-9c28-86d9955bd6e8.png)
does not have scan button.

**Comment by PrajwalM2212** [comment]
I will add the scan button in additives explorer.  But what is this issue arising from ?

**Comment by teolemon** [comment]
Clicking on the search icon. Instant crash.
Also, I feel that the line size is too small compared to categories.

**Comment by PrajwalM2212** [comment]
I was going to make the UI similar to categories

**Comment by PrajwalM2212** [comment]
Also clicking on search icon does not crash for me.

**Comment by teolemon** [comment]
```
2019-01-31 14:55:20.795 15512-15512/openfoodfacts.github.scrachx.openfood E/MainActivity: Error in creating fragment
2019-01-31 14:55:20.905 15512-15512/openfoodfacts.github.scrachx.openfood E/RecyclerView: No adapter attached; skipping layout
2019-01-31 14:55:25.103 914-914/? E/NotificationService: Muting recently noisy 0|com.twitter.android|82|null|10318
2019-01-31 14:55:32.656 15512-15512/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 15512
    java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at openfoodfacts.github.scrachx.openfood.views.AdditivesExplorer$1.onQueryTextChange(AdditivesExplorer.java:119)
        at android.support.v7.widget.SearchView.onTextChanged(SearchView.java:1180)
        at android.support.v7.widget.SearchView$10.onTextChanged(SearchView.java:1714)
        at android.widget.TextView.sendOnTextChanged(TextView.java:9754)
        at android.widget.TextView.setText(TextView.java:5733)
        at android.widget.TextView.setText(TextView.java:5571)
        at android.widget.EditText.setText(EditText.java:122)
        at android.widget.TextView.setText(TextView.java:5528)
        at android.support.v7.widget.SearchView.onActionViewExpanded(SearchView.java:1294)
        at android.support.v7.widget.Toolbar$ExpandedActionViewMenuPresenter.expandItemActionView(Toolbar.java:2396)
        at android.support.v7.view.menu.MenuBuilder.expandItemActionView(MenuBuilder.java:1348)
        at android.support.v7.view.menu.MenuItemImpl.expandActionView(MenuItemImpl.java:810)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:978)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
        at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
        at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by PrajwalM2212** [comment]
1. Were you typing anything when this happened ? 
2. Did you have to click the search icon for this to happen ?
3. Did this happen on clicking a additive ?
Can you say me the steps that lead to this log ?
Seems to be a subtle issue as it is not crashing for me.

**Comment by teolemon** [comment]
1. No
2. Yes
3. No

**Comment by PrajwalM2212** [comment]
@teolemon You can check now
