### ISSUE TITLE
Crash in the product page in the OBF flavor

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2187]
```2019-02-01 18:25:50.870 8840-8840/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openbeauty, PID: 8840
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.fasterxml.jackson.databind.JsonNode.toString()' on a null object reference
        at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient$3.onResponse(OpenFoodAPIClient.java:233)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-02-01 18:25:50.928 910-1347/? E/InputDispatcher: channel '49aa0cc openfoodfacts.github.scrachx.openbeauty/openfoodfacts.github.scrachx.openfood.views.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-02-01 18:25:52.896 12467-12467/openfoodfacts.github.scrachx.openbeauty E/RecyclerView: No adapter attached; skipping layout```

**Comment by balaji-ramavathu** [comment]
@teolemon How to reproduce the crash?

**Comment by pavankuppa1** [comment]
@teolemon I can work on this issue

**Comment by deniger** [comment]
New crash ( linked to the question feature I guess):
`W/System.err: java.lang.NullPointerException: The mapper function returned a null value.
        at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:109)
W/System.err:     at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onComplete(BodyObservable.java:66)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:47)
        at io.reactivex.Observable.subscribe(Observable.java:12268)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12268)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)`

**Comment by teolemon** [comment]
@raphael0202

**Comment by deniger** [comment]
@raphael0202  please have a look to https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2514 that should fix this issue + the issue related to question

**Comment by raphael0202** [comment]
@deniger @teolemon It's not causing a crash on my device, it's only a warning that a null value was returned, which breaks the observable flow, which was the expected behaviour. There must be more elegant way to do that.

**Comment by deniger** [comment]
In the PR I use an empty question to avoid this.
The issue comes from io.reactivex.Single#map that throw a nullPointerException. Maybe it's catched somewhere else but didn't see it...
![image](https://user-images.githubusercontent.com/47569605/55408571-8ea65e80-5560-11e9-9f6f-37bd76ff6466.png)
