### ISSUE TITLE
Can't upload offline products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#222]
I have ten offline products to upload, and it makes in the app crash.

- they don't have a name, quantity or store
- some of them don't have all three images
- some of them might already be in the database

We need to ensure that:
- we can send, even without  a name, quantity or store
- we can send, even without all the images
- if already in the database, add as additional images

**Comment by teolemon** [comment]
> 11-14 08:25:32.787 26510-26510/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: openfoodfacts.github.scrachx.openfood, PID: 26510
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
                                                       at openfoodfacts.github.scrachx.openfood.fragments.OfflineEditFragment$3.onClick(OfflineEditFragment.java:135)
                                                       at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:367)
                                                       at android.view.View.performClick(View.java:5204)
                                                       at android.view.View$PerformClick.run(View.java:21153)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
