### ISSUE TITLE
It's impossible to type a comma in the Nutrition table edit mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2252]
It's impossible to type a comma in the Nutrition table edit mode.
It should be possible to do so (some language use it as a separator), while ensuring the API call is properly done (that the comma doesn't mess up the API call).

**Comment by jaindiv26** [comment]
I'll look into it.

**Comment by deniger** [comment]
While testing this I had this exception ( if I press on < in the text field):

03-15 10:54:44.803 8824-8824/openfoodfacts.github.scrachx.openfood E/MessageQueue-JNI: java.lang.NumberFormatException: For input string: "40<"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:452)
        at openfoodfacts.github.scrachx.openfood.fragments.AddProductNutritionFactsFragment.checkEnergyInBounds(AddProductNutritionFactsFragment.java:812)
        at openfoodfacts.github.scrachx.openfood.fragments.AddProductNutritionFactsFragment_ViewBinding$5.afterTextChanged(AddProductNutritionFactsFragment_ViewBinding.java:161)
