### ISSUE TITLE
Crash on clicking on Offline Mode from Settings

### ISSUE THREAD

**Issue by subhanjansaha** [openfoodfacts/openfoodfacts-androidapp#2287]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.
- [x] Before reporting, please ensure (if you can) that you have tested it with the latest (dev) version of the software.
- [x] Don't forget to tag your issue, it makes it easier to discover.
**Summary:** 

After navigating to the Settings menu, if the user tries to navigate to the 'Offline Mode', the app crashes. 

**Steps to reproduce:** 

Go to Settings, and then try clicking on the 'Offline Mode' option in the drawer. (Note: you might have to add a product to the offline mode before trying this)

**Add system logs:**

`java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
     ViewHolder 1:ViewHolder{1645b04 position=18 id=9, oldPos=-1, pLpos:-1 not recyclable(1)} 
     View Holder 2:ViewHolder{429638d position=16 id=9, oldPos=-1, pLpos:-1} android.support.v7.widget.RecyclerView{54dde9 VFED.VC.. ......ID 0,0-608,1280 #7f09015d app:id/material_drawer_recycler_view}, adapter:com.mikepenz.fastadapter.FastAdapter@af5aa6e, layout:android.support.v7.widget.LinearLayoutManager@39b450f, context:openfoodfacts.github.scrachx.openfood.views.MainActivity@889b5bf
        at android.support.v7.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:3946)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3870)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3540)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:18879)
        at android.view.ViewGroup.layout(ViewGroup.java:5953)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
        at android.view.View.layout(View.java:18879)
        at android.view.ViewGroup.layout(ViewGroup.java:5953)
        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1195)
        at android.view.View.layout(View.java:18879)
        at android.view.ViewGroup.layout(ViewGroup.java:5953)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:18879)
        at android.view.ViewGroup.layout(ViewGroup.java:5953)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:18879)
        at android.view.ViewGroup.layout(ViewGroup.java:5953)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:18879)
        at android.view.ViewGroup.layout(ViewGroup.java:5953)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
        at android.view.View.layout(View.java:18879)
        at android.view.ViewGroup.layout(ViewGroup.java:5953)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:937)
        at android.view.View.layout(View.java:18879)
        at android.view.ViewGroup.layout(ViewGroup.java:5953)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2684)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2400)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1537)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
        at android.view.Choreographer.doCallbacks(Choreographer.java:734)
        at android.view.Choreographer.doFrame(Choreographer.java:670)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)`

**Expected behavior:** 

Not crash

**Observed behavior:** 

App crashed

**Device and Android version:** 

Samsung Galaxy J7 Nxt with Android 7.0 (Nougat)
**Screenshots:** 
See attached,
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/42271776/53240000-7ae71d00-36c3-11e9-8cf7-9523fd082396.gif)

**Comment by subhanjansaha** [comment]
I want to work on this.

**Comment by teolemon** [comment]
Ok. related as you saw is the one I opened yesterday:
https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/2264

**Comment by subhanjansaha** [comment]
Right. I'll open a PR that would close both issues.
