### ISSUE TITLE
Crash when clicking on additive from scan view

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2326]
1. https://barcode.tec-it.com/en/EAN13?data=5997523313111
2. Slide up
3. Click on E621 additive
4. BOOM

``` 
2019-02-28 13:36:27.098 4920-4920/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 4920
    java.lang.ClassCastException: openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity cannot be cast to openfoodfacts.github.scrachx.openfood.views.product.ProductActivity
        at openfoodfacts.github.scrachx.openfood.views.product.summary.SummaryProductFragment$2.lambda$onClick$0(SummaryProductFragment.java:670)
        at openfoodfacts.github.scrachx.openfood.views.product.summary.-$$Lambda$SummaryProductFragment$2$mgOUIfl5F6zUdGBaRjXhmpv94Hc.onresponse(Unknown Source:4)
        at openfoodfacts.github.scrachx.openfood.network.WikidataApiClient$1.onResponse(WikidataApiClient.java:56)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by teolemon** [comment]
If you see how to solve it @raphael0202 
It works in the ingredient tab, but not in the summary tab.
It's not quite the same code as the classic product browsing code
