### ISSUE TITLE
FATAL EXCEPTION: AsyncTask #1                                                    Process: openfoodfacts.github.scrachx.openfood, PID: 22033                                                    java.lang.RuntimeException: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#233]
Offline Edit

11-14 09:50:36.426 22033-22077/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                   Process: openfoodfacts.github.scrachx.openfood, PID: 22033
                                                   java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                       at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:610)
                                                       at openfoodfacts.github.scrachx.openfood.fragments.OfflineEditFragment$FillAdapter.doInBackground(OfflineEditFragment.java:193)
                                                       at openfoodfacts.github.scrachx.openfood.fragments.OfflineEditFragment$FillAdapter.doInBackground(OfflineEditFragment.java:169)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by herau** [comment]
occurred when offline product doesn't have a default image; which is not possible since d0650ddb3b2a772d6a4075749b37e5d7ce5e102b i guess :-)
