### ISSUE TITLE
FATAL EXCEPTION: main                                                    Process: openfoodfacts.github.scrachx.openfood, PID: 25912                                                    java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#234]
**Steps to reproduce** : Offline mode, when adding a product with just a picture

11-14 09:59:33.311 851-5656/? I/ActivityManager: START u0 {cmp=openfoodfacts.github.scrachx.openfood/.views.MainActivity (has extras)} from uid 10402 on display 0
11-14 09:59:33.797 851-870/? I/ActivityManager: Displayed openfoodfacts.github.scrachx.openfood/.views.MainActivity: +459ms
11-14 09:59:36.268 25912-25912/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: openfoodfacts.github.scrachx.openfood, PID: 25912
                                                   java.lang.IndexOutOfBoundsException: Invalid index 9, size is 9
                                                       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                       at java.util.ArrayList.get(ArrayList.java:308)
                                                       at openfoodfacts.github.scrachx.openfood.views.adapters.SaveListAdapter.getView(SaveListAdapter.java:53)
                                                       at android.widget.AbsListView.obtainView(AbsListView.java:2346)
                                                       at android.widget.ListView.makeAndAddView(ListView.java:1876)
                                                       at android.widget.ListView.fillDown(ListView.java:702)
                                                       at android.widget.ListView.fillGap(ListView.java:666)
                                                       at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5053)
                                                       at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4601)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:603)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-14 09:59:36.282 851-2553/? W/ActivityManager:   Force finishing activity openfoodfacts.github.scrachx.openfood/.views.MainActivity
11-14 09:59:36.784 851-865/? W/ActivityManager: Activity pause timeout for ActivityRecord{368df4b u0 openfoodfacts.github.scrachx.openfood/.views.MainActivity t17962 f}

**Comment by herau** [comment]
@teolemon currently not reproductible on the master branch

**Comment by teolemon** [comment]
Looks fixed in trunk (can't reproduce with translation branch). Ok for closing
