### ISSUE TITLE
FATAL EXCEPTION: main                                                    Process: openfoodfacts.github.scrachx.openfood, PID: 32670                                                    java.lang.IllegalStateException

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#235]
**Steps to reproduce**: Offline mode, long-pressing on a product

11-14 10:02:00.887 851-870/? I/ActivityManager: Displayed openfoodfacts.github.scrachx.openfood/.views.SaveProductOfflineActivity: +164ms
11-14 10:02:08.542 32670-32670/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: openfoodfacts.github.scrachx.openfood, PID: 32670
                                                   java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131624187, class android.widget.ListView) with Adapter(class openfoodfacts.github.scrachx.openfood.views.adapters.SaveListAdapter)]
                                                       at android.widget.ListView.layoutChildren(ListView.java:1573)
                                                       at android.widget.AbsListView$CheckForTap.run(AbsListView.java:3311)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by herau** [comment]
@teolemon unreproductible on master branch. The saved product has all fields filled ?
Currently a popup appears when i long pressing on a product

**Comment by teolemon** [comment]
happens on uncomplete products. On complete products, will display the deletion popup fine

**Comment by herau** [comment]
@teolemon on master branch, offline mode, product with only the default image. Then long pressing will show the deletion popup. 

So i still not reproducing...

**Comment by teolemon** [comment]
Can't reproduce on master. Will test it on my main device once the update is out. Making a note to reopen if so.
