### ISSUE TITLE
Complete fail on the product scanner

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2364]
https://youtu.be/MXmU786k6hs
1. Scan a product, expand and swipe left to ingredients
2. Reduce
3. Scan a 2nd product
4. Expand
5. Blank
6. Swipe to ingredients
7. Swipe back to summary
8. Previous product appears

**Comment by teolemon** [comment]
``` 
2019-03-05 16:27:25.492 7045-7098/? E/ViewRootImpl: Accessibility content change on non-UI thread. Future Android versions will throw an exception.
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.runOrPost(ViewRootImpl.java:8402)
        at android.view.ViewRootImpl.postSendWindowContentChangedCallback(ViewRootImpl.java:7487)
        at android.view.ViewRootImpl.notifySubtreeAccessibilityStateChanged(ViewRootImpl.java:7670)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.View.notifyViewAccessibilityStateChangedIfNeeded(View.java:11942)
        at android.widget.TextView.setText(TextView.java:5736)
        at android.widget.TextView.setText(TextView.java:5571)
        at android.widget.TextView.append(TextView.java:5235)
        at android.widget.TextView.append(TextView.java:5219)
        at openfoodfacts.github.scrachx.openfood.views.product.summary.SummaryProductFragment.d(Unknown Source:57)
        at openfoodfacts.github.scrachx.openfood.views.product.summary.b.a(Unknown Source:4)
        at openfoodfacts.github.scrachx.openfood.views.product.summary.b.lambda$-411q7w2_37vviw1EVjqHNUSKLY(Unknown Source:0)
        at openfoodfacts.github.scrachx.openfood.views.product.summary.-$$Lambda$b$-411q7w2_37vviw1EVjqHNUSKLY.accept(Unknown Source:4)
        at b.a.e.e.d.a$a.a(Unknown Source:2)
        at b.a.e.e.c.n$a.a(Unknown Source:12)
        at b.a.e.d.a.a(Unknown Source:26)
        at b.a.e.e.c.d$a.a(Unknown Source:12)
        at b.a.e.e.c.e.b(Unknown Source:7)
        at b.a.g.a(Unknown Source:14)
        at b.a.e.e.c.d.b(Unknown Source:11)
        at b.a.g.a(Unknown Source:14)
        at b.a.e.e.c.c.b(Unknown Source:9)
        at b.a.g.a(Unknown Source:14)
        at b.a.e.e.c.n.b(Unknown Source:21)
        at b.a.k.a(Unknown Source:14)
        at b.a.e.e.d.a.b(Unknown Source:9)
        at b.a.k.a(Unknown Source:14)
        at b.a.e.e.d.h$a.run(Unknown Source:2)
        at b.a.j$a.run(Unknown Source:9)
        at b.a.e.g.h.run(Unknown Source:13)
        at b.a.e.g.h.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2019-03-05 16:27:25.495 7045-7101/? E/ViewRootImpl: Accessibility content change on non-UI thread. Future Android versions will throw an exception.
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.runOrPost(ViewRootImpl.java:8402)
        at android.view.ViewRootImpl.postSendWindowContentChangedCallback(ViewRootImpl.java:7487)
        at android.view.ViewRootImpl.notifySubtreeAccessibilityStateChanged(ViewRootImpl.java:7670)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.ViewGroup.notifySubtreeAccessibilityStateChanged(ViewGroup.java:3669)
        at android.view.View.notifyViewAccessibilityStateChangedIfNeeded(View.java:11942)
        at android.widget.TextView.setText(TextView.java:5736)
        at android.widget.TextView.setText(TextView.java:5571)
        at android.widget.TextView.append(TextView.java:5235)
        at android.widget.TextView.append(TextView.java:5219)
        at openfoodfacts.github.scrachx.openfood.views.product.summary.SummaryProductFragment.b(Unknown Source:57)
        at openfoodfacts.github.scrachx.openfood.views.product.summary.b.c(Unknown Source:4)
        at openfoodfacts.github.scrachx.openfood.views.product.summary.b.lambda$tko-AVCsZo7k8xI3bLimOpKhLr8(Unknown Source:0)
        at openfoodfacts.github.scrachx.openfood.views.product.summary.-$$Lambda$b$tko-AVCsZo7k8xI3bLimOpKhLr8.accept(Unknown Source:4)
        at b.a.e.e.d.a$a.a(Unknown Source:2)
        at b.a.e.e.c.n$a.a(Unknown Source:12)
        at b.a.e.e.c.d$a.a(Unknown Source:12)
        at b.a.e.e.c.e.b(Unknown Source:7)
        at b.a.g.a(Unknown Source:14)
        at b.a.e.e.c.d.b(Unknown Source:11)
        at b.a.g.a(Unknown Source:14)
        at b.a.e.e.c.n.b(Unknown Source:21)
        at b.a.k.a(Unknown Source:14)
        at b.a.e.e.d.a.b(Unknown Source:9)
        at b.a.k.a(Unknown Source:14)
        at b.a.e.e.d.h$a.run(Unknown Source:2)
        at b.a.j$a.run(Unknown Source:9)
        at b.a.e.g.h.run(Unknown Source:13)
        at b.a.e.g.h.call(Unknown Source:0)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by teolemon** [comment]
Fixed by @philippeauriach
