### ISSUE TITLE
Crash on Comparing Evian and other products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2369]
1. Scan barcode
2. Scan https://barcode.tec-it.com/en/EAN13?data=5997523313111 
3. Slide up and click compare
4. Scan https://barcode.tec-it.com/en/EAN13?data=3068320110783
5. BOOM

**Comment by teolemon** [comment]
``` 
2019-03-07 16:47:40.991 21326-21326/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.openfoodfacts.scanner, PID: 21326
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.openfoodfacts.scanner/openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'openfoodfacts.github.scrachx.openfood.models.Product openfoodfacts.github.scrachx.openfood.models.State.getProduct()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'openfoodfacts.github.scrachx.openfood.models.Product openfoodfacts.github.scrachx.openfood.models.State.getProduct()' on a null object reference
        at openfoodfacts.github.scrachx.openfood.views.product.ingredients.IngredientsProductFragment.a(Unknown Source:79)
        at android.support.v4.app.p.a(Unknown Source:342)
        at android.support.v4.app.p.e(Unknown Source:38)
        at android.support.v4.app.p.a(Unknown Source:46)
        at android.support.v4.app.p.f(Unknown Source:4)
        at android.support.v4.app.p.n(Unknown Source:6)
        at android.support.v4.app.m.e(Unknown Source:4)
        at android.support.v4.app.k.onCreate(Unknown Source:122)
        at android.support.v7.app.e.onCreate(Unknown Source:42)
        at openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity.onCreate(Unknown Source:7)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by teolemon** [comment]
``` 
2019-03-07 20:54:14.535 8584-8584/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 8584
    java.lang.RuntimeException: Unable to start activity ComponentInfo{openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'openfoodfacts.github.scrachx.openfood.models.Product openfoodfacts.github.scrachx.openfood.models.State.getProduct()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'openfoodfacts.github.scrachx.openfood.models.Product openfoodfacts.github.scrachx.openfood.models.State.getProduct()' on a null object reference
        at openfoodfacts.github.scrachx.openfood.views.product.ingredients.IngredientsProductFragment.onAttach(IngredientsProductFragment.java:186)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1372)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:3194)
        at android.support.v4.app.FragmentController.dispatchCreate(FragmentController.java:184)
        at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:355)
        at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:84)
        at openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity.onCreate(ContinuousScanActivity.java:561)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by teolemon** [comment]
Fixed by @philippeauriach
