### ISSUE TITLE
Crash on autocorrect ?

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#238]
Was voice typing 2,4
Chose autocorrect 2,    4 (the spaces might be part of the issue ?)

Crashed:

```
11-14 17:37:12.931 2565-2565/? I/LatinIme: onActivate() : EditorInfo = Package = openfoodfacts.github.scrachx.openfood : Type = Text : Learning = Disable : Suggestion = Show : AutoCorrection = Disable : Microphone = Show
```
```

11-14 17:37:36.568 13932-13932/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: openfoodfacts.github.scrachx.openfood, PID: 13932
                                                   java.lang.IndexOutOfBoundsException: setSpan (0 ... 4) ends beyond length 2
                                                       at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1090)
                                                       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:665)
                                                       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:658)
                                                       at android.widget.TextView.setSpan_internal(TextView.java:9683)
                                                       at android.widget.Editor$SuggestionsPopupWindow.onItemClick(Editor.java:3086)
                                                       at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                       at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
                                                       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066)
                                                       at android.widget.AbsListView$3.run(AbsListView.java:3903)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-14 17:37:36.570 851-2590/? W/ActivityManager:   Force finishing activity openfoodfacts.github.scrachx.openfood/.views.SaveProductOfflineActivity
```

**Comment by teolemon** [comment]
Not master.

**Comment by teolemon** [comment]
It was on an uncomplete product in offline mode, with network on. Didn't press send.

**Comment by jaindiv26** [comment]
I cannot reproduce this bug, please elaborate on this issue.
