### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.os.Bundle.getSerializable(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by raphael0202** [openfoodfacts/openfoodfacts-androidapp#2440]
**Checklist**
- [x] Bug Report - The issue you are reporting might be there already. Please search on the [issues tracker](https://github.com/openfoodfacts/openfoodfacts-androidapp/issues) before creating or reporting an issue.

**Summary:** 
This stacktrace appears in the log when viewing the nutrition tab of the product 3401542119460.

```
2019-03-18 14:20:26.020 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.os.Bundle.getSerializable(java.lang.String)' on a null object reference
2019-03-18 14:20:26.021 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at openfoodfacts.github.scrachx.openfood.views.product.nutrition.NutritionProductFragment.refreshView(NutritionProductFragment.java:372)
2019-03-18 14:20:26.021 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at openfoodfacts.github.scrachx.openfood.views.product.nutrition.NutritionProductFragment.onViewCreated(NutritionProductFragment.java:170)
2019-03-18 14:20:26.021 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1439)
2019-03-18 14:20:26.021 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
2019-03-18 14:20:26.021 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
2019-03-18 14:20:26.022 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
2019-03-18 14:20:26.022 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
2019-03-18 14:20:26.022 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
2019-03-18 14:20:26.022 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
2019-03-18 14:20:26.022 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
2019-03-18 14:20:26.022 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
2019-03-18 14:20:26.022 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
2019-03-18 14:20:26.022 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
2019-03-18 14:20:26.023 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
2019-03-18 14:20:26.023 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v4.view.ViewPager$3.run(ViewPager.java:267)
2019-03-18 14:20:26.023 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v4.view.ViewPager.completeScroll(ViewPager.java:1999)
2019-03-18 14:20:26.024 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2129)
2019-03-18 14:20:26.024 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2511)
2019-03-18 14:20:26.024 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
2019-03-18 14:20:26.024 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
2019-03-18 14:20:26.024 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
2019-03-18 14:20:26.024 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
2019-03-18 14:20:26.024 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
2019-03-18 14:20:26.024 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
2019-03-18 14:20:26.025 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
2019-03-18 14:20:26.025 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
2019-03-18 14:20:26.025 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
2019-03-18 14:20:26.025 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
2019-03-18 14:20:26.025 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2968)
2019-03-18 14:20:26.025 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2600)
2019-03-18 14:20:26.025 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:448)
2019-03-18 14:20:26.026 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1829)
2019-03-18 14:20:26.026 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.app.Activity.dispatchTouchEvent(Activity.java:3307)
2019-03-18 14:20:26.026 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
2019-03-18 14:20:26.026 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
2019-03-18 14:20:26.026 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:410)
2019-03-18 14:20:26.026 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.View.dispatchPointerEvent(View.java:12015)
2019-03-18 14:20:26.026 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4795)
2019-03-18 14:20:26.026 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4609)
2019-03-18 14:20:26.026 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
2019-03-18 14:20:26.027 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
2019-03-18 14:20:26.027 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
2019-03-18 14:20:26.027 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4293)
2019-03-18 14:20:26.027 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
2019-03-18 14:20:26.027 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4350)
2019-03-18 14:20:26.027 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
2019-03-18 14:20:26.027 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4200)
2019-03-18 14:20:26.028 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4166)
2019-03-18 14:20:26.028 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4174)
2019-03-18 14:20:26.028 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4147)
2019-03-18 14:20:26.028 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6661)
2019-03-18 14:20:26.028 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6635)
2019-03-18 14:20:26.028 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6596)
2019-03-18 14:20:26.028 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6764)
2019-03-18 14:20:26.028 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
2019-03-18 14:20:26.028 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.os.MessageQueue.nativePollOnce(Native Method)
2019-03-18 14:20:26.029 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.os.MessageQueue.next(MessageQueue.java:325)
2019-03-18 14:20:26.029 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.os.Looper.loop(Looper.java:142)
2019-03-18 14:20:26.029 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
2019-03-18 14:20:26.029 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-03-18 14:20:26.029 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
2019-03-18 14:20:26.029 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2019-03-18 14:20:28.451 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.Serializable android.os.Bundle.getSerializable(java.lang.String)' on a null object reference
2019-03-18 14:20:28.451 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at openfoodfacts.github.scrachx.openfood.views.product.nutrition.NutritionProductFragment.refreshView(NutritionProductFragment.java:372)
2019-03-18 14:20:28.451 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at openfoodfacts.github.scrachx.openfood.views.adapters.ProductFragmentPagerAdapter.refresh(ProductFragmentPagerAdapter.java:47)
2019-03-18 14:20:28.451 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at openfoodfacts.github.scrachx.openfood.views.product.ProductActivity.onNewIntent(ProductActivity.java:534)
2019-03-18 14:20:28.451 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.app.Activity.performNewIntent(Activity.java:7021)
2019-03-18 14:20:28.451 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1309)
2019-03-18 14:20:28.452 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1321)
2019-03-18 14:20:28.452 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2932)
2019-03-18 14:20:28.452 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.app.ActivityThread.performNewIntents(ActivityThread.java:2948)
2019-03-18 14:20:28.452 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2964)
2019-03-18 14:20:28.452 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.app.ActivityThread.-wrap14(Unknown Source:0)
2019-03-18 14:20:28.452 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
2019-03-18 14:20:28.452 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2019-03-18 14:20:28.452 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.os.Looper.loop(Looper.java:164)
2019-03-18 14:20:28.453 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
2019-03-18 14:20:28.453 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-03-18 14:20:28.453 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
2019-03-18 14:20:28.453 17847-17847/openfoodfacts.github.scrachx.openfood W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by deniger** [comment]
Should be fixed with the PR https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/2437

**Comment by deniger** [comment]
See PR #2437
