### ISSUE TITLE
android.content.res.Resources$NotFoundException: Drawable org.openfoodfacts.scanner:drawable/ic_file_download_black_18dp

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2542]
2019-04-09 10:22:46.833 23258-23258/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.openfoodfacts.scanner, PID: 23258
    android.view.InflateException: Binary XML file line #123: Binary XML file line #123: Error inflating class Button
    Caused by: android.view.InflateException: Binary XML file line #123: Error inflating class Button
    Caused by: android.content.res.Resources$NotFoundException: Drawable org.openfoodfacts.scanner:drawable/ic_file_download_black_18dp with resource ID #0x7f08009d
    Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_file_download_black_18dp.xml from drawable resource ID #0x7f08009d
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:876)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:659)
        at android.content.res.Resources.loadDrawable(Resources.java:916)
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1006)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:981)
        at android.widget.TextView.<init>(TextView.java:1119)
        at android.widget.Button.<init>(Button.java:166)
        at android.widget.Button.<init>(Button.java:141)
        at android.support.v7.widget.AppCompatButton.<init>(Unknown Source:4)
        at android.support.v7.widget.AppCompatButton.<init>(Unknown Source:2)
        at android.support.v7.app.AppCompatViewInflater.c(Unknown Source:2)
        at android.support.v7.app.AppCompatViewInflater.a(Unknown Source:229)
        at android.support.v7.app.l.b(Unknown Source:140)
        at android.support.v7.app.l.onCreateView(Unknown Source:7)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:238)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1057)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1080)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1122)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1080)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:693)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
        at openfoodfacts.github.scrachx.openfood.fragments.AddProductIngredientsFragment.a(Unknown Source:4)
        at android.support.v4.app.j.b(Unknown Source:10)
        at android.support.v4.app.p.a(Unknown Source:587)
        at android.support.v4.app.p.e(Unknown Source:38)
        at android.support.v4.app.p.a(Unknown Source:46)
        at android.support.v4.app.d.g(Unknown Source:167)
        at android.support.v4.app.p.b(Unknown Source:38)
        at android.support.v4.app.p.a(Unknown Source:114)
        at android.support.v4.app.p.b(Unknown Source:88)
        at android.support.v4.app.p.b(Unknown Source:31)
        at android.support.v4.app.d.f(Unknown Source:6)
        at android.support.v4.app.s.b(Unknown Source:4)
        at android.support.v4.view.ViewPager.a(Unknown Source:389)
        at android.support.v4.view.ViewPager.c(Unknown Source:2)
        at android.support.v4.view.ViewPager.onMeasure(Unknown Source:213)
        at android.view.View.measure(View.java:24793)
        at android.support.constraint.ConstraintLayout.a(Unknown Source:185)
        at android.support.constraint.ConstraintLayout.onMeasure(Unknown Source:132)
        at android.view.View.measure(View.java:24793)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6878)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(Unknown Source:172)
        at android.view.View.measure(View.java:24793)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6878)
        at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(Unknown Source:200)
        at android.view.View.measure(View.java:24793)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6878)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
        at android.view.View.measure(View.java:24793)

**Comment by teolemon** [comment]
@mustaqmustu can you have a look ? It seems related to your change

**Comment by mustaqmustu** [comment]
![Screenshot from 2019-04-10 18-57-28](https://user-images.githubusercontent.com/43813438/55882774-b336b200-5bc2-11e9-9543-0ba85e73edfc.png)
It says that file is missing, but i still found it in drawable folder .@teolemon ,Could you say in which activity this error comes?

**Comment by teolemon** [comment]
When trying to add or edit a product.

**Comment by mustaqmustu** [comment]
So I think its the problem with android Q @teolemon

**Comment by teolemon** [comment]
I will try to revert to ic_compare_arrows_black_18dp to see if it works better for me

**Comment by teolemon** [comment]
@mustaqmustu changing back the icon fixes it for me

**Comment by mustaqmustu** [comment]
@teolemon I dont have Android Q to test it

**Comment by teolemon** [comment]
I don't think it's Android Q related.

**Comment by mustaqmustu** [comment]
@teolemon  Is it due to the path in that file ??? I created it by vector asset method.

**Comment by deniger** [comment]
could be closed no ?

**Comment by teolemon** [comment]
It will be superseded by your fix, so yes.
