### ISSUE TITLE
java.lang.NullPointerException:    at openfoodfacts.github.scrachx.openfood.views.product.ingredients.IngredientsProductFragment.a (IngredientsProductFragment.java:40)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2559]
``` 
java.lang.NullPointerException: 
  at openfoodfacts.github.scrachx.openfood.views.product.ingredients.IngredientsProductFragment.a (IngredientsProductFragment.java:40)
  at android.support.v4.app.FragmentManagerImpl.a (FragmentManagerImpl.java:336)
  at android.support.v4.app.FragmentManagerImpl.e (FragmentManagerImpl.java:38)
  at android.support.v4.app.FragmentManagerImpl.a (FragmentManagerImpl.java:46)
  at android.support.v4.app.FragmentManagerImpl.f (FragmentManagerImpl.java:4)
  at android.support.v4.app.FragmentManagerImpl.n (FragmentManagerImpl.java:6)
  at android.support.v4.app.Fragment.j (Fragment.java:29)
  at android.support.v4.app.Fragment.b (Fragment.java:3)
  at android.support.v4.app.Fragment.l (Fragment.java:13)
  at android.support.v4.app.FragmentManagerImpl.a (FragmentManagerImpl.java:378)
  at android.support.v4.app.FragmentManagerImpl.e (FragmentManagerImpl.java:38)
  at android.support.v4.app.FragmentManagerImpl.a (FragmentManagerImpl.java:46)
  at android.support.v4.app.FragmentManagerImpl.f (FragmentManagerImpl.java:4)
  at android.support.v4.app.FragmentManagerImpl.n (FragmentManagerImpl.java:6)
  at android.support.v4.app.FragmentController.e (FragmentController.java:4)
  at android.support.v4.app.FragmentActivity.onCreate (FragmentActivity.java:122)
  at android.support.v7.app.AppCompatActivity.onCreate (AppCompatActivity.java:42)
  at openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity.onCreate (ContinuousScanActivity.java:7)
  at android.app.Activity.performCreate (Activity.java:6980)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1214)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2828)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2950)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1616)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6759)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:770)
```

**Comment by deniger** [comment]
is it easy to reproduce ?

**Comment by teolemon** [comment]
``` 
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:3125)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3268)
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1960)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7097)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)
``` 
![image](https://user-images.githubusercontent.com/1689815/57328886-f5480a80-7112-11e9-8f41-339a5e115e09.png)

**Comment by teolemon** [comment]
@deniger seems focused on Android 9 so far

**Comment by teolemon** [comment]
And it's the top bug in the release so far

**Comment by teolemon** [comment]
Seing a 2nd cluster for Android 8 and 8.1
``` 
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2853)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2928)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1609)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6709)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:769)
Caused by: java.lang.NullPointerException: 
  at openfoodfacts.github.scrachx.openfood.views.product.ingredients.IngredientsProductFragment.a (IngredientsProductFragment.java:40)
  at android.support.v4.app.FragmentManagerImpl.a (FragmentManagerImpl.java:336)
  at android.support.v4.app.FragmentManagerImpl.e (FragmentManagerImpl.java:38)
  at android.support.v4.app.FragmentManagerImpl.a (FragmentManagerImpl.java:46)
  at android.support.v4.app.FragmentManagerImpl.f (FragmentManagerImpl.java:4)
  at android.support.v4.app.FragmentManagerImpl.n (FragmentManagerImpl.java:6)
  at android.support.v4.app.Fragment.j (Fragment.java:29)
  at android.support.v4.app.Fragment.b (Fragment.java:3)
  at android.support.v4.app.Fragment.l (Fragment.java:13)
  at android.support.v4.app.FragmentManagerImpl.a (FragmentManagerImpl.java:378)
  at android.support.v4.app.FragmentManagerImpl.e (FragmentManagerImpl.java:38)
  at android.support.v4.app.FragmentManagerImpl.a (FragmentManagerImpl.java:46)
  at android.support.v4.app.FragmentManagerImpl.f (FragmentManagerImpl.java:4)
  at android.support.v4.app.FragmentManagerImpl.n (FragmentManagerImpl.java:6)
  at android.support.v4.app.FragmentController.e (FragmentController.java:4)
  at android.support.v4.app.FragmentActivity.onCreate (FragmentActivity.java:122)
  at android.support.v7.app.AppCompatActivity.onCreate (AppCompatActivity.java:42)
  at openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity.onCreate (ContinuousScanActivity.java:7)
  at android.app.Activity.performCreate (Activity.java:6980)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1214)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2806)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2928)
  at android.app.ActivityThread.-wrap11 (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1609)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:164)
  at android.app.ActivityThread.main (ActivityThread.java:6709)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:769)
```
![image](https://user-images.githubusercontent.com/1689815/57329225-a058c400-7113-11e9-9509-cdd801311dff.png)

**Comment by teolemon** [comment]
And a 3rd slightly different cluster to Android 4.4 that looks a bit similar to this closed bug:
https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/1870

**Comment by teolemon** [comment]
``` 
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2187)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2236)
  at android.app.ActivityThread.access$800 (ActivityThread.java:138)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1199)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:136)
  at android.app.ActivityThread.main (ActivityThread.java:5095)
  at java.lang.reflect.Method.invokeNative (Method.java)
  at java.lang.reflect.Method.invoke (Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:786)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:602)
  at dalvik.system.NativeStart.main (NativeStart.java)
Caused by: java.lang.NullPointerException: 
  at openfoodfacts.github.scrachx.openfood.views.product.ingredients.IngredientsProductFragment.access$000 (IngredientsProductFragment.java)
  or                     .buildStringBuilder (IngredientsProductFragment.java)
  or                     .getAdditiveTag (IngredientsProductFragment.java)
  or                     .getAllergensTag (IngredientsProductFragment.java)
  or                     .getTracesName (IngredientsProductFragment.java)
  or                     .lambda$onRequestPermissionsResult$5 (IngredientsProductFragment.java)
  or                     .onActivityResult (IngredientsProductFragment.java)
  or                     .onAttach (IngredientsProductFragment.java)
  or                     .onCreateView (IngredientsProductFragment.java)
  or                     .onPhotoReturned (IngredientsProductFragment.java)
  or                     .onRequestPermissionsResult (IngredientsProductFragment.java)
  or                     .onViewCreated (IngredientsProductFragment.java)
  or                     .refreshView (IngredientsProductFragment.java)
  or                     .setSpanBoldBetweenTokens (IngredientsProductFragment.java)
  or                     .showAdditives (IngredientsProductFragment.java)
  at android.support.v4.app.FragmentManagerImpl.access$500 (FragmentManagerImpl.java)
  or                     .access$600 (FragmentManagerImpl.java)
  or                     .addFragment (FragmentManagerImpl.java)
  or                     .addOnBackStackChangedListener (FragmentManagerImpl.java)
  or                     .allocBackStackIndex (FragmentManagerImpl.java)
  or                     .animateRemoveFragment (FragmentManagerImpl.java)
  or                     .attachController (FragmentManagerImpl.java)
  or                     .beginTransaction (FragmentManagerImpl.java)
  or                     .completeExecute (FragmentManagerImpl.java)
  or                     .dispatchConfigurationChanged (FragmentManagerImpl.java)
  or                     .dispatchCreateOptionsMenu (FragmentManagerImpl.java)
  or                     .dispatchMultiWindowModeChanged (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentPreAttached (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentPreCreated (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentViewCreated (FragmentManagerImpl.java)
  or                     .dispatchOptionsItemSelected (FragmentManagerImpl.java)
  or                     .dispatchPrepareOptionsMenu (FragmentManagerImpl.java)
  or                     .dump (FragmentManagerImpl.java)
  or                     .enqueueAction (FragmentManagerImpl.java)
  or                     .executeOpsTogether (FragmentManagerImpl.java)
  or                     .executePostponedTransaction (FragmentManagerImpl.java)
  or                     .findFragmentById (FragmentManagerImpl.java)
  or                     .findFragmentByTag (FragmentManagerImpl.java)
  or                     .getAnimationListener (FragmentManagerImpl.java)
  or                     .getFragment (FragmentManagerImpl.java)
  or                     .loadAnimation (FragmentManagerImpl.java)
  or                     .makeFadeAnimation (FragmentManagerImpl.java)
  or                     .makeOpenCloseAnimation (FragmentManagerImpl.java)
  or                     .makeRemovedFragmentsInvisible (FragmentManagerImpl.java)
  or                     .modifiesAlpha (FragmentManagerImpl.java)
  or                     .moveToState (FragmentManagerImpl.java)
  or                     .performPendingDeferredStart (FragmentManagerImpl.java)
  or                     .popBackStack (FragmentManagerImpl.java)
  or                     .popBackStackImmediate (FragmentManagerImpl.java)
  or                     .popBackStackState (FragmentManagerImpl.java)
  or                     .postponePostponableTransactions (FragmentManagerImpl.java)
  or                     .putFragment (FragmentManagerImpl.java)
  or                     .restoreAllState (FragmentManagerImpl.java)
  or                     .setBackStackIndex (FragmentManagerImpl.java)
  or                     .setRetaining (FragmentManagerImpl.java)
  or                     .shouldRunOnHWLayer (FragmentManagerImpl.java)
  or                     .throwException (FragmentManagerImpl.java)
  at android.support.v4.app.FragmentManagerImpl.dispatchOnFragmentStopped (FragmentManagerImpl.java)
  or                     .isStateSaved (FragmentManagerImpl.java)
  or                     .moveFragmentToExpectedState (FragmentManagerImpl.java)
  or                     .reverseTransit (FragmentManagerImpl.java)
  at android.support.v4.app.FragmentManagerImpl.access$500 (FragmentManagerImpl.java)
  or                     .access$600 (FragmentManagerImpl.java)
  or                     .addFragment (FragmentManagerImpl.java)
  or                     .addOnBackStackChangedListener (FragmentManagerImpl.java)
  or                     .allocBackStackIndex (FragmentManagerImpl.java)
  or                     .animateRemoveFragment (FragmentManagerImpl.java)
  or                     .attachController (FragmentManagerImpl.java)
  or                     .beginTransaction (FragmentManagerImpl.java)
  or                     .completeExecute (FragmentManagerImpl.java)
  or                     .dispatchConfigurationChanged (FragmentManagerImpl.java)
  or                     .dispatchCreateOptionsMenu (FragmentManagerImpl.java)
  or                     .dispatchMultiWindowModeChanged (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentPreAttached (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentPreCreated (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentViewCreated (FragmentManagerImpl.java)
  or                     .dispatchOptionsItemSelected (FragmentManagerImpl.java)
  or                     .dispatchPrepareOptionsMenu (FragmentManagerImpl.java)
  or                     .dump (FragmentManagerImpl.java)
  or                     .enqueueAction (FragmentManagerImpl.java)
  or                     .executeOpsTogether (FragmentManagerImpl.java)
  or                     .executePostponedTransaction (FragmentManagerImpl.java)
  or                     .findFragmentById (FragmentManagerImpl.java)
  or                     .findFragmentByTag (FragmentManagerImpl.java)
  or                     .getAnimationListener (FragmentManagerImpl.java)
  or                     .getFragment (FragmentManagerImpl.java)
  or                     .loadAnimation (FragmentManagerImpl.java)
  or                     .makeFadeAnimation (FragmentManagerImpl.java)
  or                     .makeOpenCloseAnimation (FragmentManagerImpl.java)
  or                     .makeRemovedFragmentsInvisible (FragmentManagerImpl.java)
  or                     .modifiesAlpha (FragmentManagerImpl.java)
  or                     .moveToState (FragmentManagerImpl.java)
  or                     .performPendingDeferredStart (FragmentManagerImpl.java)
  or                     .popBackStack (FragmentManagerImpl.java)
  or                     .popBackStackImmediate (FragmentManagerImpl.java)
  or                     .popBackStackState (FragmentManagerImpl.java)
  or                     .postponePostponableTransactions (FragmentManagerImpl.java)
  or                     .putFragment (FragmentManagerImpl.java)
  or                     .restoreAllState (FragmentManagerImpl.java)
  or                     .setBackStackIndex (FragmentManagerImpl.java)
  or                     .setRetaining (FragmentManagerImpl.java)
  or                     .shouldRunOnHWLayer (FragmentManagerImpl.java)
  or                     .throwException (FragmentManagerImpl.java)
  at android.support.v4.app.FragmentManagerImpl.dispatchOnFragmentViewDestroyed (FragmentManagerImpl.java)
  or                     .dispatchStateChange (FragmentManagerImpl.java)
  or                     .makeActive (FragmentManagerImpl.java)
  or                     .startPendingDeferredFragments (FragmentManagerImpl.java)
  at android.support.v4.app.FragmentManagerImpl.dispatchCreate (FragmentManagerImpl.java)
  or                     .saveFragmentBasicState (FragmentManagerImpl.java)
  at android.support.v4.app.Fragment.getTargetFragment (Fragment.java)
  or                     .restoreChildFragmentState (Fragment.java)
  or                     .setHideReplaced (Fragment.java)
  at android.support.v4.app.Fragment.access$800 (Fragment.java)
  or                     .onContextItemSelected (Fragment.java)
  or                     .onCreate (Fragment.java)
  or                     .onCreateAnimator (Fragment.java)
  or                     .onHiddenChanged (Fragment.java)
  or                     .onOptionsMenuClosed (Fragment.java)
  or                     .performCreateOptionsMenu (Fragment.java)
  or                     .performCreateView (Fragment.java)
  or                     .setNextAnim (Fragment.java)
  at android.support.v4.app.Fragment.performCreate (Fragment.java)
  or                     .requireContext (Fragment.java)
  at android.support.v4.app.FragmentManagerImpl.access$500 (FragmentManagerImpl.java)
  or                     .access$600 (FragmentManagerImpl.java)
  or                     .addFragment (FragmentManagerImpl.java)
  or                     .addOnBackStackChangedListener (FragmentManagerImpl.java)
  or                     .allocBackStackIndex (FragmentManagerImpl.java)
  or                     .animateRemoveFragment (FragmentManagerImpl.java)
  or                     .attachController (FragmentManagerImpl.java)
  or                     .beginTransaction (FragmentManagerImpl.java)
  or                     .completeExecute (FragmentManagerImpl.java)
  or                     .dispatchConfigurationChanged (FragmentManagerImpl.java)
  or                     .dispatchCreateOptionsMenu (FragmentManagerImpl.java)
  or                     .dispatchMultiWindowModeChanged (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentPreAttached (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentPreCreated (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentViewCreated (FragmentManagerImpl.java)
  or                     .dispatchOptionsItemSelected (FragmentManagerImpl.java)
  or                     .dispatchPrepareOptionsMenu (FragmentManagerImpl.java)
  or                     .dump (FragmentManagerImpl.java)
  or                     .enqueueAction (FragmentManagerImpl.java)
  or                     .executeOpsTogether (FragmentManagerImpl.java)
  or                     .executePostponedTransaction (FragmentManagerImpl.java)
  or                     .findFragmentById (FragmentManagerImpl.java)
  or                     .findFragmentByTag (FragmentManagerImpl.java)
  or                     .getAnimationListener (FragmentManagerImpl.java)
  or                     .getFragment (FragmentManagerImpl.java)
  or                     .loadAnimation (FragmentManagerImpl.java)
  or                     .makeFadeAnimation (FragmentManagerImpl.java)
  or                     .makeOpenCloseAnimation (FragmentManagerImpl.java)
  or                     .makeRemovedFragmentsInvisible (FragmentManagerImpl.java)
  or                     .modifiesAlpha (FragmentManagerImpl.java)
  or                     .moveToState (FragmentManagerImpl.java)
  or                     .performPendingDeferredStart (FragmentManagerImpl.java)
  or                     .popBackStack (FragmentManagerImpl.java)
  or                     .popBackStackImmediate (FragmentManagerImpl.java)
  or                     .popBackStackState (FragmentManagerImpl.java)
  or                     .postponePostponableTransactions (FragmentManagerImpl.java)
  or                     .putFragment (FragmentManagerImpl.java)
  or                     .restoreAllState (FragmentManagerImpl.java)
  or                     .setBackStackIndex (FragmentManagerImpl.java)
  or                     .setRetaining (FragmentManagerImpl.java)
  or                     .shouldRunOnHWLayer (FragmentManagerImpl.java)
  or                     .throwException (FragmentManagerImpl.java)
  at android.support.v4.app.FragmentManagerImpl.dispatchOnFragmentStopped (FragmentManagerImpl.java)
  or                     .isStateSaved (FragmentManagerImpl.java)
  or                     .moveFragmentToExpectedState (FragmentManagerImpl.java)
  or                     .reverseTransit (FragmentManagerImpl.java)
  at android.support.v4.app.FragmentManagerImpl.access$500 (FragmentManagerImpl.java)
  or                     .access$600 (FragmentManagerImpl.java)
  or                     .addFragment (FragmentManagerImpl.java)
  or                     .addOnBackStackChangedListener (FragmentManagerImpl.java)
  or                     .allocBackStackIndex (FragmentManagerImpl.java)
  or                     .animateRemoveFragment (FragmentManagerImpl.java)
  or                     .attachController (FragmentManagerImpl.java)
  or                     .beginTransaction (FragmentManagerImpl.java)
  or                     .completeExecute (FragmentManagerImpl.java)
  or                     .dispatchConfigurationChanged (FragmentManagerImpl.java)
  or                     .dispatchCreateOptionsMenu (FragmentManagerImpl.java)
  or                     .dispatchMultiWindowModeChanged (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentPreAttached (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentPreCreated (FragmentManagerImpl.java)
  or                     .dispatchOnFragmentViewCreated (FragmentManagerImpl.java)
  or                     .dispatchOptionsItemSelected (FragmentManagerImpl.java)
  or                     .dispatchPrepareOptionsMenu (FragmentManagerImpl.java)
  or                     .dump (FragmentManagerImpl.java)
  or                     .enqueueAction (FragmentManagerImpl.java)
  or                     .executeOpsTogether (FragmentManagerImpl.java)
  or                     .executePostponedTransaction (FragmentManagerImpl.java)
  or                     .findFragmentById (FragmentManagerImpl.java)
  or                     .findFragmentByTag (FragmentManagerImpl.java)
  or                     .getAnimationListener (FragmentManagerImpl.java)
  or                     .getFragment (FragmentManagerImpl.java)
  or                     .loadAnimation (FragmentManagerImpl.java)
  or                     .makeFadeAnimation (FragmentManagerImpl.java)
  or                     .makeOpenCloseAnimation (FragmentManagerImpl.java)
  or                     .makeRemovedFragmentsInvisible (FragmentManagerImpl.java)
  or                     .modifiesAlpha (FragmentManagerImpl.java)
  or                     .moveToState (FragmentManagerImpl.java)
  or                     .performPendingDeferredStart (FragmentManagerImpl.java)
  or                     .popBackStack (FragmentManagerImpl.java)
  or                     .popBackStackImmediate (FragmentManagerImpl.java)
  or                     .popBackStackState (FragmentManagerImpl.java)
  or                     .postponePostponableTransactions (FragmentManagerImpl.java)
  or                     .putFragment (FragmentManagerImpl.java)
  or                     .restoreAllState (FragmentManagerImpl.java)
  or                     .setBackStackIndex (FragmentManagerImpl.java)
  or                     .setRetaining (FragmentManagerImpl.java)
  or                     .shouldRunOnHWLayer (FragmentManagerImpl.java)
  or                     .throwException (FragmentManagerImpl.java)
  at android.support.v4.app.FragmentManagerImpl.dispatchOnFragmentViewDestroyed (FragmentManagerImpl.java)
  or                     .dispatchStateChange (FragmentManagerImpl.java)
  or                     .makeActive (FragmentManagerImpl.java)
  or                     .startPendingDeferredFragments (FragmentManagerImpl.java)
  at android.support.v4.app.FragmentManagerImpl.dispatchCreate (FragmentManagerImpl.java)
  or                     .saveFragmentBasicState (FragmentManagerImpl.java)
  at android.support.v4.app.FragmentController.dispatchCreate (FragmentController.java)
  at android.support.v4.app.FragmentActivity.onCreate (FragmentActivity.java)
  at android.support.v7.app.AppCompatActivity.onCreate (AppCompatActivity.java)
  at openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity.onCreate (ContinuousScanActivity.java)
  at android.app.Activity.performCreate (Activity.java:5231)
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1087)
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2151)
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2236)
  at android.app.ActivityThread.access$800 (ActivityThread.java:138)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1199)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:136)
  at android.app.ActivityThread.main (ActivityThread.java:5095)
  at java.lang.reflect.Method.invokeNative (Method.java)
  at java.lang.reflect.Method.invoke (Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:786)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:602)
  at dalvik.system.NativeStart.main (NativeStart.java)
```
![image](https://user-images.githubusercontent.com/1689815/57329427-05acb500-7114-11e9-82c8-18770c7bcd3f.png)

**Comment by deniger** [comment]
I hope I managed to reproduce it:

2019-05-09 13:27:08.031 12168-12168/openfoodfacts.github.scrachx.openfood E/NUTRIMENTS-MODEL: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
        at openfoodfacts.github.scrachx.openfood.models.Nutriments.getServing(Nutriments.java:226)
        at openfoodfacts.github.scrachx.openfood.models.Nutriments.get(Nutriments.java:210)
        at openfoodfacts.github.scrachx.openfood.views.product.nutrition.NutritionProductFragment.getNutrimentItems(NutritionProductFragment.java:466)
        at openfoodfacts.github.scrachx.openfood.views.product.nutrition.NutritionProductFragment.refreshView(NutritionProductFragment.java:443)
        at openfoodfacts.github.scrachx.openfood.views.product.nutrition.NutritionProductFragment.onViewCreated(NutritionProductFragment.java:141)
