### ISSUE TITLE
Can't install both OpenFoodFacts and OpenBeautyFacts

### ISSUE THREAD

**Issue by Zoah** [openfoodfacts/openfoodfacts-androidapp#2574]
**Summary:** 

I can't install both OpenFoodFacts and OpenBeautyFacts on the same device. SearchSuggestionProvider is used on both applications and Android seems to dislike that.

**Steps to reproduce:** 

- Install OpenBeautyFacts (2.9.8) from F-Droid.
- Install OpenFoodFacts (2.9.8) from F-Droid.
- Update OpenBeautyFacts to 3.1.0
- Try to update OpenFoodFacts to 3.1.0

Or easier:
- Install OpenBeautyFacts 3.1.0
- Try to install OpenFoodFacts 3.1.0

**Add system logs:**

```
04-27 12:58:19.994  1164  1248 W PackageManager: Package couldn't be installed in /data/app/openfoodfacts.github.scrachx.openfood-NXQt09iGA659Yy4-n62pvg==
04-27 12:58:19.994  1164  1248 W PackageManager: com.android.server.pm.PackageManagerException: Can't install because provider name openfoodfacts.github.scrachx.openfood.utils.SearchSuggestionProvider (in package openfoodfacts.github.scrachx.openfood) is already used by openfoodfacts.github.scrachx.openbeauty
04-27 12:58:19.994  1164  1248 W PackageManager:        at com.android.server.pm.PackageManagerService.assertPackageIsValid(PackageManagerService.java:11839)
04-27 12:58:19.994  1164  1248 W PackageManager:        at com.android.server.pm.PackageManagerService.scanPackageNewLI(PackageManagerService.java:10803)
04-27 12:58:19.994  1164  1248 W PackageManager:        at com.android.server.pm.PackageManagerService.scanPackageTracedLI(PackageManagerService.java:10605)
04-27 12:58:19.994  1164  1248 W PackageManager:        at com.android.server.pm.PackageManagerService.replaceNonSystemPackageLIF(PackageManagerService.java:17614)
04-27 12:58:19.994  1164  1248 W PackageManager:        at com.android.server.pm.PackageManagerService.replacePackageLIF(PackageManagerService.java:17561)
04-27 12:58:19.994  1164  1248 W PackageManager:        at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:18556)
04-27 12:58:19.994  1164  1248 W PackageManager:        at com.android.server.pm.PackageManagerService.installPackageTracedLI(PackageManagerService.java:18041)
04-27 12:58:19.994  1164  1248 W PackageManager:        at com.android.server.pm.PackageManagerService.access$4000(PackageManagerService.java:460)
04-27 12:58:19.994  1164  1248 W PackageManager:        at com.android.server.pm.PackageManagerService$10.run(PackageManagerService.java:15765)
04-27 12:58:19.994  1164  1248 W PackageManager:        at android.os.Handler.handleCallback(Handler.java:873)
04-27 12:58:19.994  1164  1248 W PackageManager:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-27 12:58:19.994  1164  1248 W PackageManager:        at android.os.Looper.loop(Looper.java:193)
04-27 12:58:19.994  1164  1248 W PackageManager:        at android.os.HandlerThread.run(HandlerThread.java:65)
04-27 12:58:19.994  1164  1248 W PackageManager:        at com.android.server.ServiceThread.run(ServiceThread.java:44)
```

**Expected behavior:** 

Both applications installed.

**Observed behavior:** 

An error message from Package Manager. The application isn't installed because of an "unknown error".

**Device and Android version:** 

Oneplus 6, on Android 9 (official rom OxygenOS, 9.0.5)

**Comment by SantosSi** [comment]
Same for me trying to install the new 3.1.0 from f-droid on a Galaxy S9 with Android 9 with an unknown error and on a Galaxy S6 with LineageOS 14.1 (Android 7.1.2) with "Error -13: The new package failed because it contains a content provider with the same authority as a provider already installed in the system."

**Comment by Zoah** [comment]
Hi. I also tried to install Open Pet Food Facts 3.1.0. The result was similar.

**Comment by teolemon** [comment]
@subhanjansaha

**Comment by teolemon** [comment]
Perhaps a solution like this @deniger @subhanjansaha ?
https://stackoverflow.com/questions/26527722/define-a-string-in-gradle-and-also-use-a-flavor-specific-applicationid

**Comment by deniger** [comment]
I believe that the fix should be easier as we can use a something like that:

```
public class SearchSuggestionProvider extends SearchRecentSuggestionsProvider {
  public final static String AUTHORITY = BuildConfig.APPLICATION_ID+".utils.SearchSuggestionProvider";

```

**Comment by deniger** [comment]
I had to modify AndroidManifest.xml too:
```

<provider
            android:authorities="${applicationId}.utils.SearchSuggestionProvider"
            android:name=".utils.SearchSuggestionProvider" />
```

**Comment by SantosSi** [comment]
Was F-Droid notified to trigger them to provide corrected apps?

**Comment by teolemon** [comment]
normally, I've created a release, so it should propagate really soon :-)
