### ISSUE TITLE
subjectAltNames  okhttp3.internal.connection.RealConnection.connect

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2588]
``` 
subjectAltNames: 	at b.a.e.d.g.a(Unknown Source)
	at b.a.e.e.a.b$a.a(Unknown Source)
	at b.a.e.e.d.g$a.run(Unknown Source)
	at b.a.a.b.b$b.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:7007)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by:     subjectAltNames
  at okhttp3.internal.connection.RealConnection.connect (RealConnection.java)
  or                     .connectSocket (RealConnection.java)
  or                     .connectTls (RealConnection.java)
  or                     .connectTunnel (RealConnection.java)
  or                     .createTunnel (RealConnection.java)
  or                     .establishProtocol (RealConnection.java)
  or                     .isEligible (RealConnection.java)
  or                     .isHealthy (RealConnection.java)
  or                     .newCodec (RealConnection.java)
  or                     .onSettings (RealConnection.java)
  or                     .onStream (RealConnection.java)
  or                     .route (RealConnection.java)
  or                     .supportsUrl (RealConnection.java)
  at okhttp3.internal.connection.RealConnection.connect (RealConnection.java)
  or                     .connectSocket (RealConnection.java)
  or                     .connectTls (RealConnection.java)
  or                     .connectTunnel (RealConnection.java)
  or                     .createTunnel (RealConnection.java)
  or                     .establishProtocol (RealConnection.java)
  or                     .isEligible (RealConnection.java)
  or                     .isHealthy (RealConnection.java)
  or                     .newCodec (RealConnection.java)
  or                     .onSettings (RealConnection.java)
  or                     .onStream (RealConnection.java)
  or                     .route (RealConnection.java)
  or                     .supportsUrl (RealConnection.java)
  at okhttp3.internal.connection.RealConnection.connect (RealConnection.java)
  or                     .connectSocket (RealConnection.java)
  or                     .connectTls (RealConnection.java)
  or                     .connectTunnel (RealConnection.java)
  or                     .createTunnel (RealConnection.java)
  or                     .establishProtocol (RealConnection.java)
  or                     .isEligible (RealConnection.java)
  or                     .isHealthy (RealConnection.java)
  or                     .newCodec (RealConnection.java)
  or                     .onSettings (RealConnection.java)
  or                     .onStream (RealConnection.java)
  or                     .route (RealConnection.java)
  or                     .supportsUrl (RealConnection.java)
  at okhttp3.internal.connection.StreamAllocation.acquire (StreamAllocation.java)
  or                     .codec (StreamAllocation.java)
  or                     .deallocate (StreamAllocation.java)
  or                     .findConnection (StreamAllocation.java)
  or                     .findHealthyConnection (StreamAllocation.java)
  or                     .newStream (StreamAllocation.java)
  or                     .releaseAndAcquire (StreamAllocation.java)
  or                     .streamFailed (StreamAllocation.java)
  or                     .streamFinished (StreamAllocation.java)
  at okhttp3.internal.connection.StreamAllocation.acquire (StreamAllocation.java)
  or                     .codec (StreamAllocation.java)
  or                     .deallocate (StreamAllocation.java)
  or                     .findConnection (StreamAllocation.java)
  or                     .findHealthyConnection (StreamAllocation.java)
  or                     .newStream (StreamAllocation.java)
  or                     .releaseAndAcquire (StreamAllocation.java)
  or                     .streamFailed (StreamAllocation.java)
  or                     .streamFinished (StreamAllocation.java)
  at okhttp3.internal.connection.StreamAllocation.acquire (StreamAllocation.java)
  or                     .codec (StreamAllocation.java)
  or                     .deallocate (StreamAllocation.java)
  or                     .findConnection (StreamAllocation.java)
  or                     .findHealthyConnection (StreamAllocation.java)
  or                     .newStream (StreamAllocation.java)
  or                     .releaseAndAcquire (StreamAllocation.java)
  or                     .streamFailed (StreamAllocation.java)
  or                     .streamFinished (StreamAllocation.java)
  at okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.java)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java)
  or                     .request (RealInterceptorChain.java)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java)
  or                     .request (RealInterceptorChain.java)
  at okhttp3.internal.cache.CacheInterceptor.cacheWritingResponse (CacheInterceptor.java)
  or                     .combine (CacheInterceptor.java)
  or                     .intercept (CacheInterceptor.java)
  or                     .isEndToEnd (CacheInterceptor.java)
  or                     .stripBody (CacheInterceptor.java)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java)
  or                     .request (RealInterceptorChain.java)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java)
  or                     .request (RealInterceptorChain.java)
  at okhttp3.internal.http.BridgeInterceptor.cookieHeader (BridgeInterceptor.java)
  or                     .intercept (BridgeInterceptor.java)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java)
  or                     .request (RealInterceptorChain.java)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.cancel (RetryAndFollowUpInterceptor.java)
  or                     .createAddress (RetryAndFollowUpInterceptor.java)
  or                     .followUpRequest (RetryAndFollowUpInterceptor.java)
  or                     .intercept (RetryAndFollowUpInterceptor.java)
  or                     .isRecoverable (RetryAndFollowUpInterceptor.java)
  or                     .recover (RetryAndFollowUpInterceptor.java)
  or                     .sameConnection (RetryAndFollowUpInterceptor.java)
  or                     .setCallStackTrace (RetryAndFollowUpInterceptor.java)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java)
  or                     .request (RealInterceptorChain.java)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java)
  or                     .request (RealInterceptorChain.java)
  at okhttp3.logging.HttpLoggingInterceptor.bodyEncoded (HttpLoggingInterceptor.java)
  or                     .intercept (HttpLoggingInterceptor.java)
  or                     .isPlaintext (HttpLoggingInterceptor.java)
  or                     .setLevel (HttpLoggingInterceptor.java)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java)
  or                     .request (RealInterceptorChain.java)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java)
  or                     .request (RealInterceptorChain.java)
  at okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java)
  at okhttp3.RealCall.access$000 (RealCall.java)
  or                 .enqueue (RealCall.java)
  or                 .execute (RealCall.java)
  or                 .newRealCall (RealCall.java)
  at retrofit2.OkHttpCall.enqueue (OkHttpCall.java)
  or                     .execute (OkHttpCall.java)
  or                     .parseResponse (OkHttpCall.java)
  at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual (CallExecuteObservable.java)
  at io.reactivex.Observable.bufferSize (Observable.java)
  or                     .filter (Observable.java)
  or                     .flatMapSingle (Observable.java)
  or                     .fromArray (Observable.java)
  or                     .just (Observable.java)
  or                     .subscribe (Observable.java)
  or                     .subscribeOn (Observable.java)
  or                     .toFlowable (Observable.java)
  or                     .toList (Observable.java)
  at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual (BodyObservable.java)
  at io.reactivex.Observable.bufferSize (Observable.java)
  or                     .filter (Observable.java)
  or                     .flatMapSingle (Observable.java)
  or                     .fromArray (Observable.java)
  or                     .just (Observable.java)
  or                     .subscribe (Observable.java)
  or                     .subscribeOn (Observable.java)
  or                     .toFlowable (Observable.java)
  or                     .toList (Observable.java)
  at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual (ObservableSingleSingle.java)
  at io.reactivex.Single.doOnSubscribe (Single.java)
  or                    .error (Single.java)
  or                    .flatMap (Single.java)
  or                    .just (Single.java)
  or                    .observeOn (Single.java)
  or                    .subscribe (Single.java)
  or                    .zip (Single.java)
  or                    .zipArray (Single.java)
  at io.reactivex.internal.operators.single.SingleMap.subscribeActual (SingleMap.java)
  at io.reactivex.Single.doOnSubscribe (Single.java)
  or                    .error (Single.java)
  or                    .flatMap (Single.java)
  or                    .just (Single.java)
  or                    .observeOn (Single.java)
  or                    .subscribe (Single.java)
  or                    .zip (Single.java)
  or                    .zipArray (Single.java)
  at io.reactivex.internal.operators.single.SingleZipArray.subscribeActual (SingleZipArray.java)
  at io.reactivex.Single.doOnSubscribe (Single.java)
  or                    .error (Single.java)
  or                    .flatMap (Single.java)
  or                    .just (Single.java)
  or                    .observeOn (Single.java)
  or                    .subscribe (Single.java)
  or                    .zip (Single.java)
  or                    .zipArray (Single.java)
  at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run (SingleSubscribeOn.java)
  at io.reactivex.Scheduler$DisposeTask.run (Scheduler.java)
  at io.reactivex.internal.schedulers.ScheduledRunnable.run (ScheduledRunnable.java)
  at io.reactivex.internal.schedulers.ScheduledRunnable.call (ScheduledRunnable.java)
  at java.util.concurrent.FutureTask.run (FutureTask.java:237)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201 (ScheduledThreadPoolExecutor.java:152)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:265)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
  at java.lang.Thread.run (Thread.java:818)
```

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/56889233-2327b200-6a76-11e9-9a90-497724c37f8f.png)
