### ISSUE TITLE
 Process: com.google.android.GoogleCamera, PID: 25603     java.lang.SecurityException: Permission Denial: writing android.support.v4.content.FileProvider uri content://org.openfoodfacts.scanner.easyphotopicker.fileprovider/picturesext/665c6152-96f5-4424-9d4a-64a7d25638271406564021776967102.jpg from pid=25603, uid=10077 requires the provider be exported, or grantUriPermission()

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2615]
``` 
2019-05-07 22:49:27.176 25603-25603/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.GoogleCamera, PID: 25603
    java.lang.SecurityException: Permission Denial: writing android.support.v4.content.FileProvider uri content://org.openfoodfacts.scanner.easyphotopicker.fileprovider/picturesext/665c6152-96f5-4424-9d4a-64a7d25638271406564021776967102.jpg from pid=25603, uid=10077 requires the provider be exported, or grantUriPermission()
        at android.os.Parcel.createException(Parcel.java:2069)
        at android.os.Parcel.readException(Parcel.java:2037)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
        at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:631)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1505)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1211)
        at android.content.ContentResolver.openOutputStream(ContentResolver.java:1187)
        at ekm.e(PG:11)
        at ekm.c(PG:37)
        at czm.b(PG:13)
        at czm.a(PG:33)
        at egn.onShutterButtonClick(PG:9)
        at jry.onShutterButtonClick(PG:16)
        at com.google.android.apps.camera.ui.shutterbutton.ShutterButton.performClick(PG:498)
        at android.view.View.performClickInternal(View.java:7228)
        at android.view.View.access$3500(View.java:802)
        at android.view.View$PerformClick.run(View.java:27843)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7116)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)
```

**Comment by teolemon** [comment]
might be related to https://github.com/commons-app/apps-android-commons/issues/167

**Comment by deniger** [comment]
Do you have more logs about this: the action that causes this ?

**Comment by ighotouch** [comment]
This describes the possible cause: https://stackoverflow.com/questions/30572261/using-data-from-context-providers-or-requesting-google-photos-read-permission/30909105#30909105

**Comment by teolemon** [comment]
thank you so much @ighotouch 👍 
Would you have some time to investigate ?

**Comment by ighotouch** [comment]
Will take a look at this.

**Comment by teolemon** [comment]
going to close this one, since it's inactive. Will reopen one if I re-encounter the issue.
