### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by itchix** [openfoodfacts/OpenFoodFacts-androidApp#262]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
	at openfoodfacts.github.scrachx.openfood.views.SaveProductOfflineActivity.onSaveProduct(SaveProductOfflineActivity.java:179)
	at openfoodfacts.github.scrachx.openfood.views.SaveProductOfflineActivity_ViewBinding$5.doClick(SaveProductOfflineActivity_ViewBinding.java:91)

**Comment by herau** [comment]
already fixed in another commit
