### ISSUE TITLE
Cannot add photos, camera crash

### ISSUE THREAD

**Issue by VaiTon** [openfoodfacts/openfoodfacts-androidapp#2736]
**Describe the bug**
When I try to open the camera it makes me take the photo but then returns to the product screen without doing nothing.
**To Reproduce**
1. Open a product without images
2. Click on add image
3. Look at Android Studio Log

**Smartphone (please complete the following information):**
 - Device: Huawei p8 lite 2017
 - OS: Android 8
 - Browser: Chrome

**Additional context**
```
W/System.err: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/3433-3732/Android/data/openfoodfacts.github.scrachx.openfood/cache/EasyImage/db40b32c-250f-4208-8ad4-093af753c50b5784083626112538003.jpg
        at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:738)
W/System.err:     at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:417)
        at pl.aprilapps.easyphotopicker.EasyImage.createCameraPictureFile(EasyImage.java:56)
        at pl.aprilapps.easyphotopicker.EasyImage.createCameraIntent(EasyImage.java:86)
        at pl.aprilapps.easyphotopicker.EasyImage.openCamera(EasyImage.java:260)
        at openfoodfacts.github.scrachx.openfood.fragments.BaseFragment.doChooseOrTakePhotos(BaseFragment.java:126)
        at openfoodfacts.github.scrachx.openfood.views.product.summary.SummaryProductFragment.newFrontImage(SummaryProductFragment.java:898)
        at openfoodfacts.github.scrachx.openfood.views.product.summary.SummaryProductFragment.openFullScreen(SummaryProductFragment.java:891)
        at openfoodfacts.github.scrachx.openfood.views.product.summary.SummaryProductFragment_ViewBinding$1.doClick(SummaryProductFragment_ViewBinding.java:66)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
W/System.err:     at android.view.View.performClick(View.java:6291)
        at android.view.View$PerformClick.run(View.java:24931)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
D/CameraPreview: pause()
```

**Comment by VaiTon** [comment]
Because of this issue I can't add any product. The app tells me that I must add at least a photo to save the product but when i take the photo this happens. @teolemon

**Comment by VaiTon** [comment]
As version 3.2.3 this is still an issue.

**Comment by teolemon** [comment]
https://github.com/jkwiecien/EasyImage/issues/78

**Comment by teolemon** [comment]
@VaiTon was it still an issue ? is it still an issue ?

**Comment by VaiTon** [comment]
I don't use that smartphone anymore so I don't really know. I guess we can close for now.

**Comment by teolemon** [comment]
ok, thanks 👍
