### ISSUE TITLE
Image crashing when clicked from compare mode

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2772]
Image crashing when clicked from compare mode

```
2019-06-23 19:55:09.437 17481-17481/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 17481
    java.lang.RuntimeException: Unable to start activity ComponentInfo{openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.ProductImageManagementActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3260)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3396)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7319)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at openfoodfacts.github.scrachx.openfood.views.ProductImageManagementActivity.updateLanguageStatus(ProductImageManagementActivity.java:201)
        at openfoodfacts.github.scrachx.openfood.views.ProductImageManagementActivity.stopRefresh(ProductImageManagementActivity.java:337)
        at openfoodfacts.github.scrachx.openfood.views.ProductImageManagementActivity.access$200(ProductImageManagementActivity.java:52)
        at openfoodfacts.github.scrachx.openfood.views.ProductImageManagementActivity$1.onSuccess(ProductImageManagementActivity.java:254)
        at com.squareup.picasso.RequestCreator.into(RequestCreator.java:657)
        at openfoodfacts.github.scrachx.openfood.views.ProductImageManagementActivity.loadImage(ProductImageManagementActivity.java:248)
        at openfoodfacts.github.scrachx.openfood.views.ProductImageManagementActivity.onRefresh(ProductImageManagementActivity.java:239)
        at openfoodfacts.github.scrachx.openfood.views.ProductImageManagementActivity.onCreate(ProductImageManagementActivity.java:124)
        at android.app.Activity.performCreate(Activity.java:7783)
        at android.app.Activity.performCreate(Activity.java:7772)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3235)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3396) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7319) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934) 
2019-06-23 19:55:09.490 1088-1375/? E/InputDispatcher: channel '6dfb308 openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2019-06-23 19:55:11.027 18147-18147/openfoodfacts.github.scrachx.openfood E/RecyclerView: No adapter attached; skipping layout
2019-06-23 19:55:11.028 18147-20640/openfoodfacts.github.scrachx.openfood E/libEGL: Driver indicates EGL 1.5 support, but does not have a critical API

```

**Comment by deniger** [comment]
Fixed with last PR
