### ISSUE TITLE
Trace from Crash with AsyncTasks on OpenPetFoodFacts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2820]
2019-07-03 13:57:58.785 29126-29229/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: org.openpetfoodfacts.scanner, PID: 29126
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalArgumentException: the bind value at index 1 is null
        at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:167)
        at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:203)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:49)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1443)
        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1382)
        at org.greenrobot.greendao.database.StandardDatabase.rawQuery(StandardDatabase.java:32)
        at org.greenrobot.greendao.query.Query.list(Query.java:88)
        at org.greenrobot.greendao.query.QueryBuilder.list(QueryBuilder.java:427)
        at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient.addToHistory(OpenFoodAPIClient.java:558)
        at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient$HistoryTask.doInBackground(OpenFoodAPIClient.java:551)
        at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient$HistoryTask.doInBackground(OpenFoodAPIClient.java:546)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2019-07-03 14:09:17.592 29343-31692/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: org.openpetfoodfacts.scanner, PID: 29343
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalArgumentException: the bind value at index 1 is null
        at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:167)
        at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:203)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:49)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1443)
        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1382)
        at org.greenrobot.greendao.database.StandardDatabase.rawQuery(StandardDatabase.java:32)
        at org.greenrobot.greendao.query.Query.list(Query.java:88)
        at org.greenrobot.greendao.query.QueryBuilder.list(QueryBuilder.java:427)
        at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient.addToHistory(OpenFoodAPIClient.java:558)
        at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient$HistoryTask.doInBackground(OpenFoodAPIClient.java:551)
        at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient$HistoryTask.doInBackground(OpenFoodAPIClient.java:546)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2019-07-03 14:09:44.858 31701-31763/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: org.openpetfoodfacts.scanner, PID: 31701
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:399)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.IllegalArgumentException: the bind value at index 1 is null
        at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:167)
        at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:203)
        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:49)
        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1443)
        at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1382)
        at org.greenrobot.greendao.database.StandardDatabase.rawQuery(StandardDatabase.java:32)
        at org.greenrobot.greendao.query.Query.list(Query.java:88)
        at org.greenrobot.greendao.query.QueryBuilder.list(QueryBuilder.java:427)
        at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient.addToHistory(OpenFoodAPIClient.java:558)
        at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient$HistoryTask.doInBackground(OpenFoodAPIClient.java:551)
        at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient$HistoryTask.doInBackground(OpenFoodAPIClient.java:546)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by deniger** [comment]
For Open Pet Food Facts, the issue is that this query:
https://ssl-api.openpetfoodfacts.org/api/v0/product/3662852000255.json?fields=emb_codes_tags%2Cother_information%2Cvitamins_tags%2Ccustomer_service%2Crecycling_instructions_to_discard_en%2Cimage_nutrition_url%2Cnutriments%2Cother_information_en%2Ccustomer_service_en%2Cserving_size%2Cconservation_conditions%2Cwarning%2Cproduct_name_en%2Cwarning_en%2Camino_acids_tags%2Cimage_small_url%2Cnutrient_levels%2Cadditives_tags%2Cbrands_tags%2Cimage_url%2Cgeneric_name%2Ctraces%2Cimage_ingredients_url_en%2Cingredients_from_palm_oil_tags%2Ccountries%2Cpurchase_places%2Cproduct_name%2Crecycling_instructions_to_recycle%2Cminerals_tags%2Ctraces_tags%2Clabels_hierarchy%2Cno_nutrition_data%2Cenvironment_infocard%2Cingredients_from_or_that_may_be_from_palm_oil_n%2Cnutrition_grade_fr%2Cimage_nutrition_url_en%2Ccities_tags%2Cgeneric_name_en%2Cconservation_conditions_en%2Cother%2Ccode%2Cingredients_text_en%2Cingredients_from_palm_oil_n%2Clink%2Clanguages_codes%2Cstates_tags%2Callergens_tags%2Cimage_ingredients_url%2Ccategories_tags%2Cenvironment_impact_level_tags%2Cnutrition_data_per%2Cother_nutritional_substances_tags%2Corigins%2Clang%2Cimage_front_url%2Cnova_groups%2Ccreator%2Cbrands%2Cquantity%2Cstores%2Cmanufacturing_places%2Crecycling_instructions_to_recycle_en%2Cpackaging%2Clast_modified_t%2Clast_modified_by%2Ccountries_tags%2Crecycling_instructions_to_discard%2Curl%2Callergens%2Cingredients_that_may_be_from_palm_oil_tags%2Cingredients_text%2Ceditors_tags%2Ccreated_t%2Cselected_images%2Clabels_tags%2Cimage_front_url_en%2Callergens_hierarchy 

return  this:
`
status | 1
-- | --
product | {}
status_verbose | "product found"
code | "3662852000255"
`

A parameter is not supported I guess...

**Comment by teolemon** [comment]
https://ssl-api.openpetfoodfacts.org/api/v0/product/3662852000255.json?fields=emb_codes_tags,other_information,vitamins_tags,customer_service,recycling_instructions_to_discard_en,image_nutrition_url,nutriments,other_information_en,customer_service_en,serving_size,conservation_conditions,warning,product_name_en,warning_en,amino_acids_tags,image_small_url,nutrient_levels,additives_tags,brands_tags,image_url,generic_name,traces,image_ingredients_url_en,ingredients_from_palm_oil_tags,countries,purchase_places,product_name,recycling_instructions_to_recycle,minerals_tags,traces_tags,labels_hierarchy,no_nutrition_data,environment_infocard,ingredients_from_or_that_may_be_from_palm_oil_n,nutrition_grade_fr,image_nutrition_url_en,cities_tags,generic_name_en,conservation_conditions_en,other,code,ingredients_text_en,ingredients_from_palm_oil_n,link,languages_codes,states_tags,allergens_tags,image_ingredients_url,categories_tags,environment_impact_level_tags,nutrition_data_per,other_nutritional_substances_tags,origins,lang,image_front_url,nova_groups,creator,brands,quantity,stores,manufacturing_places,recycling_instructions_to_recycle_en,packaging,last_modified_t,last_modified_by,countries_tags,recycling_instructions_to_discard,url,allergens,ingredients_that_may_be_from_palm_oil_tags,ingredients_text,editors_tags,created_t,selected_images,labels_tags,image_front_url_en,allergens_hierarchy

**Comment by teolemon** [comment]
My guess is that the Open Pet Food Facts server is not up to date. @stephanegigandet 
https://ssl-api.openpetfoodfacts.org/api/v0/product/3662852000255.json?fields=
emb_codes_tags
other_information
vitamins_tags
customer_service
recycling_instructions_to_discard_en
image_nutrition_url
nutriments
other_information_en
customer_service_en
serving_size
conservation_conditions
warning
product_name_en
warning_en
amino_acids_tags
image_small_url
nutrient_levels
additives_tags
brands_tags
image_url
generic_name
traces
image_ingredients_url_en
ingredients_from_palm_oil_tags
countries
purchase_places
product_name
recycling_instructions_to_recycle
minerals_tags
traces_tags
labels_hierarchy
no_nutrition_data
environment_infocard
ingredients_from_or_that_may_be_from_palm_oil_n
nutrition_grade_fr
image_nutrition_url_en
cities_tags
generic_name_en
conservation_conditions_en
other
code
ingredients_text_en
ingredients_from_palm_oil_n
link
languages_codes
states_tags
allergens_tags
image_ingredients_url
categories_tags
environment_impact_level_tags
nutrition_data_per
other_nutritional_substances_tags
origins
lang
image_front_url
nova_groups
creator
brands
quantity
stores
manufacturing_places
recycling_instructions_to_recycle_en
packaging
last_modified_t
last_modified_by
countries_tags
recycling_instructions_to_discard
url
allergens
ingredients_that_may_be_from_palm_oil_tags
ingredients_text
editors_tags
created_t
selected_images
labels_tags
image_front_url_en
allergens_hierarchy

**Comment by deniger** [comment]
The same query with OFF works:
 https://ssl-api.openfoodfacts.org/api/v0/product/5060229012371.json?fields=emb_codes_tags%2Cother_information%2Cvitamins_tags%2Ccustomer_service%2Crecycling_instructions_to_discard_en%2Cimage_nutrition_url%2Cnutriments%2Cother_information_en%2Ccustomer_service_en%2Cserving_size%2Cconservation_conditions%2Cwarning%2Cproduct_name_en%2Cwarning_en%2Camino_acids_tags%2Cimage_small_url%2Cnutrient_levels%2Cadditives_tags%2Cbrands_tags%2Cimage_url%2Cgeneric_name%2Ctraces%2Cimage_ingredients_url_en%2Cingredients_from_palm_oil_tags%2Ccountries%2Cpurchase_places%2Cproduct_name%2Crecycling_instructions_to_recycle%2Cminerals_tags%2Ctraces_tags%2Clabels_hierarchy%2Cno_nutrition_data%2Cenvironment_infocard%2Cingredients_from_or_that_may_be_from_palm_oil_n%2Cnutrition_grade_fr%2Cimage_nutrition_url_en%2Ccities_tags%2Cgeneric_name_en%2Cconservation_conditions_en%2Cother%2Ccode%2Cingredients_text_en%2Cingredients_from_palm_oil_n%2Clink%2Clanguages_codes%2Cstates_tags%2Callergens_tags%2Cimage_ingredients_url%2Ccategories_tags%2Cenvironment_impact_level_tags%2Cnutrition_data_per%2Cother_nutritional_substances_tags%2Corigins%2Clang%2Cimage_front_url%2Cnova_groups%2Ccreator%2Cbrands%2Cquantity%2Cstores%2Cmanufacturing_places%2Crecycling_instructions_to_recycle_en%2Cpackaging%2Clast_modified_t%2Clast_modified_by%2Ccountries_tags%2Crecycling_instructions_to_discard%2Curl%2Callergens%2Cingredients_that_may_be_from_palm_oil_tags%2Cingredients_text%2Ceditors_tags%2Ccreated_t%2Cselected_images%2Clabels_tags%2Cimage_front_url_en%2Callergens_hierarchy

**Comment by teolemon** [comment]
The queries now work. Closing
