### ISSUE TITLE
Crash on product addition from trunk

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2821]
``` 
2019-07-04 11:12:58.798 10642-10642/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 10642
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=131275, result=-1, data=Intent { (has extras) }} to activity {openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.AddProductActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4830)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4871)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7319)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
        at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.hideImageProgress(AddProductOverviewFragment.java:950)
        at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.hideImageProgress(AddProductActivity.java:1185)
        at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.access$2100(AddProductActivity.java:58)
        at openfoodfacts.github.scrachx.openfood.views.AddProductActivity$8.onError(AddProductActivity.java:1101)
        at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:78)
        at io.reactivex.internal.operators.single.SingleDoOnSubscribe$DoOnSubscribeSingleObserver.onSubscribe(SingleDoOnSubscribe.java:65)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.onSubscribe(SingleObserveOn.java:57)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onSubscribe(ObservableSingleSingle.java:58)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn.subscribeActual(ObservableSubscribeOn.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleDoOnSubscribe.subscribeActual(SingleDoOnSubscribe.java:41)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.savePhoto(AddProductActivity.java:1050)
        at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.addToPhotoMap(AddProductActivity.java:1043)
        at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.onPhotoReturned(AddProductOverviewFragment.java:921)
        at openfoodfacts.github.scrachx.openfood.jobs.PhotoReceiverHandler.onCropResult(PhotoReceiverHandler.java:105)
        at openfoodfacts.github.scrachx.openfood.jobs.PhotoReceiverHandler.onActivityResult(PhotoReceiverHandler.java:39)
        at openfoodfacts.github.scrachx.openfood.jobs.PhotoReceiverHandler.onActivityResult(PhotoReceiverHandler.java:31)
        at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.onActivityResult(AddProductOverviewFragment.java:939)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:160)
2019-07-04 12:22:46.270 538-538/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 538
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=131275, result=-1, data=Intent { (has extras) }} to activity {openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.AddProductActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4830)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4871)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7319)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
        at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.hideImageProgress(AddProductOverviewFragment.java:950)
        at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.hideImageProgress(AddProductActivity.java:1185)
        at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.access$2100(AddProductActivity.java:58)
        at openfoodfacts.github.scrachx.openfood.views.AddProductActivity$8.onError(AddProductActivity.java:1101)
        at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:78)
        at io.reactivex.internal.operators.single.SingleDoOnSubscribe$DoOnSubscribeSingleObserver.onSubscribe(SingleDoOnSubscribe.java:65)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.onSubscribe(SingleObserveOn.java:57)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onSubscribe(ObservableSingleSingle.java:58)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn.subscribeActual(ObservableSubscribeOn.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleDoOnSubscribe.subscribeActual(SingleDoOnSubscribe.java:41)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.savePhoto(AddProductActivity.java:1050)
        at openfoodfacts.github.scrachx.openfood.views.AddProductActivity.addToPhotoMap(AddProductActivity.java:1043)
        at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.onPhotoReturned(AddProductOverviewFragment.java:921)
        at openfoodfacts.github.scrachx.openfood.jobs.PhotoReceiverHandler.onCropResult(PhotoReceiverHandler.java:105)
        at openfoodfacts.github.scrachx.openfood.jobs.PhotoReceiverHandler.onActivityResult(PhotoReceiverHandler.java:39)
        at openfoodfacts.github.scrachx.openfood.jobs.PhotoReceiverHandler.onActivityResult(PhotoReceiverHandler.java:31)
        at openfoodfacts.github.scrachx.openfood.fragments.AddProductOverviewFragment.onActivityResult(AddProductOverviewFragment.java:939)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:160)
2019-07-04 12:22:46.440 1428-1428/openfoodfacts.github.scrachx.openfood E/crachx.openfoo: Unknown bits set in runtime_flags: 0x8000
2019-07-04 12:22:48.338 1428-1428/openfoodfacts.github.scrachx.openfood E/showCat: false
2019-07-04 12:22:49.102 1428-1505/openfoodfacts.github.scrachx.openfood E/libEGL: Driver indicates EGL 1.5 support, but does not have a critical API
2019-07-04 12:22:49.323 1428-1428/openfoodfacts.github.scrachx.openfood E/showCat: false
```

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/60707689-93d2cb00-9f0c-11e9-95e0-abc1988520a9.png)
https://teamtreehouse.com/community/javalangnullpointerexception-attempt-to-invoke-virtual-method-void-androidwidgetprogressbarsetvisibilityint
