### ISSUE TITLE
Crash when clicking on Help complete categories in the category explorer

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#2823]
Crash when clicking on Help complete categories in the category explorer
It should open a Chrome Custom Tab, instead it crashes the app
```  
2019-07-06 20:53:55.021 5793-5793/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood, PID: 5793
    android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
        at android.app.ContextImpl.startActivity(ContextImpl.java:952)
        at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:248)
        at androidx.browser.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:263)
        at openfoodfacts.github.scrachx.openfood.views.category.activity.CategoryActivity.lambda$onCreate$1$CategoryActivity(CategoryActivity.java:65)
        at openfoodfacts.github.scrachx.openfood.views.category.activity.-$$Lambda$CategoryActivity$FNGAsGYmFkXkquF5pu5-EgmUiA8.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3400(View.java:801)
        at android.view.View$PerformClick.run(View.java:27301)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7319)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)

```

**Comment by teolemon** [comment]
I have this on the @dobriseb branch for diets, but I think it might happen on trunk.
