### ISSUE TITLE
NPE on OPF continuous scan

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3149]
```
FATAL EXCEPTION: Thread-1155
Process: org.openproductsfacts.scanner, PID: 19329
java.lang.NullPointerException: Attempt to read from field 'android.widget.EditText openfoodfacts.github.scrachx.openfood.d.a.O' on a null object reference
	at openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity.hideAllViews(ContinuousScanActivity.java:463)
	at openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity.lambda$onCreate$7(ContinuousScanActivity.java:560)
	at openfoodfacts.github.scrachx.openfood.views.-$$Lambda$ContinuousScanActivity$kNT4tS01CpARjbn5Wc_WCURtDk4.run(-.java)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:132)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:126)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:102)
	at androidx.test.espresso.action.Tap$2.a(Tap.java:7)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:33)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5538)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
 ```

**Comment by VaiTon** [comment]
It does work for me. Are you running master? I'm running 11fb788610363532b326c6ef45f874801592951d.

**Comment by teolemon** [comment]
master with Open Products Facts, in testing mode (those are the automated playstore checks)

**Comment by teolemon** [comment]
before GreenDao, possibly

**Comment by teolemon** [comment]
I built that this night

**Comment by teolemon** [comment]
```
Today, 12:50 AM on app version 420
Samsung Galaxy S10+ (beyond2), 7424MB RAM, Android 10
Report 1 of 1
java.lang.NullPointerException: 
  at openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity.hideAllViews (ContinuousScanActivity.java:463)
  at openfoodfacts.github.scrachx.openfood.views.ContinuousScanActivity.lambda$onCreate$7 (ContinuousScanActivity.java:560)
  at openfoodfacts.github.scrachx.openfood.views.-$$Lambda$ContinuousScanActivity$kNT4tS01CpARjbn5Wc_WCURtDk4.run (-.java:2)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:8016)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1076)
```

**Comment by teolemon** [comment]
closing for now
