### ISSUE TITLE
The app is not able to send the authed answer to Robotoff questions anymore

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3184]
The app is not able to send the authed answer to Robotoff questions anymore after a hasty merge or the Auth PR by @VaiTon by me

https://github.com/openfoodfacts/openfoodfacts-androidapp/commit/05f3f5227e29b001d1a5baa1601ee0c9eece11d5

**Comment by teolemon** [comment]
@raphael0202 does the auth mechanism seem right ?
```
        // if the user is logged in, send the auth, otherwise make it anonymous
        final SharedPreferences userPref = OFFApplication.getInstance()
            .getSharedPreferences("login", 0);

        final String user = userPref.getString("user", "");
        final String pass = userPref.getString("pass", "");

        if (StringUtils.isNotBlank(user) && StringUtils.isNotBlank(pass)) {
            final String baseAuth = "Basic " + Base64.encodeToString(
                (user + ":" + pass).getBytes(), Base64.DEFAULT);

            return robotoffApi.annotateInsight(insightId, annotation, baseAuth);
        } else {
            return robotoffApi.annotateInsight(insightId, annotation);
        }
```

**Comment by teolemon** [comment]
```
2020-06-06 16:30:06.162 17207-17207/openfoodfacts.github.scrachx.openfood E/SummaryProductPresenter: annotateInsight
    java.lang.IllegalArgumentException: Unexpected char 0x0a at 46 in Authentication value: Basic aHVuZ2VyZ2FtZXM6aGFwcHlodW5nZXJnYW1lcw==
        at okhttp3.Headers.checkValue(Headers.java:272)
        at okhttp3.Headers$Builder.add(Headers.java:312)
        at retrofit2.RequestBuilder.addHeader(RequestBuilder.java:104)
        at retrofit2.ParameterHandler$Header.apply(ParameterHandler.java:89)
        at retrofit2.RequestFactory.create(RequestFactory.java:117)
        at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:192)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:175)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12284)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3666)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```
I got this for Robotoff and that might be the solution: https://github.com/square/retrofit/issues/1153
