### ISSUE TITLE
Crash after product save

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#322]
Crash : online, product addition, front photo taken, no text, hit send, photo sent, product saved then the app crashes.

```
12-03 17:47:42.939 18348-19844/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                                                       Process: openfoodfacts.github.scrachx.openfood, PID: 18348
                                                                                       java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                           at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                                                           at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                           at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                                           at java.lang.Thread.run(Thread.java:761)
                                                                                        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                                           at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:658)
                                                                                           at openfoodfacts.github.scrachx.openfood.fragments.OfflineEditFragment$FillAdapter.doInBackground(OfflineEditFragment.java:197)
                                                                                           at openfoodfacts.github.scrachx.openfood.fragments.OfflineEditFragment$FillAdapter.doInBackground(OfflineEditFragment.java:172)
                                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                                           at java.lang.Thread.run(Thread.java:761) 
```

**Comment by teolemon** [comment]
Moto G - Nougat (Cyanogenmod)

**Comment by lucaa** [comment]
I had a bug on adding a new product as well, but I don't know the error because I was using the app, not debugging it.

I added a new product with the 3 photos, without text and it crashed on upload. It saved the product but it did not upload all photos.

**Comment by herau** [comment]
reproduce. asynchronous task with the taken picture.

**Comment by herau** [comment]
@teolemon currently when we had a product, the user return to the main activity.
Why not send the user to the product page ?

**Comment by teolemon** [comment]
+1

**Comment by teolemon** [comment]
@lucaa can you confirm trunk works for you ?
