### ISSUE TITLE
Category explorer crashing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3231]
Video to reproduce: https://photos.app.goo.gl/9qntvPGu4rsn5Nf79

```
2020-06-10 13:11:33.842 19372-19372/? E/AndroidRuntime:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: openfoodfacts.github.scrachx.openfood.views.category.fragment.CategoryListFragment
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at androidx.fragment.app.h.c(FragmentFactory.java:2)
        at androidx.fragment.app.h.d(FragmentFactory.java:1)
        	... 35 more
     Caused by: java.lang.ClassNotFoundException: openfoodfacts.github.scrachx.openfood.views.category.fragment.CategoryListFragment
        	... 39 more
```

**Comment by teolemon** [comment]
2020-06-10 13:11:33.842 19372-19372/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.openbeautyfacts.scanner, PID: 19372
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.openbeautyfacts.scanner/openfoodfacts.github.scrachx.openfood.views.category.activity.CategoryActivity}: android.view.InflateException: Binary XML file line #31 in org.openbeautyfacts.scanner:layout/activity_category: Binary XML file line #31 in org.openbeautyfacts.scanner:layout/activity_category: Error inflating class androidx.fragment.app.FragmentContainerView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.InflateException: Binary XML file line #31 in org.openbeautyfacts.scanner:layout/activity_category: Binary XML file line #31 in org.openbeautyfacts.scanner:layout/activity_category: Error inflating class androidx.fragment.app.FragmentContainerView
     Caused by: android.view.InflateException: Binary XML file line #31 in org.openbeautyfacts.scanner:layout/activity_category: Error inflating class androidx.fragment.app.FragmentContainerView
     Caused by: androidx.fragment.app.Fragment$d: Unable to instantiate fragment openfoodfacts.github.scrachx.openfood.views.category.fragment.CategoryListFragment: make sure class name exists
        at androidx.fragment.app.h.d(FragmentFactory.java:3)
        at androidx.fragment.app.Fragment.m0(Fragment.java:2)
        at androidx.fragment.app.f.a(FragmentContainer.java:1)
        at androidx.fragment.app.l$c.a(FragmentManager.java:1)
        at androidx.fragment.app.FragmentContainerView.<init>(FragmentContainerView.java:17)
        at androidx.fragment.app.j.onCreateView(FragmentLayoutInflaterFactory.java:3)
        at androidx.fragment.app.g.w(FragmentController.java:2)
        at androidx.fragment.app.d.B(FragmentActivity.java:1)
        at androidx.fragment.app.d.onCreateView(FragmentActivity.java:1)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at androidx.databinding.g.e(DataBindingUtil.java:2)
        at androidx.databinding.ViewDataBinding.A(ViewDataBinding.java:2)
        at openfoodfacts.github.scrachx.openfood.d.e.T(ActivityCategoryBinding.java:1)
        at openfoodfacts.github.scrachx.openfood.d.e.S(ActivityCategoryBinding.java:1)
        at openfoodfacts.github.scrachx.openfood.views.category.activity.CategoryActivity.onCreate(CategoryActivity.java:4)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)

**Comment by teolemon** [comment]
Still happening on latest master

**Comment by VaiTon** [comment]
I think it is caused by proguard, because it changes class names. Let's try setting it from the code.

**Comment by VaiTon** [comment]
Try PR https://github.com/openfoodfacts/openfoodfacts-androidapp/pull/3251
