### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String com.fasterxml.jackson.databind.JsonNode.toString()' on a null object reference  (OpenFoodAPIClient.java:9)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3249]
```
2020-06-13 12:57:19.963 17242-17302/? D/OkHttp: <-- 200 https://ssl-api.openbeautyfacts.org/api/v0/product/4013474107010.json?fields=ingredients (20ms, unknown-length body)
2020-06-13 12:57:19.984 17242-17242/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.openbeautyfacts.scanner, PID: 17242
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.fasterxml.jackson.databind.JsonNode.toString()' on a null object reference
        at openfoodfacts.github.scrachx.openfood.h.w$m.b(OpenFoodAPIClient.java:9)
        at o.g$b$a$a.run(DefaultCallAdapterFactory.java:3)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

**Comment by teolemon** [comment]
Happens on swiping to ingredients tab on latest master for Open Beauty Facts on product above (not all products)

**Comment by VaiTon** [comment]
@teolemon sometimes "rank" field is not returned for ingredients, apparently. Is this normal behavior? Should we report to product opener?

**Comment by stephanegigandet** [comment]
Rank is returned only for top level ingredients, not sub ingredients. That's the normal behaviour.
