### ISSUE TITLE
App crashes when camera permission is off.

### ISSUE THREAD

**Issue by arsadeghi** [openfoodfacts/OpenFoodFacts-androidApp#329]
When the "Camera" permission is revoked, app crashes after clicking on "TAKE PICTURE" button in the page for adding the information of a product. (The clip of reproducible bug scenario is attached)

![openfood](https://cloud.githubusercontent.com/assets/11197005/20986980/b32e21ec-bc7f-11e6-8f3e-3bd7317d1dbb.gif)

I believe the APIs for checking(checkSelfPermission)/asking(requestPermissions) CAMERA permission should get called.

Here is the stack trace after the crash:

```
12-07 13:20:29.759 11938-11938/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: openfoodfacts.github.scrachx.openfood, PID: 11938
                                                                                       java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.android.camera/.Camera clip={text/uri-list U:file:///storage/emulated/0/Android/data/openfoodfacts.github.scrachx.openfood/files/Pictures/OFF_Images/44058612-cd5a-4913-b4a6-eb6ac3c1ecee1158311955.jpg} (has extras) } from ProcessRecord{4eae974 11938:openfoodfacts.github.scrachx.openfood/u0a131} (pid=11938, uid=10131) with revoked permission android.permission.CAMERA
                                                                                           at android.os.Parcel.readException(Parcel.java:1599)
                                                                                           at android.os.Parcel.readException(Parcel.java:1552)
                                                                                           at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2658)
                                                                                           at android.app.Instrumentation.execStartActivity(Instrumentation.java:1507)
                                                                                           at android.app.Activity.startActivityForResult(Activity.java:3917)
                                                                                           at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
                                                                                           at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:77)
                                                                                           at android.app.Activity.startActivityForResult(Activity.java:3877)
                                                                                           at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                                           at pl.aprilapps.easyphotopicker.EasyImage.openCamera(EasyImage.java:212)
                                                                                           at openfoodfacts.github.scrachx.openfood.views.SaveProductOfflineActivity.onTakePhotoClicked(SaveProductOfflineActivity.java:240)
                                                                                           at openfoodfacts.github.scrachx.openfood.views.SaveProductOfflineActivity_ViewBinding$3.doClick(SaveProductOfflineActivity_ViewBinding.java:73)
                                                                                           at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                                                           at android.view.View.performClick(View.java:5198)
                                                                                           at android.view.View$PerformClick.run(View.java:21147)
                                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by teolemon** [comment]
Nice spot @arsadeghi :-)

**Comment by herau** [comment]
@teolemon can we also ask permissions during the installation step ? if not already done

**Comment by teolemon** [comment]
Asking as needed might increase install rate ?
