### ISSUE TITLE
Crash when clicking on Manage Account (while logged in)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#341]
```
12-20 15:13:18.941 942-942/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
  Process: openfoodfacts.github.scrachx.openfood, PID: 942
  android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW pkg=com.android.chrome (has extras) }
      at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
      at android.app.Activity.startActivityForResult(Activity.java:3930)
      at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:77)
      at android.app.Activity.startActivityForResult(Activity.java:3890)
      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
      at android.app.Activity.startActivity(Activity.java:4213)
      at android.support.v4.content.ContextCompatJellybean.startActivity(ContextCompatJellybean.java:30)
      at android.support.v4.content.ContextCompat.startActivity(ContextCompat.java:151)
      at android.support.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:262)
      at openfoodfacts.github.scrachx.openfood.views.customtabs.CustomTabActivityHelper.openCustomTab(CustomTabActivityHelper.java:57)
      at openfoodfacts.github.scrachx.openfood.views.MainActivity$1.onProfileChanged(MainActivity.java:123)
      at com.mikepenz.materialdrawer.AccountHeaderBuilder$7.onItemClick(AccountHeaderBuilder.java:1423)
      at com.mikepenz.materialdrawer.DrawerBuilder$5.onClick(DrawerBuilder.java:1716)
      at com.mikepenz.materialdrawer.DrawerBuilder$5.onClick(DrawerBuilder.java:1690)
      at com.mikepenz.fastadapter.FastAdapter$1.onClick(FastAdapter.java:433)
      at android.view.View.performClick(View.java:5204)
      at android.view.View$PerformClick.run(View.java:21153)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:148)
      at android.app.ActivityThread.main(ActivityThread.java:5461)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-20 15:13:21.289 942-942/openfoodfacts.github.scrachx.openfood I/Process: Sending signal. PID: 942 SIG: 9

```

**Comment by herau** [comment]
works for me but i have a `Error Permission Denied` page with this kind of url:

`http://world.openfoodfacts.org/cgi/user.pl?type=edit&userid=herau&user_id=herau&user_session=XXXXX`

**Comment by Karljoones** [comment]
This button is currently disabled due to a recent PR merge, I'm going to close this for now and open another issue about replacing it somewhere useful, though is there a way of putting this somewhere useful and keeping the user logged in to manage it without exposing their password etc? Maybe we could have a dedicated activity to handle this in-app?
