### ISSUE TITLE
Unable to import additives from additives_fr.json     java.io.FileNotFoundException: additives_fr.json

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3435]
Happens when switching languages from the settings. Symptom: the new language (French) is not displayed.
```
2020-08-19 13:42:43.805 26256-26306/? E/ADDITIVE_IMPORT: Unable to import additives from additives_fr.json
    java.io.FileNotFoundException: additives_fr.json
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:874)
        at android.content.res.AssetManager.open(AssetManager.java:851)
        at openfoodfacts.github.scrachx.openfood.g.w2.x2(PreferencesFragment.java:4)
        at openfoodfacts.github.scrachx.openfood.g.d2.call(Unknown Source:2)
        at h.a.v.e.e.g.s(SingleFromCallable.java:4)
        at h.a.p.b(Single.java:4)
        at h.a.v.e.e.l$a.run(SingleSubscribeOn.java:1)
        at h.a.o$a.run(Scheduler.java:2)
        at h.a.v.g.k.run(ScheduledRunnable.java:2)
        at h.a.v.g.k.call(ScheduledRunnable.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by teolemon** [comment]
```
2020-08-19 13:45:14.931 26256-27667/? E/ADDITIVE_IMPORT: Unable to import additives from additives_it.json
    java.io.FileNotFoundException: additives_it.json
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:874)
        at android.content.res.AssetManager.open(AssetManager.java:851)
        at openfoodfacts.github.scrachx.openfood.g.w2.x2(PreferencesFragment.java:4)
        at openfoodfacts.github.scrachx.openfood.g.d2.call(Unknown Source:2)
        at h.a.v.e.e.g.s(SingleFromCallable.java:4)
        at h.a.p.b(Single.java:4)
        at h.a.v.e.e.l$a.run(SingleSubscribeOn.java:1)
        at h.a.o$a.run(Scheduler.java:2)
        at h.a.v.g.k.run(ScheduledRunnable.java:2)
        at h.a.v.g.k.call(ScheduledRunnable.java:1)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by teolemon** [comment]
I'm not sure why we a reloading taxonomy JSON, let alone prefixing a langcode (they are language independant)

**Comment by VaiTon** [comment]
Legacy code IMO. I'm checking.

**Comment by teolemon** [comment]
@VaiTon I'm closing, I think you fixed it.
