### ISSUE TITLE
IllegalStateException: Fragment not attached to an activity at openfood.views.product - (IngredientsProductFragment.java:2)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3472]
java.lang.IllegalStateException: Fragment z{ebe6e16} (cc8b936a-0eb2-4a6e-8ba9-1f28672b6de6)} not attached to an activity.

```
FATAL EXCEPTION: Thread-8
Process: org.openfoodfacts.scanner, PID: 27927
java.lang.IllegalStateException: Fragment z{ebe6e16} (cc8b936a-0eb2-4a6e-8ba9-1f28672b6de6)} not attached to an activity.
	at androidx.fragment.app.Fragment.D1(Fragment.java:2)
	at openfoodfacts.github.scrachx.openfood.views.product.l.z.o2(IngredientsProductFragment.java:2)
	at openfoodfacts.github.scrachx.openfood.views.product.ProductActivity.k0(ProductActivity.java:7)
	at openfoodfacts.github.scrachx.openfood.views.product.m.o.s2(IngredientsWithTagDialogFragment.java:5)
	at openfoodfacts.github.scrachx.openfood.views.product.m.o.B2(IngredientsWithTagDialogFragment.java:1)
	at openfoodfacts.github.scrachx.openfood.views.product.m.j.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:6877)
	at android.view.View$PerformClick.run(View.java:26069)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:130)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:124)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:40)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:68)
	at androidx.test.espresso.action.Tap.a(Unknown Source:13)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:2)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:9)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:6)
	at androidx.test.espresso.ViewInteraction.a(Unknown Source:140)
	at androidx.test.espresso.ViewInteraction$1.call(Unknown Source:4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6938)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by teolemon** [comment]
Probably the same as #3460 and #3461 #3440

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/main/java/openfoodfacts/github/scrachx/openfood/views/product/ingredients_analysis/IngredientsWithTagDialogFragment.java#L193
```
            helpNeeded.setText(Html.fromHtml(getString(R.string.help_extract_ingredients, typeName.toLowerCase())));
            helpNeeded.setOnClickListener(v -> goToExtract());
            helpNeeded.setVisibility(View.VISIBLE);
```
