### ISSUE TITLE
Build failing in develop

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3516]
Caused by: /home/runner/work/openfoodfacts-androidapp/openfoodfacts-androidapp/app/src/main/res/values-lol/strings.xml: Error: Found item String/txtHomeOnline more than one time
	at com.android.ide.common.resources.MergingException.throwIfNonEmpty(MergingException.java:170)
	at com.android.ide.common.resources.DataSet.loadFromFiles(DataSet.java:261)
	at com.android.build.gradle.tasks.MergeResources.lambda$doFullTaskAction$0(MergeResources.java:276)
	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:58)
	at com.android.build.gradle.tasks.MergeResources.doFullTaskAction(MergeResources.java:270)
	... 97 more

**Comment by teolemon** [comment]
fixed by https://github.com/openfoodfacts/openfoodfacts-androidapp/commit/6a9e2f406846ca03d7bee0cccd0feb6c7fff29a3
