### ISSUE TITLE
Crash on ingredient extraction

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3572]
Crash on ingredient extraction
```
2020-11-04 22:44:01.571 4536-25172/? E/ThirdPartyChatAppSvc: ThirdPartyChatAppService: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:openfoodfacts.github.scrachx.openfood.debug flg=0x4000010 cmp=com.google.android.wearable.app/com.google.android.clockwork.companion.messaging.ThirdPartyChatAppService (has extras) }
2020-11-04 22:44:02.173 24652-24652/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.openfoodfacts.scanner, PID: 24652
    java.lang.IllegalStateException: Fragment z{8ca173e} (2d302c50-15ef-4683-a8de-b1fe4c746c6c) f1} is attempting to registerForActivityResult after being created. Fragments must call registerForActivityResult() before they are created (i.e. initialization, onAttach(), or onCreate()).
        at androidx.fragment.app.Fragment.D1(Fragment.java:5)
        at androidx.fragment.app.Fragment.E1(Fragment.java:1)
        at openfoodfacts.github.scrachx.openfood.features.product.view.m.z.u2(IngredientsProductFragment.java:7)
        at openfoodfacts.github.scrachx.openfood.features.product.view.m.z.I2(IngredientsProductFragment.java:1)
        at openfoodfacts.github.scrachx.openfood.features.product.view.m.z.J2(Unknown Source:0)
        at openfoodfacts.github.scrachx.openfood.features.product.view.m.d.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by VaiTon** [comment]
Sorry, which branch are you talking about? Could you link the hash? @teolemon thanks!

**Comment by teolemon** [comment]
I'm updating the issue. It's verified on master, but only seems to happen when coming from `Products to be completed`

**Comment by teolemon** [comment]
It's working for me. Closing.
