### ISSUE TITLE
App Crashed on opening Preferences from Sidebar

### ISSUE THREAD

**Issue by mrudultora** [openfoodfacts/openfoodfacts-androidapp#3614]
**Describe the bug**
App is crashing on pressing preferences in debug build of OpenFoodFacts (giving a NullPointerException). The one available on Play Store is working fine.

**To Reproduce**
1. Go to NavigationDrawer
2. Click on Preferences

**Expected behavior**
PreferencesFragment must Open.

**Additional context**
Attaching the logs...
    `2020-12-11 23:54:53.057 7921-7921/openfoodfacts.github.scrachx.openfood.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood.debug, PID: 7921
    java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter bundle
        at openfoodfacts.github.scrachx.openfood.features.PreferencesFragment.onCreatePreferences(Unknown Source:8)
        at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2936)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:273)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2177)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2088)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7548)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
`
**Smartphone Tested**
Redmi Note 7S
API 29

**Comment by teolemon** [comment]
Ok, develop crashes during app startup @VaiTon @mrudultora :-)
I'm trying a few things to make it work

**Comment by teolemon** [comment]
2020-12-25 17:17:20.466 25811-25811/? E/Finsky: [2] aftn.b(5): Failed to get status for package 'openfoodfacts.github.scrachx.openbeauty' (1601)
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at znr.run(Unknown Source:5)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.content.pm.PackageManager$NameNotFoundException: openfoodfacts

**Comment by teolemon** [comment]
```
2020-12-25 17:17:20.471 25811-25811/? E/Finsky: [2] aftn.b(5): Failed to get status for package 'openfoodfacts.github.scrachx.openfood' (1601)
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at znr.run(Unknown Source:5)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: android.content.pm.PackageManager$NameNotFoundException: openfoodfacts.github.scrachx.openfood
```

**Comment by mrudultora** [comment]
@teolemon  I am unable to understand the logs you added. I mean how to reproduce them?
