### ISSUE TITLE
App crashes at launch / : Unable to get provider openfoodfacts.github.scrachx.openfood.utils.GenericFileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3653]
```
2021-01-01 10:23:18.379 8422-8422/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood.debug, PID: 8422
    java.lang.RuntimeException: Unable to get provider openfoodfacts.github.scrachx.openfood.utils.GenericFileProvider: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
        at android.app.ActivityThread.installProvider(ActivityThread.java:7247)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6783)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6700)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalArgumentException: Missing android.support.FILE_PROVIDER_PATHS meta-data
        at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:613)
        at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
        at androidx.core.content.FileProvider.attachInfo(FileProvider.java:392)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7242)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6783) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6700) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7660) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 

```

**Comment by teolemon** [comment]
https://stackoverflow.com/questions/45973746/missing-android-support-file-provider-paths-meta-data

**Comment by kartikaysharma01** [comment]
Clean the project and run. It

**Comment by VaiTon** [comment]
I can't reproduce. Have you tried cleaning and rebuilding?

**Comment by kartikaysharma01** [comment]
cleaning and building resolves it !
