### ISSUE TITLE
Crash when sending Three products

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#376]
```12-31 17:24:15.556 2938-3191/? I/AmazonVideo: Waiting for ExperimentManager to initialize, current state NotInitialized
12-31 17:24:15.561 30786-30786/openfoodfacts.github.scrachx.openfood D/AndroidRuntime: Shutting down VM
12-31 17:24:15.562 30786-30786/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: openfoodfacts.github.scrachx.openfood, PID: 30786
                                                                                       java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
                                                                                           at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                                           at java.util.ArrayList.remove(ArrayList.java:403)
                                                                                           at openfoodfacts.github.scrachx.openfood.fragments.OfflineEditFragment$3$1.onProductSentResponse(OfflineEditFragment.java:156)
                                                                                           at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient$4.onResponse(OpenFoodAPIClient.java:239)
                                                                                           at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:66)
                                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
12-31 17:24:15.643 850-4088/? W/ActivityManager:   Force finishing activity openfoodfacts.github.scrachx.openfood/.views.MainActivity
12-31 17:24:15.742 2946-2963/? W/art: Suspending all threads took: 15.957ms
12-31 17:24:15.928 2901-2920/? W/art: Suspending all threads took: 165.935ms
12-31 17:24:16.014 850-24986/? I/OpenGLRenderer: Initialized EGL, version 1.4```

**Comment by teolemon** [comment]
```
                        apiClient.post(getActivity(), product, new OpenFoodAPIClient.OnProductSentCallback() {
                            @Override
                            public void onProductSentResponse(boolean value) {
                                if (value) {
                                    **saveItems.remove(listSaveProduct.indexOf(product));**
                                    ((SaveListAdapter) listView.getAdapter()).notifyDataSetChanged();
                                    SendProduct.deleteAll(SendProduct.class, "barcode = ?", product.getBarcode());
                                }
                            }
                        });
```

**Comment by teolemon** [comment]
```
                lt.success();
                **productSentCallback.onProductSentResponse(true);**
```
