### ISSUE TITLE
ISE - volumeUnitPreference does not exist

### ISSUE THREAD

**Issue by mrudultora** [openfoodfacts/openfoodfacts-androidapp#3769]
**Describe the bug**
When going to preferences from drawer the app crashes with `IllegalStateException`.

**Screenshots**
Attaching the logs.

> 2021-01-23 00:37:36.175 4771-4771/openfoodfacts.github.scrachx.openfood.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: openfoodfacts.github.scrachx.openfood.debug, PID: 4771
    java.lang.IllegalStateException: volumeUnitPreference preference does not exist.
        at openfoodfacts.github.scrachx.openfood.utils.PreferencesUtilsKt.requirePreference(PreferencesUtils.kt:8)
        at openfoodfacts.github.scrachx.openfood.features.PreferencesFragment.onCreatePreferences(PreferencesFragment.kt:222)
        at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2936)

**Comment by teolemon** [comment]
I can't reproduce with latest code. Can you confirm it's fixed or not ? I'm going to close it otherwise.

**Comment by mrudultora** [comment]
Unable to reproduce now!
