### ISSUE TITLE
NPE after going back from Product Browsing Activity

### ISSUE THREAD

**Issue by mrudultora** [openfoodfacts/openfoodfacts-androidapp#3827]
Attaching the logs.
```
 Caused by: java.lang.NullPointerException
        at openfoodfacts.github.scrachx.openfood.features.categories.fragment.CategoryListFragment.createComponent(CategoryListFragment.kt:99)
        at openfoodfacts.github.scrachx.openfood.features.categories.fragment.CategoryListFragment.createComponent(CategoryListFragment.kt:22)
        at openfoodfacts.github.scrachx.openfood.features.MVVMFragment$component$2.invoke(MVVMFragment.kt:10)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at openfoodfacts.github.scrachx.openfood.features.MVVMFragment.getComponent(Unknown Source:2)
        at openfoodfacts.github.scrachx.openfood.features.categories.fragment.CategoryListFragment.inject(CategoryListFragment.kt:101)
        at openfoodfacts.github.scrachx.openfood.features.MVVMFragment.onCreate(MVVMFragment.kt:16)
        at openfoodfacts.github.scrachx.openfood.features.categories.fragment.CategoryListFragment.onCreate(CategoryListFragment.kt:31)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2936)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:472)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1636)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3112)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3045)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:240)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:272)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
        at openfoodfacts.github.scrachx.openfood.features.shared.BaseActivity.onCreate(BaseActivity.kt:45)
        at openfoodfacts.github.scrachx.openfood.features.categories.activity.CategoryActivity.onCreate(CategoryActivity.kt:22)
        at android.app.Activity.performCreate(Activity.java:7893)
```

**Comment by kartikaysharma01** [comment]
@mrudultora Can you please add a video or more precise steps to reproduce.

**Comment by teolemon** [comment]
@mrudultora Can you check whether that stills happen in the beta ? Otherwise, I'm going to close

**Comment by mrudultora** [comment]
Unable to reproduce now !!!
