### ISSUE TITLE
Image selection from the image manager does not work anymore

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#3839]
https://user-images.githubusercontent.com/1689815/108596090-10851800-7383-11eb-8d3e-df9b9e2fb918.mp4

**Comment by teolemon** [comment]
Sentry Issue: [OPENFOODFACTS-ANDROID-1SW](https://sentry.io/organizations/openfoodfacts/issues/2141096632/?referrer=github_integration)

```
NullPointerException: Parameter specified as non-null is null: method kotlin.a0.e.k.e, parameter view
    at openfoodfacts.github.scrachx.openfood.features.ImagesManageActivity$onCreate$8.onItemSelected
    at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)
    at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)
    at android.widget.AdapterView.selectionChanged(AdapterView.java:935)
    at android.widget.AdapterView.checkSelectionChanged(AdapterView.java:1118)
...
(50 additional frame(s) were not displayed)
```

**Comment by teolemon** [comment]
Probably this trace

**Comment by kartikaysharma01** [comment]
Could not reproduce the issue. but making a PR, solving the stack trace.
