### ISSUE TITLE
SQL exception when opening history

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#402]
```
01-04 18:06:04.088 10074-10074/openfoodfacts.github.scrachx.openfood E/MainActivity: Error in creating fragment
01-04 18:06:04.241 10074-10074/openfoodfacts.github.scrachx.openfood E/SQLiteDatabase: Failed to open database '/data/user/0/openfoodfacts.github.scrachx.openfood/databases/offacts.db'.
                                                                                       android.database.sqlite.SQLiteException: not an error (code 0)
                                                                                           at android.database.sqlite.SQLiteConnection.nativeRegisterLocalizedCollators(Native Method)
                                                                                           at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:359)
                                                                                           at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:216)
                                                                                           at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
                                                                                           at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                                           at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                                           at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                                           at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
                                                                                           at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                                                                                           at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                                           at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:575)
                                                                                           at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:269)
                                                                                           at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
                                                                                           at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                                           at com.orm.SugarDb.getDB(SugarDb.java:38)
                                                                                           at com.orm.SugarRecord.getSugarDataBase(SugarRecord.java:35)
                                                                                           at com.orm.SugarRecord.find(SugarRecord.java:201)
                                                                                           at com.orm.SugarRecord.listAll(SugarRecord.java:127)
                                                                                           at openfoodfacts.github.scrachx.openfood.views.HistoryScanActivity$FillAdapter.onPreExecute(HistoryScanActivity.java:193)
                                                                                           at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:604)
                                                                                           at android.os.AsyncTask.execute(AsyncTask.java:551)
                                                                                           at openfoodfacts.github.scrachx.openfood.views.HistoryScanActivity.onCreate(HistoryScanActivity.java:70)
                                                                                           at android.app.Activity.performCreate(Activity.java:6251)
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
                                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-04 18:06:04.241 10074-10074/openfoodfacts.github.scrachx.openfood D/AndroidRuntime: Shutting down VM
01-04 18:06:04.242 10074-10074/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: openfoodfacts.github.scrachx.openfood, PID: 10074
                                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.HistoryScanActivity}: android.database.sqlite.SQLiteException: not an error (code 0)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2444)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
                                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                        Caused by: android.database.sqlite.SQLiteException: not an error (code 0)
                                                                                           at android.database.sqlite.SQLiteConnection.nativeRegisterLocalizedCollators(Native Method)
                                                                                           at android.database.sqlite.SQLiteConnection.setLocaleFromConfiguration(SQLiteConnection.java:359)
                                                                                           at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:216)
                                                                                           at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
                                                                                           at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                                           at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                                           at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                                           at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
                                                                                           at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                                                                                           at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                                           at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:575)
                                                                                           at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:269)
                                                                                           at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
                                                                                           at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                                           at com.orm.SugarDb.getDB(SugarDb.java:38)
                                                                                           at com.orm.SugarRecord.getSugarDataBase(SugarRecord.java:35)
                                                                                           at com.orm.SugarRecord.find(SugarRecord.java:201)
                                                                                           at com.orm.SugarRecord.listAll(SugarRecord.java:127)
                                                                                           at openfoodfacts.github.scrachx.openfood.views.HistoryScanActivity$FillAdapter.onPreExecute(HistoryScanActivity.java:193)
                                                                                           at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:604)
                                                                                           at android.os.AsyncTask.execute(AsyncTask.java:551)
                                                                                           at openfoodfacts.github.scrachx.openfood.views.HistoryScanActivity.onCreate(HistoryScanActivity.java:70)
                                                                                           at android.app.Activity.performCreate(Activity.java:6251)
                                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
                                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504) 
                                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367) 
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                           at android.os.Looper.loop(Looper.java:148) 
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5461) 
                                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

```

**Comment by herau** [comment]
what is the context of this issue please ? empty history ?

**Comment by teolemon** [comment]
Wiped the app and worked fine. The history was full. Might have been a faulty recompile ?
