### ISSUE TITLE
Crash when clicking on product in history

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#409]
Product: https://fr.openfoodfacts.org/produit/3560070323067/haricots-verts-extra-fins-carrefour

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: openfoodfacts.github.scrachx.openfood, PID: 1202
                                                 java.lang.StringIndexOutOfBoundsException: length=48; index=-1
                                                     at java.lang.String.indexAndLength(String.java:294)
                                                     at java.lang.String.substring(String.java:1067)
                                                     at openfoodfacts.github.scrachx.openfood.fragments.IngredientsProductFragment.onViewCreated(IngredientsProductFragment.java:81)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1132)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                                                     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                     at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1643)
                                                     at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
                                                     at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1272)
                                                     at android.support.v4.view.ViewPager.populate(ViewPager.java:1120)
                                                     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1646)
                                                     at android.view.View.measure(View.java:18794)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                     at android.view.View.measure(View.java:18794)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                     at android.view.View.measure(View.java:18794)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                     at android.view.View.measure(View.java:18794)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                     at android.view.View.measure(View.java:18794)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                     at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                     at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                     at android.view.View.measure(View.java:18794)
                                                     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                     at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                     at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                     at android.view.View.measure(View.java:18794)
                                                     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                                     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by itchix** [comment]
I'll fix that tomorrow

**Comment by teolemon** [comment]
here's the line where it occurs:
https://github.com/openfoodfacts/OpenFoodFacts-androidApp/blob/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/fragments/IngredientsProductFragment.java#L81

**Comment by itchix** [comment]
Can you please remove data/cache and try again? I don't have this issue..

**Comment by asmoth360** [comment]
@itchix Don't know if it's related, but this morning after the update I wanted to consult a product (via the "search by name") and it crashed when opening any product. I deleted the data/cache and it now works (I already had the issue for a previous update).

**Comment by itchix** [comment]
I don't know why, but I think Sugar ORM mess everything up each time I update the apk....

**Comment by teolemon** [comment]
Try switching to Romanian and opening "haricots verts extra fins carrefour"
