### ISSUE TITLE
Voice typing crashes the new branch

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#423]
```
FATAL EXCEPTION: main
																			                                                                               Process: openfoodfacts.github.scrachx.openfood, PID: 20195
																			                                                                               java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
 at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1832)
 at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1850)
 at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:643)
 at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:603)
 at openfoodfacts.github.scrachx.openfood.views.MainActivity.onNewIntent(MainActivity.java:535)
 at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1212)
 at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1224)
 at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:2573)
 at android.app.ActivityThread.performNewIntents(ActivityThread.java:2585)
 at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2594)
 at android.app.ActivityThread.-wrap12(ActivityThread.java)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1439)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:148)
								´											                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5461)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)


```

**Comment by teolemon** [comment]
can't reproduce.
