### ISSUE TITLE
[Bug]: App crashes with exception when attempting to open links from external apps

### ISSUE THREAD

**Issue by TimMagee** [openfoodfacts/openfoodfacts-androidapp#4356]
### Open Food Facts username

blendergeek

### What happened?

I opened a product page in Firefox and the used the "open in app" feature in the menu in firefox to view the same page in the OpenFoodFacts app. Instead of opening, I got the dreaded "OpenFoodFacts has stopped" dialog.

I expected the product page to open nicely in the OFF app.

### Steps to reproduce the behavior

1. Open a web browser that supports opening pages in other apps
2. Go to any product page on openfoodfacts.org
3. Attempt to open the page in the OFF app from the web browser.

### What device were you using ?

Moto G4

### Android Version

Android 7

### Barcode(s) of the product(s)

All

### Language your app was in

English

### Version

3.6.5 (Default)

### Flavor

Open Food Facts

### Installation method

F-Droid

### Relevant log output

```shell
FATAL EXCEPTION: main
Process: org.openfoodfacts.scanner, PID: 14844
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.openfoodfacts.scanner/openfoodfacts.github.scrachx.openfood.features.product.view.ProductViewActivity}:
java.lang.IllegalStateException: Activity ProductViewActivity started without 'state' serializable in intent.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2724)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1473)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Caused by: java.lang.IllegalStateException: Activity ProductViewActivity started without 'state' serializable in intent.
	at openfoodfacts.github.scrachx.openfood.utils.k.e(FragmentExt.kt:2)
	at openfoodfacts.github.scrachx.openfood.features.product.view.ProductViewActivity.onCreate(ProductViewActivity.kt:10)
	at android.app.Activity.performCreate(Activity.java:6672)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1140)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2612)
	... 9 more
```

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/develop/app/src/main/java/openfoodfacts/github/scrachx/openfood/features/product/view/ProductViewActivity.kt

**Comment by teolemon** [comment]
This is fixed on the Play Store, we need to release for F-Droid
