### ISSUE TITLE
App should not crash if Robotoff is down

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-androidapp#4357]
### What

- Today robotoff was down (502 from nginx). As a result the android app in last versions was crashing just after product scan. https://sentry.io/organizations/openfoodfacts/issues/2653173009/
- It did not crash on older version (eg. v 433).

### Reproduction steps

1. Shut down robotoff
2. Scan a product
3. Just after scan happens, info on product appears for a short time, then app crash and you are redirected to welcome screen.

### Expected behavior

Android app should not crash, but just handle the 502 silently, not displaying any robotoff question.

**Comment by teolemon** [comment]
Following an error on Robotoff which returned 502

Sentry Issue: [OPENFOODFACTS-ANDROID-4GJ](https://sentry.io/organizations/openfoodfacts/issues/2653173009/?referrer=github_integration)

```
HttpException: HTTP 502 
    at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
    at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
    at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:47)
    at io.reactivex.Observable.subscribe(Observable.java:12284)
    at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
...
(10 additional frame(s) were not displayed)
```

**Comment by teolemon** [comment]
Sentry Issue: [OPENFOODFACTS-ANDROID-4F5](https://sentry.io/organizations/openfoodfacts/issues/2638887200/?referrer=github_integration)

```
GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
    at libcore.io.Linux.android_getaddrinfo(Linux.java)
    at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
    at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
    at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
    at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
...
(39 additional frame(s) were not displayed)

UnknownHostException: Unable to resolve host "robotoff.openfoodfacts.org": No address associated with hostname
    at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
    at java.net.InetAddress.getAllByName(InetAddress.java:1152)
    at okhttp3.Dns$1.lookup(Dns.java:40)
    at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
...
(35 additional frame(s) were not displayed)
```
