### ISSUE TITLE
App crashes when opening offline edit before any product has been added

### ISSUE THREAD

**Issue by friedger** [openfoodfacts/OpenFoodFacts-androidApp#44]
```
FATAL EXCEPTION: main
Process: openfoodfacts.github.scrachx.openfood, PID: 24844
android.database.sqlite.SQLiteException: no such table: SEND_PRODUCT (code 1): , while compiling: SELECT * FROM SEND_PRODUCT
   at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
   at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:891)
   at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:502)
   at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
   at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
   at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
   at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
   at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
   at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
   at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
   at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1240)
   at com.orm.SugarRecord.find(SugarRecord.java:201)
   at com.orm.SugarRecord.listAll(SugarRecord.java:127)
   at openfoodfacts.github.scrachx.openfood.fragments.OfflineEditFragment$FillAdapter.onPreExecute(OfflineEditFragment.java:188)
   at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:591)
   at android.os.AsyncTask.execute(AsyncTask.java:539)
   at openfoodfacts.github.scrachx.openfood.fragments.OfflineEditFragment.onResume(OfflineEditFragment.java:181)
   at android.app.Fragment.performResume(Fragment.java:2096)
   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:928)
   at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
   at android.app.BackStackRecord.run(BackStackRecord.java:834)
   at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
   at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:135)
   at android.app.ActivityThread.main(ActivityThread.java:5294)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by friedger** [comment]
I think that this is blocked by https://github.com/satyan/sugar/issues/582

**Comment by itchix** [comment]
Yes, but I don't know why, it doesn't fix it... I had to change the name of the database, number version and then it works.... But we lose all offline datas.

**Comment by friedger** [comment]
It looks like it is only an issue in debug. Disabling instant on the first
run should fix it. The reason is that the apk has a different location for
the dexed classes when using instant run. These dexed classes are needed to
create the tables.
