### ISSUE TITLE
java.lang.RuntimeException: cancelAutoFocus failed java.lang.RuntimeException: cancelAutoFocus failed

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#443]
```
01-12 12:02:34.965 848-861/? W/ActivityManager: Activity pause timeout for ActivityRecord{d61980f u0 openfoodfacts.github.scrachx.openfood/.views.ScannerFragmentActivity t27129}
01-12 12:02:35.367 11221-11221/? E/CameraPreview: java.lang.RuntimeException: cancelAutoFocus failed java.lang.RuntimeException: cancelAutoFocus failed
at android.hardware.Camera.native_cancelAutoFocus(Native Method)
at android.hardware.Camera.cancelAutoFocus(Camera.java:1275)
at me.dm7.barcodescanner.core.CameraPreview.stopCameraPreview(CameraPreview.java:115)
at me.dm7.barcodescanner.core.BarcodeScannerView.stopCamera(BarcodeScannerView.java:102)
at openfoodfacts.github.scrachx.openfood.fragments.BarCodeScannerFragment.onPause(BarCodeScannerFragment.java:220)
at android.support.v4.app.Fragment.performPause(Fragment.java:2363)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1354)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1523)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1585)
at android.support.v4.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:2846)
at android.support.v4.app.FragmentController.dispatchPause(FragmentController.java:234)
at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:448)
at android.app.Activity.performPause(Activity.java:6363)
at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1311)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3395)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3368)
at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3343)
at android.app.ActivityThread.-wrap13(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
01-12 12:02:36.353 317-4192/? I/CameraService: CameraService::connect call (PID 11221 "openfoodfacts.github.scrachx.openfood", camera ID 0) for HAL version default and Camera API version 1
01-12 12:02:36.599 11221-11221/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: openfoodfacts.github.scrachx.openfood, PID: 11221
java.lang.RuntimeException: getParameters failed (empty parameters)
 at android.hardware.Camera.native_getParameters(Native Method)
 at android.hardware.Camera.getParameters(Camera.java:1890)
 at me.dm7.barcodescanner.core.CameraUtils.isFlashSupported(CameraUtils.java:47)
 at me.dm7.barcodescanner.core.BarcodeScannerView.setFlash(BarcodeScannerView.java:153)
 at me.dm7.barcodescanner.core.BarcodeScannerView.setupCameraPreview(BarcodeScannerView.java:90)
 at me.dm7.barcodescanner.core.CameraHandlerThread$1$1.run(CameraHandlerThread.java:31)
 at android.os.Handler.handleCallback(Handler.java:739)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:148)
 at android.app.ActivityThread.main(ActivityThread.java:5461)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by huzaifaiftikhar** [comment]
We don't use this library anymore. Closing the issue.
