### ISSUE TITLE
A NPE is triggered if the search Activity is left

### ISSUE THREAD

**Issue by g123k** [openfoodfacts/openfoodfacts-androidapp#4571]
Stacktrace:

```
    java.lang.NullPointerException
        at openfoodfacts.github.scrachx.openfood.features.search.ProductSearchActivity.getBinding(ProductSearchActivity.kt:58)
        at openfoodfacts.github.scrachx.openfood.features.search.ProductSearchActivity.showOfflineCloud(ProductSearchActivity.kt:430)
        at openfoodfacts.github.scrachx.openfood.features.search.ProductSearchActivity.displaySearch(ProductSearchActivity.kt:476)
        at openfoodfacts.github.scrachx.openfood.features.search.ProductSearchActivity.access$displaySearch(ProductSearchActivity.kt:55)
        at openfoodfacts.github.scrachx.openfood.features.search.ProductSearchActivity$startSearch$1.invokeSuspend(ProductSearchActivity.kt:369)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by g123k** [comment]
Ooops sorry this one is actually a duplicate of https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/4559
