### ISSUE TITLE
Resources not found

### ISSUE THREAD

**Issue by itchix** [openfoodfacts/OpenFoodFacts-androidApp#463]
``` 
java.lang.RuntimeException: Unable to start activity ComponentInfo{openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.MainActivity}: android.content.res.Resources$NotFoundException: File res/drawable/ic_arrow_back_black.xml from drawable resource ID #0x7f020069
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2439)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
	at android.app.ActivityThread.access$800(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5633)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_arrow_back_black.xml from drawable resource ID #0x7f020069
	at android.content.res.Resources.loadDrawable(Resources.java:2141)
	at android.content.res.Resources.getDrawable(Resources.java:711)
	at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
	at openfoodfacts.github.scrachx.openfood.utils.Utils.getBitmapFromDrawable(Utils.java:218)
	at openfoodfacts.github.scrachx.openfood.views.customtabs.CustomTabsHelper.getCustomTabsIntent(CustomTabsHelper.java:67)
	at openfoodfacts.github.scrachx.openfood.views.MainActivity.onCreate(MainActivity.java:114)
	at android.app.Activity.performCreate(Activity.java:5312)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2395)
	... 11 more
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
	at android.content.res.Resources.loadDrawable(Resources.java:2137)
	... 19 more
```

**Comment by herau** [comment]
not reproductible on the master branch (the resource `ic_arrow_back_black.xml` doesn't not exist anymore)
