### ISSUE TITLE
Chrome missing: ActivityNotFoundException

### ISSUE THREAD

**Issue by itchix** [openfoodfacts/openfoodfacts-androidapp#464]
```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW pkg=com.android.chrome (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1798)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1512)
	at android.app.Activity.startActivityForResult(Activity.java:3930)
	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
	at android.app.Activity.startActivityForResult(Activity.java:3890)
	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
	at android.app.Activity.startActivity(Activity.java:4213)
	at android.support.v4.content.ContextCompatJellybean.startActivity(ContextCompatJellybean.java:34)
	at android.support.v4.content.ContextCompat.startActivity(ContextCompat.java:151)
	at android.support.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:262)
	at openfoodfacts.github.scrachx.openfood.views.customtabs.CustomTabActivityHelper.openCustomTab(CustomTabActivityHelper.java:57)
	at openfoodfacts.github.scrachx.openfood.views.MainActivity$1.onProfileChanged(MainActivity.java:127)
	at com.mikepenz.materialdrawer.AccountHeaderBuilder$7.onItemClick(AccountHeaderBuilder.java:1423)
	at com.mikepenz.materialdrawer.DrawerBuilder$5.onClick(DrawerBuilder.java:1716)
	at com.mikepenz.materialdrawer.DrawerBuilder$5.onClick(DrawerBuilder.java:1690)
	at com.mikepenz.fastadapter.FastAdapter$1.onClick(FastAdapter.java:492)
	at android.view.View.performClick(View.java:5204)
	at android.view.View$PerformClick.run(View.java:21153)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by herau** [comment]
no chrome on the device ?

**Comment by teolemon** [comment]
This looks like it. 
Best practises for Chrome Custom Tabs : https://developer.chrome.com/multidevice/android/customtabs#bestpractices

**Comment by teolemon** [comment]
Inactive and probably fixed. Closing.
