### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'com.fasterxml.jackson.databind.JsonNode 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/OpenFoodFacts-androidApp#465]
```
01-15 19:54:43.567 20140-20140/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: openfoodfacts.github.scrachx.openfood, PID: 20140
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'com.fasterxml.jackson.databind.JsonNode com.fasterxml.jackson.databind.JsonNode.get(java.lang.String)' on a null object reference
                                                       at openfoodfacts.github.scrachx.openfood.network.OpenFoodAPIClient$6.onResponse(OpenFoodAPIClient.java:416)
                                                       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:66)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by herau** [comment]
@teolemon how to reproduce please ?

**Comment by herau** [comment]
@teolemon i'm interesting about the context to reproduce for this issue
