### ISSUE TITLE
E/WindowManager: android.view.WindowLeaked: Activity openfoodfacts.github.scrachx.openfood.views.SaveProductOfflineActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#466]
```
01-15 19:53:49.511 20140-20140/? E/WindowManager: android.view.WindowLeaked: Activity openfoodfacts.github.scrachx.openfood.views.SaveProductOfflineActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{4946416 V.E...... R.....ID 0,0-720,467} that was originally added here
at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
at android.app.Dialog.show(Dialog.java:319)
at com.afollestad.materialdialogs.MaterialDialog.show(MaterialDialog.java:1466)
at com.afollestad.materialdialogs.MaterialDialog$Builder.show(MaterialDialog.java:1457)
at openfoodfacts.github.scrachx.openfood.views.SaveProductOfflineActivity.onCreate(SaveProductOfflineActivity.java:156)
at android.app.Activity.performCreate(Activity.java:6251)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2397)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4105)
at android.app.ActivityThread.-wrap15(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5461)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)```

**Comment by herau** [comment]
information about your use case are welcome :-)

**Comment by teolemon** [comment]
I've managed to reproduce it more of less in the last bug about disappearing images. At least it appears in the scenario I've described.

**Comment by teolemon** [comment]
closing as very old. thanks @herau
