### ISSUE TITLE
I/HISTORY: unable to get the history product image   java.net.MalformedURLException

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#475]
```
I/HISTORY: unable to get the history product image
    java.net.MalformedURLException
    at java.net.URL.<init>(URL.java:152)
    at java.net.URL.<init>(URL.java:125)
    at openfoodfacts.github.scrachx.openfood.views.HistoryScanActivity$FillAdapter.doInBackground(HistoryScanActivity.java:207)
    at openfoodfacts.github.scrachx.openfood.views.HistoryScanActivity$FillAdapter.doInBackground(HistoryScanActivity.java:197)
    at android.os.AsyncTask$2.call(AsyncTask.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by teolemon** [comment]
This one is most likely fixed by using the new API
