### ISSUE TITLE
Ruby is blocking release

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#4878]
### What
are replacing the current local value of deployment, which is currently nil
  Cache key: setup-ruby-bundler-cache-v4-ubuntu-20.04-ruby-2.3.1-Gemfile.lock-a526[36](https://github.com/openfoodfacts/openfoodfacts-androidapp/actions/runs/3445176944/jobs/5748685122#step:4:42)cc9fdc569ab7f58496613fd167aef61b7885ceaad309e8b4ee9cda4d7a
  /opt/hostedtoolcache/Ruby/2.3.1/x64/bin/bundle install --jobs 4
  You must use Bundler 2 or greater with this lockfile.
  Took   0.88 seconds
Error: Error: The process '/opt/hostedtoolcache/Ruby/2.3.1/x64/bin/bundle' failed with exit code 20
    at ExecState._setResult (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5334:25)
    at ExecState.CheckComplete (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5317:18)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:5211:27)
    at ChildProcess.emit (node:events:[39](https://github.com/openfoodfacts/openfoodfacts-androidapp/actions/runs/3445176944/jobs/5748685122#step:4:45)0:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)

**Comment by VaiTon** [comment]
Where did you find this log? @teolemon

**Comment by teolemon** [comment]
Can't reproduce. Closing as a result
