### ISSUE TITLE
Crash while swiping on 3274490972988

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#539]
```android.content.res.Resources$NotFoundException: File res/drawable-hdpi-v4/error_image.png from xml type xml resource ID #0x7f020064
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2899)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2854)
	at android.content.res.Resources.getXml(Resources.java:1236)
	at android.support.graphics.drawable.VectorDrawableCompat.create(Unknown Source)
	at openfoodfacts.github.scrachx.openfood.views.adapters.NutrientLevelListAdapter.getView(Unknown Source)
	at android.widget.AbsListView.obtainView(AbsListView.java:2346)
	at android.widget.ListView.onMeasure(ListView.java:1158)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
	at android.view.View.measure(View.java:18794)
	at android.support.v4.widget.NestedScrollView.measureChildWithMargins(Unknown Source)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.support.v4.widget.NestedScrollView.onMeasure(Unknown Source)
	at android.view.View.measure(View.java:18794)
	at android.support.v4.view.ViewPager.onMeasure(Unknown Source)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.support.design.widget.CoordinatorLayout.onMeasureChild(Unknown Source)
	at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(Unknown Source)
	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(Unknown Source)
	at android.support.design.widget.CoordinatorLayout.onMeasure(Unknown Source)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.support.v7.widget.ContentFrameLayout.onMeasure(Unknown Source)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
	at android.view.View.measure(View.java:18794)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.io.FileNotFoundException: Corrupt XML binary file
	at android.content.res.AssetManager.openXmlAssetNative(Native Method)
	at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:495)
	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2881)
	... 61 more```

**Comment by teolemon** [comment]
```04-04 11:32:25.179 23723-23723/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: openfoodfacts.github.scrachx.openfood, PID: 23723
                                                                                       android.content.res.Resources$NotFoundException: File res/drawable-hdpi-v4/error_image.png from xml type xml resource ID #0x7f020064
                                                                                           at android.content.res.Resources.loadXmlResourceParser(Resources.java:2899)
                                                                                           at android.content.res.Resources.loadXmlResourceParser(Resources.java:2854)
                                                                                           at android.content.res.Resources.getXml(Resources.java:1236)
                                                                                           at android.support.graphics.drawable.VectorDrawableCompat.create(VectorDrawableCompat.java:586)
                                                                                           at openfoodfacts.github.scrachx.openfood.views.adapters.NutrientLevelListAdapter.getView(NutrientLevelListAdapter.java:60)
                                                                                           at android.widget.AbsListView.obtainView(AbsListView.java:2346)
                                                                                           at android.widget.ListView.onMeasure(ListView.java:1158)
                                                                                           at android.view.View.measure(View.java:18794)
                                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                           at android.view.View.measure(View.java:18794)
                                                                                           at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1420)
                                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                           at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:482)
                                                                                           at android.view.View.measure(View.java:18794)
                                                                                           at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1658)
                                                                                           at android.view.View.measure(View.java:18794)
                                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                           at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
                                                                                           at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
                                                                                           at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1375)
                                                                                           at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:784)
                                                                                           at android.view.View.measure(View.java:18794)
                                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                           at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
                                                                                           at android.view.View.measure(View.java:18794)
                                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                           at android.view.View.measure(View.java:18794)
                                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                           at android.view.View.measure(View.java:18794)
                                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                           at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                           at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                           at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                           at android.view.View.measure(View.java:18794)
                                                                                           at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                                           at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                           at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                                           at android.view.View.measure(View.java:18794)
                                                                                           at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                                                                           at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
                                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
                                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                           at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                       	at android.view```
