### ISSUE TITLE
different use case to make OBF/OPFF/OFF crash

### ISSUE THREAD

**Issue by Jibec** [openfoodfacts/openfoodfacts-androidapp#574]
hi there,

a few weeks ago, versions bigger than 0.4 didn't run at all.
Now, with the version 7.xx, it does:
 * run,
 * scan,
 * add unknown items

Before running test, I clean application data.
I go to OBF search page, type "a", open first ingredient, go ingredient tab, it works.
I go to OPFF search page, type "a", open first ingredient, go ingredient tab, it **crashes**.
I go to OFF search page, type "a", open first ingredient, go ingredient tab, it works.

I go to OBF login, it show the form, I quit.
I go to OPFF login, it show the form, I quit.
I go to OFF login, it **crashes**.

I go to OBF login, it show the form, I connect, it works and I see my username in the side panel.
I go to OPFF login, it show the form, I connect, it works by I don't see my username in the side panel, instead I see anonymous, but it still shows one previous contribution (3222270494083) which isn't mine (I have none with this login).
I go to OFF login, it **crashes**.

thanks for your help

NB: I use the same login/password in all apps.

**Comment by teolemon** [comment]
@Jibec Any way you can provide traces of the bug ?

**Comment by Jibec** [comment]
is this of any help? This is the log from OPFF when going to the ingredients menu.

```
jean-baptiste  ~  adb logcat "*:E"
--------- beginning of /dev/log/main
--------- beginning of /dev/log/system
E/AudioMTKHardware(  985): setParameters() still have param.size() = 1, remain param = "screen_state=on"
E/CellLocation( 1272): create GsmCellLocation
E/CellLocation( 1272): create GsmCellLocation
E/CellLocation( 1272): create GsmCellLocation
E/RecyclerView( 6952): No adapter attached; skipping layout
E/RecyclerView( 6952): No adapter attached; skipping layout
E/NativeCrypto( 6952): ssl=0x60412a48 cert_verify_callback x509_store_ctx=0x60604ab0 arg=0x0
E/NativeCrypto( 6952): ssl=0x60412a48 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
E/CellLocation( 1272): create GsmCellLocation
E/CellLocation( 1272): create GsmCellLocation
E/CellLocation( 1272): create GsmCellLocation
E/AndroidRuntime( 6952): FATAL EXCEPTION: main
E/AndroidRuntime( 6952): android.content.res.Resources$NotFoundException: File res/drawable-hdpi-v4/error_image.png from xml type xml resource ID #0x7f020064. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
E/AndroidRuntime( 6952): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2226)
E/AndroidRuntime( 6952): 	at android.content.res.Resources.loadXmlResourceParser(Resources.java:2181)
E/AndroidRuntime( 6952): 	at android.content.res.Resources.getXml(Resources.java:921)
E/AndroidRuntime( 6952): 	at android.support.graphics.drawable.VectorDrawableCompat.create(Unknown Source)
E/AndroidRuntime( 6952): 	at openfoodfacts.github.scrachx.openfood.views.adapters.NutrientLevelListAdapter.getView(Unknown Source)
E/AndroidRuntime( 6952): 	at android.widget.AbsListView.obtainView(AbsListView.java:2207)
E/AndroidRuntime( 6952): 	at android.widget.ListView.onMeasure(ListView.java:1134)
E/AndroidRuntime( 6952): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime( 6952): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
E/AndroidRuntime( 6952): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1411)
E/AndroidRuntime( 6952): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:698)
E/AndroidRuntime( 6952): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
E/AndroidRuntime( 6952): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime( 6952): 	at android.support.v4.widget.NestedScrollView.measureChildWithMargins(Unknown Source)
E/AndroidRuntime( 6952): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime( 6952): 	at android.support.v4.widget.NestedScrollView.onMeasure(Unknown Source)
E/AndroidRuntime( 6952): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime( 6952): 	at android.support.v4.view.ViewPager.onMeasure(Unknown Source)
E/AndroidRuntime( 6952): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime( 6952): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
E/AndroidRuntime( 6952): 	at android.support.design.widget.CoordinatorLayout.onMeasureChild(Unknown Source)
E/AndroidRuntime( 6952): 	at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(Unknown Source)
E/AndroidRuntime( 6952): 	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(Unknown Source)
E/AndroidRuntime( 6952): 	at android.support.design.widget.CoordinatorLayout.onMeasure(Unknown Source)
E/AndroidRuntime( 6952): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime( 6952): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
E/AndroidRuntime( 6952): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime( 6952): 	at android.support.v7.widget.ContentFrameLayout.onMeasure(Unknown Source)
E/AndroidRuntime( 6952): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime( 6952): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
E/AndroidRuntime( 6952): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1411)
E/AndroidRuntime( 6952): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:698)
E/AndroidRuntime( 6952): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
E/AndroidRuntime( 6952): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime( 6952): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
E/AndroidRuntime( 6952): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime( 6952): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime( 6952): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
E/AndroidRuntime( 6952): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1411)
E/AndroidRuntime( 6952): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:698)
E/AndroidRuntime( 6952): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
E/AndroidRuntime( 6952): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime( 6952): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
E/AndroidRuntime( 6952): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
E/AndroidRuntime( 6952): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2191)
E/AndroidRuntime( 6952): 	at android.view.View.measure(View.java:15609)
E/AndroidRuntime( 6952): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2165)
E/AndroidRuntime( 6952): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1249)
E/AndroidRuntime( 6952): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1443)
E/AndroidRuntime( 6952): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
E/AndroidRuntime( 6952): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4879)
E/AndroidRuntime( 6952): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
E/AndroidRuntime( 6952): 	at android.view.Choreographer.doCallbacks(Choreographer.java:579)
E/AndroidRuntime( 6952): 	at android.view.Choreographer.doFrame(Choreographer.java:548)
E/AndroidRuntime( 6952): 	at android.v
E/AppErrorDialog( 1272): Failed to get ILowStorageHandle instance

```

**Comment by teolemon** [comment]
Looks like: https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/571

**Comment by teolemon** [comment]
I'd be interested in the Login Bug. Can you trace it ?

**Comment by Jibec** [comment]
Here it is for the OFF login bug:

```
E/MainActivity(19685): Error in creating fragment
E/AndroidRuntime(19685): FATAL EXCEPTION: main
E/AndroidRuntime(19685): java.lang.RuntimeException: Unable to start activity ComponentInfo{openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.LoginActivity}: android.view.InflateException: Binary XML file line #22: Error inflating class EditText
E/AndroidRuntime(19685): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2306)
E/AndroidRuntime(19685): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358)
E/AndroidRuntime(19685): 	at android.app.ActivityThread.access$600(ActivityThread.java:156)
E/AndroidRuntime(19685): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
E/AndroidRuntime(19685): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19685): 	at android.os.Looper.loop(Looper.java:153)
E/AndroidRuntime(19685): 	at android.app.ActivityThread.main(ActivityThread.java:5299)
E/AndroidRuntime(19685): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(19685): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(19685): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
E/AndroidRuntime(19685): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
E/AndroidRuntime(19685): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(19685): Caused by: android.view.InflateException: Binary XML file line #22: Error inflating class EditText
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
E/AndroidRuntime(19685): 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(Unknown Source)
E/AndroidRuntime(19685): 	at android.support.v7.app.AppCompatActivity.setContentView(Unknown Source)
E/AndroidRuntime(19685): 	at openfoodfacts.github.scrachx.openfood.views.BaseActivity.setContentView(Unknown Source)
E/AndroidRuntime(19685): 	at openfoodfacts.github.scrachx.openfood.views.LoginActivity.onCreate(Unknown Source)
E/AndroidRuntime(19685): 	at android.app.Activity.performCreate(Activity.java:5122)
E/AndroidRuntime(19685): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
E/AndroidRuntime(19685): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
E/AndroidRuntime(19685): 	... 11 more
E/AndroidRuntime(19685): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_person_grey_24dp.xml from drawable resource ID #0x7f020095
E/AndroidRuntime(19685): 	at android.content.res.Resources.loadDrawable(Resources.java:1993)
E/AndroidRuntime(19685): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
E/AndroidRuntime(19685): 	at android.widget.TextView.<init>(TextView.java:760)
E/AndroidRuntime(19685): 	at android.widget.EditText.<init>(EditText.java:60)
E/AndroidRuntime(19685): 	at android.support.v7.widget.AppCompatEditText.<init>(Unknown Source)
E/AndroidRuntime(19685): 	at android.support.v7.widget.AppCompatEditText.<init>(Unknown Source)
E/AndroidRuntime(19685): 	at android.support.v7.app.AppCompatViewInflater.createView(Unknown Source)
E/AndroidRuntime(19685): 	at android.support.v7.app.AppCompatDelegateImplV9.createView(Unknown Source)
E/AndroidRuntime(19685): 	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(Unknown Source)
E/AndroidRuntime(19685): 	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(Unknown Source)
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675)
E/AndroidRuntime(19685): 	... 24 more
E/AndroidRuntime(19685): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
E/AndroidRuntime(19685): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
E/AndroidRuntime(19685): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
E/AndroidRuntime(19685): 	at android.content.res.Resources.loadDrawable(Resources.java:1990)
E/AndroidRuntime(19685): 	... 34 more
E/AppErrorDialog( 1272): Failed to get ILowStorageHandle instance
```

**Comment by teolemon** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/issues/578 has been opened. 
The other one looks like: #571

Closing this meta bug ? @Jibec

**Comment by Jibec** [comment]
I would like to say yes, but there is still one more use case to investigate here. I propose to wait for the resolution of the two existing bugs, and to try to reproduce the last bug. If it still exists, we'll have to investigate more, if not well close this ticket, OK ?

**Comment by sachincool** [comment]
@teolemon  this one can be closed. i think
