### ISSUE TITLE
Crash on the login page due to missing PNG fallback

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#578]
Reported by @jibec
```
E/MainActivity(19685): Error in creating fragment
E/AndroidRuntime(19685): FATAL EXCEPTION: main
E/AndroidRuntime(19685): java.lang.RuntimeException: Unable to start activity ComponentInfo{openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.LoginActivity}: android.view.InflateException: Binary XML file line #22: Error inflating class EditText
E/AndroidRuntime(19685): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2306)
E/AndroidRuntime(19685): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2358)
E/AndroidRuntime(19685): 	at android.app.ActivityThread.access$600(ActivityThread.java:156)
E/AndroidRuntime(19685): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340)
E/AndroidRuntime(19685): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19685): 	at android.os.Looper.loop(Looper.java:153)
E/AndroidRuntime(19685): 	at android.app.ActivityThread.main(ActivityThread.java:5299)
E/AndroidRuntime(19685): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(19685): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(19685): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
E/AndroidRuntime(19685): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
E/AndroidRuntime(19685): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(19685): Caused by: android.view.InflateException: Binary XML file line #22: Error inflating class EditText
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
E/AndroidRuntime(19685): 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(Unknown Source)
E/AndroidRuntime(19685): 	at android.support.v7.app.AppCompatActivity.setContentView(Unknown Source)
E/AndroidRuntime(19685): 	at openfoodfacts.github.scrachx.openfood.views.BaseActivity.setContentView(Unknown Source)
E/AndroidRuntime(19685): 	at openfoodfacts.github.scrachx.openfood.views.LoginActivity.onCreate(Unknown Source)
E/AndroidRuntime(19685): 	at android.app.Activity.performCreate(Activity.java:5122)
E/AndroidRuntime(19685): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
E/AndroidRuntime(19685): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
E/AndroidRuntime(19685): 	... 11 more
E/AndroidRuntime(19685): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_person_grey_24dp.xml from drawable resource ID #0x7f020095
E/AndroidRuntime(19685): 	at android.content.res.Resources.loadDrawable(Resources.java:1993)
E/AndroidRuntime(19685): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
E/AndroidRuntime(19685): 	at android.widget.TextView.<init>(TextView.java:760)
E/AndroidRuntime(19685): 	at android.widget.EditText.<init>(EditText.java:60)
E/AndroidRuntime(19685): 	at android.support.v7.widget.AppCompatEditText.<init>(Unknown Source)
E/AndroidRuntime(19685): 	at android.support.v7.widget.AppCompatEditText.<init>(Unknown Source)
E/AndroidRuntime(19685): 	at android.support.v7.app.AppCompatViewInflater.createView(Unknown Source)
E/AndroidRuntime(19685): 	at android.support.v7.app.AppCompatDelegateImplV9.createView(Unknown Source)
E/AndroidRuntime(19685): 	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(Unknown Source)
E/AndroidRuntime(19685): 	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(Unknown Source)
E/AndroidRuntime(19685): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675)
E/AndroidRuntime(19685): 	... 24 more
E/AndroidRuntime(19685): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
E/AndroidRuntime(19685): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
E/AndroidRuntime(19685): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
E/AndroidRuntime(19685): 	at android.content.res.Resources.loadDrawable(Resources.java:1990)
E/AndroidRuntime(19685): 	... 34 more
E/AppErrorDialog( 1272): Failed to get ILowStorageHandle instance

```

**Comment by mikini** [comment]
I got something similar with OFF v0.7.4 from F-Droid on a Stock Samsung SIII (GT-I9305) running Android 4.4.4. Monitoring press on "Sign-in" yields:
```
shell@m3:/ $ am monitor                                                        
Monitoring activity manager...  available commands:
(q)uit: finish monitoring
** Activity starting: openfoodfacts.github.scrachx.openfood
** Activity starting: openfoodfacts.github.scrachx.openfood
** Activity resuming: openfoodfacts.github.scrachx.openfood
** Activity starting: openfoodfacts.github.scrachx.openfood
** ERROR: PROCESS CRASHED
processName: openfoodfacts.github.scrachx.openfood
processPid: 16229
shortMsg: org.xmlpull.v1.XmlPullParserException
longMsg: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
timeMillis: 1505416776234
stack:
java.lang.RuntimeException: Unable to start activity ComponentInfo{openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.LoginActivity}: android.view.InflateException: Binary XML file line #22: Error inflating class EditText
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2441)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2500)
	at android.app.ActivityThread.access$900(ActivityThread.java:171)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1309)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5679)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #22: Error inflating class EditText
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:719)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(Unknown Source)
	at android.support.v7.app.AppCompatActivity.setContentView(Unknown Source)
	at openfoodfacts.github.scrachx.openfood.views.BaseActivity.setContentView(Unknown Source)
	at openfoodfacts.github.scrachx.openfood.views.LoginActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:5582)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2405)
	... 11 more
Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_person_grey_24dp.xml from drawable resource ID #0x7f020095
	at android.content.res.Resources.loadDrawable(Resources.java:3439)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
	at android.widget.TextView.<init>(TextView.java:1319)
	at android.widget.EditText.<init>(EditText.java:79)
	at android.support.v7.widget.AppCompatEditText.<init>(Unknown Source)
	at android.support.v7.widget.AppCompatEditText.<init>(Unknown Source)
	at android.support.v7.app.AppCompatViewInflater.createView(Unknown Source)
	at android.support.v7.app.AppCompatDelegateImplV9.createView(Unknown Source)
	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(Unknown Source)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(Unknown Source)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:690)
	... 24 more
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:986)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:930)
	at android.content.res.Resources.loadDrawable(Resources.java:3435)
	... 34 more
#
```
Device info:
```
shell@m3:/ $ getprop|grep ro.product                                           
[ro.product.board]: [smdk4x12]
[ro.product.brand]: [samsung]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.device]: [m3]
[ro.product.locale.language]: [en]
[ro.product.locale.region]: [GB]
[ro.product.manufacturer]: [samsung]
[ro.product.model]: [GT-I9305]
[ro.product.name]: [m3xx]
[ro.product_ship]: [true]
shell@m3:/ $ getprop|grep build.version                                        
[ro.build.version.base_os]: []
[ro.build.version.codename]: [REL]
[ro.build.version.incremental]: [I9305XXSFQD1]
[ro.build.version.release]: [4.4.4]
[ro.build.version.sdk]: [19]
[ro.build.version.security_patch]: []
```
I can do some diagnostics if needed. Planning on putting an alternative Android on it soon, though.

**Comment by mikini** [comment]
Digging for "invalid drawable tag vector" lead me to [this stackoverflow comment](https://stackoverflow.com/a/45397767/4782539) which smells like something similar.

I guess the openfoodfacts.github.scrachx.openfood.utils.CustomEditTextView class used by the login form in app/src/main/res/layout/activity_login.xml is based on TextView. And the only reference to ic_person_grey_24dp I found (in master branch or tag 0.7.4) is fromthere. Seems like this was also code added in the last commit on the 0.7.4 tag (in 8109cb40e5d1b0f30b1072417ab6b14e236ca062).

**Comment by teolemon** [comment]
@mikini Can you try with latest trunk ?

**Comment by mikini** [comment]
@teolemon I'm sad to say that this device is now serving in the duty of the eternal bricklayer. At some point I might be able to put together a working 9305 from parts but I can't promise when.

**Comment by jaztriumph** [comment]
@Karljoones Did you find a solution? if you are not working on this, I would like to take up on this.
