### ISSUE TITLE
The categories view stays stuck on "Loading…"

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#677]
```

01-18 15:34:58.233 2005-2030/openfoodfacts.github.scrachx.openfood D/OpenGLRenderer: endAllActiveAnimators on 0x7426b5bc00 (StateListDrawable) with handle 0x74362ea720
01-18 15:35:08.362 2005-12890/openfoodfacts.github.scrachx.openfood E/openfoodfacts.github.scrachx.openfood.views.viewmodel.category.CategoryFragmentViewModel: Error loading categories
java.net.SocketTimeoutException: timeout
at okio.Okio$4.newTimeoutException(Okio.java:230)
at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187)
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
at okhttp3.RealCall.execute(RealCall.java:77)
at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
at io.reactivex.Observable.subscribe(Observable.java:10981)
at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
at io.reactivex.Observable.subscribe(Observable.java:10981)
at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.net.SocketException: socket is closed
at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
at okio.Okio$2.read(Okio.java:139)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345) 
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217) 
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211) 
at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187) 
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88) 
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) 
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) 
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) 
at okhttp3.RealCall.execute(RealCall.java:77) 
at retrofit2.OkHttpCall.execute(OkHttpCall.java:180) 
at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41) 
at io.reactivex.Observable.subscribe(Observable.java:10981) 
at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34) 
at io.reactivex.Observable.subscribe(Observable.java:10981) 
at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96) 
at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452) 
at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
at java.lang.Thread.run(Thread.java:764) 

```

**Comment by teolemon** [comment]
Poke @alikyo

**Comment by policorn** [comment]
OFF is using OkHttpClient 3.9.0. It uses a default read timeout of 10secs. The categories.json takes about that time to get rendered in the server (I guess it is not being cached* and the query is being executed on every "categories list" query hitting the server). Download effective time is ~1.6secs (over 5G wifi and 400mbps downlink). 

Implementing OkHttpClient read timeout allows the download process to finish and the future queries are read from the local cache. 

I've also have increased the OFF API Client timeouts just in case other long pulling queries might also be affected.  

(*) Are we running some cache in front of Nginx? i.e. Varnish? 

- - - 

Tests and references:

```
$ time wget --progress=dot -v -N -O /tmp/categories.json  https://world.openfoodfacts.org/categories.json
  WARNING: timestamping does nothing in combination with -O. See the manual
  for details.

  --2018-02-09 17:32:54--  https://world.openfoodfacts.org/categories.json
  Resolving world.openfoodfacts.org... 178.33.252.125
  Connecting to world.openfoodfacts.org|178.33.252.125|:443... connected.
  HTTP request sent, awaiting response... 200 OK
  Length: unspecified [application/json]
  Saving to: '/tmp/categories.json'

     0K .......... .......... .......... .......... .......... 2.08M
    50K .......... .......... .......... .......... .......... 1.94M
   100K .......... .......... .......... .......... .......... 2.02M
   ...
   2900K .......... .......... .......... .......... ..........  121M
   2950K .......... .......... ........                         2.27M=1.6s

  2018-02-09 17:33:07 (1.76 MB/s) - '/tmp/categories.json' saved [3049538]

  wget --progress=dot -v -N -O /tmp/categories.json   0.03s user 0.04s system 0% cpu 12.530 total

```
https://github.com/square/okhttp/blob/51663fd08f1670c5d55fdc5b8b0bd5e326054a4e/okhttp/src/main/java/okhttp3/OkHttpClient.java#L491

```
public class OkHttpClient implements Cloneable, Call.Factory, WebSocket.Factory {
...
  public Builder() {
  ...
    connectTimeout = 10_000;
    readTimeout = 10_000;
    writeTimeout = 10_000;
  ...
  }

```

**Comment by teolemon** [comment]
Fix by @policorn just merged
