### ISSUE TITLE
Crash when clicking on main photo to expand it

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-androidapp#709]
02-12 11:39:24.754 3659-3659/openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
 Process: openfoodfacts.github.scrachx.openfood, PID: 3659
 java.lang.RuntimeException: Unable to start activity ComponentInfo{openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.FullScreenImage}: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class uk.co.senab.photoview.PhotoView
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
     at android.app.ActivityThread.-wrap11(Unknown Source:0)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
     at android.os.Handler.dispatchMessage(Handler.java:106)
     at android.os.Looper.loop(Looper.java:164)
     at android.app.ActivityThread.main(ActivityThread.java:6494)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
  Caused by: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class uk.co.senab.photoview.PhotoView
  Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class uk.co.senab.photoview.PhotoView
  Caused by: java.lang.ClassNotFoundException: Didn't find class "uk.co.senab.photoview.PhotoView" on path: DexPathList[[zip file "/data/app/openfoodfacts.github.scrachx.openfood-aBJ8hLD0yld85a_5830ZMg==/base.apk"],nativeLibraryDirectories=[/data/app/openfoodfacts.github.scrachx.openfood-aBJ8hLD0yld85a_5830ZMg==/lib/arm64, /system/lib64, /vendor/lib64]]
     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
     at android.view.LayoutInflater.createView(LayoutInflater.java:606)
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
     at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
     at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
     at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
     at openfoodfacts.github.scrachx.openfood.views.BaseActivity.setContentView(BaseActivity.java:31)
     at openfoodfacts.github.scrachx.openfood.views.FullScreenImage.onCreate(FullScreenImage.java:27)
     at android.app.Activity.performCreate(Activity.java:6999)
     at android.app.Activity.performCreate(Activity.java:6990)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
     at android.app.ActivityThread.-wrap11(Unknown Source:0)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
     at android.os.Handler.dispatchMessage(Handler.java:106)
     at android.os.Looper.loop(Looper.java:164)
     at android.app.ActivityThread.main(ActivityThread.java:6494)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by huzaifaiftikhar** [comment]
@teolemon I've fixed this issue. Please merge.
