### ISSUE TITLE
Cannot add picture in some cases

### ISSUE THREAD

**Issue by oliver** [openfoodfacts/openfoodfacts-androidapp#75]
When adding a new product, sometimes the app won't use the picture I take with camera. I choose Take Picture, the camera opens, I take a picture, the buttons Verwerfen (Discard) and Speichern (Save) appear, I click Save, the OpenFood data entry mask reappears, but no photo is attached. I can try Take Picture again, but often this will still fail just like before.

This might be related to screen orientation: if I rotate the phone so that the left long side is down (so that the camera goes into widescreen, and the Discard/Save buttons are displayed on the left long side of the screen), it usually works fine (taken pictures are visible in the data entry mask). In any other orientation it usually fails.

This is on Samsung S4 Mini, with Android 4.4.2, OpenFood 0.1.12 (from F-Droid), and Kamera (com.sec.android.app.camera) 2.0.

**Comment by teolemon** [comment]
@oliver Can you reproduce with the current version ?

**Comment by oliver** [comment]
Tried with version 0.3 from F-Droid, but now I can't even get that far (it crashes as soon as I want to add a new product, or view a known product). Is there any way I can get you infos about these crashes from my phone? I don't have Android SDK available though.

Is it recommended to do a complete reinstall? I saw in Logcat app this warning:

> 11-11 18:43:58.907 E/AndroidRuntime(23770): java.lang.RuntimeException: Unable to start activity ComponentInfo{openfoodfacts.github.scrachx.openfood/openfoodfacts.github.scrachx.openfood.views.HistoryScanActivity}: android.database.sqlite.SQLiteException: no such table: SENDPRODUCT (code 1): , while compiling: ALTER TABLE SENDPRODUCT ADD UNIQUE (barcode)

**Comment by teolemon** [comment]
Same here
![screenshot_20161110-115114](https://cloud.githubusercontent.com/assets/1689815/20227174/7d006942-a84b-11e6-88ba-c16e6a116348.png)

**Comment by teolemon** [comment]
11-14 08:27:52.560 851-870/? I/ActivityManager: Displayed openfoodfacts.github.scrachx.openfood/.views.SaveProductOfflineActivity: +326ms
11-14 08:27:57.451 29841-29841/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: openfoodfacts.github.scrachx.openfood, PID: 29841
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
                                                       at openfoodfacts.github.scrachx.openfood.views.SaveProductOfflineActivity.onSaveProduct(SaveProductOfflineActivity.java:179)
                                                       at openfoodfacts.github.scrachx.openfood.views.SaveProductOfflineActivity_ViewBinding$5.doClick(SaveProductOfflineActivity_ViewBinding.java:91)
                                                       at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
                                                       at android.view.View.performClick(View.java:5204)
                                                       at android.view.View$PerformClick.run(View.java:21153)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-14 08:27:57.452 851-2191/? W/ActivityManager:   Force finishing activity openfoodfacts.github.scrachx.openfood/.views.SaveProductOfflineActivity

**Comment by Karljoones** [comment]
Hey @teolemon and @oliver is this still an issue? Very old issue I know but I want to close it if it no longer affects anyone.
