### ISSUE TITLE
App crashes on clicking "offline edit" option on Android version 4.4 and also when loading offline images

### ISSUE THREAD

**Issue by jaztriumph** [openfoodfacts/openfoodfacts-androidapp#753]
**Summary:** 

App crashes on clicking "offline edit" option on Android version 4.4. 

**System logs:**

```
openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
       Process: openfoodfacts.github.scrachx.openfood, PID: 31654
       android.view.InflateException: Binary XML file line #20: Error inflating class Button
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
       .
       .
       .
       Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_done_all.xml from drawable resource ID #0x7f080086
       at android.content.res.Resources.loadDrawable(Resources.java:2170)
       at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
       at android.widget.TextView.<init>(TextView.java:841)
       at android.widget.Button.<init>(Button.java:107)
       at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:70)
       at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:66)
       at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109)
       at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1016)
       at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1073)
       at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:172)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
       at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
       at openfoodfacts.github.scrachx.openfood.fragments.BaseFragment.createView(BaseFragment.java:17) 
       at openfoodfacts.github.scrachx.openfood.fragments.OfflineEditFragment.onCreateView(OfflineEditFragment.java:52) 
       .
       .
       .
       at dalvik.system.NativeStart.main(Native Method) 
       Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
       at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
       at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
       .
       .
       .
       
       createView(BaseFragment.java:17) 
       at openfoodfacts.github.scrachx.openfood.fragments.OfflineEditFragment.onCreateView(OfflineEditFragment.java:52) 
    
```

**Device and Android version:** 

HTC 820 G+
 Android 4.4 KITKAT

**Screen-shots:** 
![device-2018-02-15-060357](https://user-images.githubusercontent.com/22943390/36236118-5555a832-121a-11e8-8cf2-4081b2b2f28a.gif)

**Comment by jaztriumph** [comment]
@teolemon I would like to work on this.
