### ISSUE TITLE
app crashes just after logging in and clicking manage accounts

### ISSUE THREAD

**Issue by jaztriumph** [openfoodfacts/openfoodfacts-androidapp#756]
**Summary:** 

app crashes just after logging in and clicking manage accounts.

**Steps to reproduce:** 

just after logging in, in the navigation drawer header we can observe that the name is still anonymous and them on clicking manage accounts. 

**Add System logs:**

```
openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
Process: openfoodfacts.github.scrachx.openfood, PID: 463
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW pkg=com.android.chrome (has extras) }
   at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1638)
   at android.app.Instrumentation.execStartActivity(Instrumentation.java:1430)
   at android.app.Activity.startActivityForResult(Activity.java:3480)
   at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
   at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
   at android.app.Activity.startActivityForResult(Activity.java:3432)
   at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:732)
   at android.app.Activity.startActivity(Activity.java:3683)
   at android.support.v4.content.ContextCompat.startActivity(ContextCompat.java:143)
   at android.support.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:262)
   at openfoodfacts.github.scrachx.openfood.views.customtabs.CustomTabActivityHelper.openCustomTab(CustomTabActivityHelper.java:57)
   at openfoodfacts.github.scrachx.openfood.views.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:127)
   at openfoodfacts.github.scrachx.openfood.views.MainActivity$$Lambda$0.onProfileChanged(Unknown Source)
   at com.mikepenz.materialdrawer.AccountHeaderBuilder$7.onItemClick(AccountHeaderBuilder.java:1427)
   at com.mikepenz.materialdrawer.DrawerBuilder$6.onClick(DrawerBuilder.java:1768)
   at com.mikepenz.materialdrawer.DrawerBuilder$6.onClick(DrawerBuilder.java:1742)
   at com.mikepenz.fastadapter.FastAdapter$1.onClick(FastAdapter.java:580)
   at com.mikepenz.fastadapter.utils.EventHookUtil$1.onClick(EventHookUtil.java:72)
   at android.view.View.performClick(View.java:4463)
   at android.view.View$PerformClick.run(View.java:18770)
   at android.os.Handler.handleCallback(Handler.java:808)
   at android.os.Handler.dispatchMessage(Handler.java:103)
   at android.os.Looper.loop(Looper.java:193)
   at android.app.ActivityThread.main(ActivityThread.java:5333)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
   at dalvik.system.NativeStart.main(Native Method)
```

**Expected behavior:** 

user name in navigation drawer header should get updated after logging in and app should not crash.

**Device and Android version:** 

HTC 820 G+ Android 4.4 KITKAT,
one plus 5T   Android O.

**Screen-shots:** 
![login_error](https://user-images.githubusercontent.com/22943390/36242276-f5610c1a-1240-11e8-8858-c9e89b048443.gif)

**Comment by jaztriumph** [comment]
@teolemon I will be working on this

**Comment by teolemon** [comment]
I can reproduce. Manage accounts should open a Chrome Custom Tab to manage the account, until we have a native solution
https://world.openfoodfacts.org/cgi/user.pl?userid=XXXXX&type=edit
