### ISSUE TITLE
app crash when you go to item which is empty or incomplete

### ISSUE THREAD

**Issue by jaztriumph** [openfoodfacts/openfoodfacts-androidapp#761]
**Summary:** 

app crash when you go to item which is empty or incomplete, for example on this bar code :7613036024358 (incomplete).

**Steps to reproduce:** 

search by barcode 7613036024358.

**System logs:**
```
openfoodfacts.github.scrachx.openfood E/AndroidRuntime: FATAL EXCEPTION: main
Process: openfoodfacts.github.scrachx.openfood, PID: 11245
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.replace(java.lang.CharSequence, java.lang.CharSequence)' on a null object reference
at openfoodfacts.github.scrachx.openfood.models.Product.getPackaging(Product.java:319)
at openfoodfacts.github.scrachx.openfood.fragments.SummaryProductFragment.onViewCreated(SummaryProductFragment.java:138)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1430)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2209)
at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
.
.
.
```
**Device and Android version:** 

one plus 5T , Android O.

**Screen-shots:** 
![string_errror](https://user-images.githubusercontent.com/22943390/36261949-110f544e-128c-11e8-819c-0a92e1e5751e.gif)

**Comment by Shubham2320** [comment]
I would love to work on this issue if available.

**Comment by jaztriumph** [comment]
this happened due to changes in this PR #743

**Comment by jaztriumph** [comment]
@Shubham2320 I am working on this.
