### ISSUE TITLE
Forever loading on SplashScreen on OffDebug Variant 

### ISSUE THREAD

**Issue by sachincool** [openfoodfacts/openfoodfacts-androidapp#793]
**Summary:** 
The Splash Screen Keeps on Loading on `OffDebug` Variant 

**Steps to reproduce:** 
1 choose offDebug as your build variant
2 Build and run the variant on 7.1 Android 
3 Splash Screen with LoadToast is showing indeterminately. 

**Add System logs:**
There's no Error 
Only a bunch of Database create calls. 
**Expected behavior:** 
The App should run fine on android 7.1

**Observed behavior:** 
I checked further and got that it Leads to GetJson Asynktask to execute and get the json value. 
Afterwards it runs the preexecute and Doinbackground Perfectly but gets stucked on PostExecute. 
![device-2018-02-18-045801](https://user-images.githubusercontent.com/25671488/36346688-44a0b7d8-1469-11e8-84ca-e039bdc10901.png)
![1](https://user-images.githubusercontent.com/25671488/36346687-44559e92-1469-11e8-872d-a4b2471bfdb0.png)
![screenshot from 2018-02-18 04-59-17](https://user-images.githubusercontent.com/25671488/36346689-44e6ec6c-1469-11e8-830a-98c8fccf9d49.png)

**Device and Android version:** 
Android 7.1
*Yes, I would like to work on this issue*

**Comment by sachincool** [comment]
Yes i would like to Work on this issue.

**Comment by sachincool** [comment]
It is caused inside that `getAllergence` call And inside that call it calls the Overridden method `onFailure` 
Here is the proof:
![1](https://user-images.githubusercontent.com/25671488/36346770-34daae06-146b-11e8-934c-8b0c82e94178.png)

**Comment by sachincool** [comment]
on printing the stacktrace of the throwable `t`  i got this 
```
02-18 05:32:02.130 24333-24333/openfoodfacts.github.scrachx.openfood W/System.err: java.net.SocketException: Network is unreachable
02-18 05:32:02.131 24333-24333/openfoodfacts.github.scrachx.openfood W/System.err:     at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
        at java.net.Socket.connect(Socket.java:586)
        at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:69)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
02-18 05:32:02.132 24333-24333/openfoodfacts.github.scrachx.openfood W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:760)
```
If anybody got a clue on why is it happening in `getAllergance` method. Don't keep it to yourself :smile:

**Comment by policorn** [comment]
Hi @sachincool, I've been able to reproduce the issue, just as you mention, using a 7.0 image. The `java.net.PlainSocketImpl.socketConnect(Native Method)` warning made my thing something weird is going on. The URL `getAllergens()` is trying to retrieve can be accessed without errors outside the app (using a browser with it own TLS certificate stack, independent from the system, like chrome). Moreover, you cannot sign in, or get any asset from the OFF server. 

I captured the traffic with wireshark:

<img width="800" alt="screen shot 2018-02-21 at 00 50 48" src="https://user-images.githubusercontent.com/18316436/36455828-3a97b170-16a2-11e8-901a-ed005f941ff9.png">

As you can see, the TLS connection is failing during the handshake; and this is the very reason OFF is failing in this version. 

I found some articles mentioning the issue and how to solve it:

- https://stackoverflow.com/questions/39133437/sslhandshakeexception-handshake-failed-on-android-n-7-0#42047877
- https://issuetracker.google.com/issues/37122132
- https://community.letsencrypt.org/t/warning-android-7-0-clients-not-browsers-can-only-use-curve-prime256v1/23212

It requires a bit of work on the server side: nginx's config file (or the TLS terminator OFF is currently using) to allow `prime256v1` elliptic curve as fallback to make Android 7.0 devices to finish the TLS handshake, hence being able to retrieve assets from OFF server.

**Comment by sachincool** [comment]
Wow !! @policorn  I never thought i would see Wireshark and Android in the same room :open_mouth:

I'll get on the links you provided Thankyou So much for the help.  :heart_eyes:

**Comment by itchix** [comment]
You can see this file to resolve this issue : https://github.com/itchix/TestMVPAndroid/blob/88cf30e65756301464fc63c78ebe6ec47bdea4d8/app/src/main/java/com/scrachx/foodfacts/checker/utils/OkHttpUtil.java 
I use it to bypass the bug on Android 7.0

**Comment by policorn** [comment]
Hi @itchix, could we only force this weak cipher suite for Android 7.0 so the other Android versions can negotiate a stronger one if they support them?

**Comment by itchix** [comment]
https://github.com/openfoodfacts/openfoodfacts-androidapp/blob/master/app/src/main/java/openfoodfacts/github/scrachx/openfood/network/OpenFoodAPIClient.java#L84

You can verify the `android.os.Build.VERSION_CODES` and pass the good `httpClient`

**Comment by policorn** [comment]
Hi @sachincool, please implement the fix with @itchix's suggestions - Thanks!
